#!/bin/bash

echo make kdv8000e!

mkdir mcu
mkdir mcu/webroot
mkdir mcu/webroot2
mkdir mcu/conf
mkdir mcu/tool
mkdir mcu/ftp

#All  files check
#Exec files
file1=../../10-common/lib/release/linux/snmpd
file2=../../10-common/version/release/linux/mcu_8000e
file3=../../10-common/version/release/linux/mmp_8000e
file4=../../10-common/version/release/linux/prs_8000e
file5=../../10-common/version/release/linux/kdvlogserver
file6=../../10-common/version/release/linux/mcugk_redhat
file7=../../10-common/version/release/linux/pxyserverapp_redhat
file8=../../10-common/version/release/linux/detectee
#web files
#Web files, If English version, notice to modify here!
webrootfile1=../../10-common/version/release/win32/mcs/Mcs.cab
webrootfile2=../../10-common/version/release/win32/mcs/index.htm
webrootfile3=../../10-common/version/release/win32/gkcuiocx/GKCUIOcx.cab
webrootfile4=../../10-common/version/release/win32/gkcuiocx/index.htm
webrootfile5=../../10-common/version/release/win32/McsOutlookAddin/McsOutlookAddinSetup.exe
#script files
script1=../../60-mercury/8kelinuxcab/guard.sh
script2=../../60-mercury/8kelinuxcab/ethdetect.sh
script3=../../60-mercury/8kelinuxcab/ftpsetup.sh
script4=../../60-mercury/8kelinuxcab/apachesvrcfg
script5=../../60-mercury/8kelinuxcab/NetCap.sh


canmakebin=1
for file in $file1 $file2 $file3 $file4 $file5 $file6 $file7 $file8\
 $webrootfile1 $webrootfile2 $webrootfile3 $webrootfile4 $webrootfile5 \
 $script1 $script2 $script3 $script4 $script5
do
if [ ! -f $file ]
then
	echo err : $file not exist
	if [ $canmakebin -eq 0 ];then
		echo err : $file not exist >> err.txt
	else #first time in for 
		canmakebin=0
	  echo err : $file not exist > err.txt
	fi	

fi
done

if [ $canmakebin -eq 0 ];then
echo neccessary file needed ,can not makebin
exit -1
else
for appfile in $file1 $file2 $file3 $file4 $file5  $file6  $file7 $file8
do
	cp $appfile  mcu
done


#cp ../../10-common/version/release/linux/guard mcu
#cp ../../10-common/version/release/linux/kdvgk_8000e mcu
#cp ../../10-common/version/release/linux/kdvts_8000e mcu
#cp ../../10-common/version/release/linux/pxyserverapp_8000e mcu

#All SO Libs
cp ../../10-common/lib/release/linux/*.so mcu
cp ../../10-common/lib/release/linux/libintlc.so.5 mcu

#All font
#cp ../../90-nms8000e/install/mcufont/huawenxihei16-17.bin mcu
#cp ../../90-nms8000e/install/mcufont/huawenxihei22-22.bin mcu
#cp ../../90-nms8000e/install/mcufont/msuigothic10-21.bin mcu
#cp ../../90-nms8000e/install/mcufont/msuigothic21-33.bin mcu
#cp ../../90-nms8000e/install/mcufont/msuigothic9-17.bin mcu
#cp ../../90-nms8000e/install/mcufont/song-32-gb2312.bin mcu

cp ../../60-mercury/8kefont/*.bin mcu
cp ../font/kdvuni.ttf mcu

#webroot files£ºMCS
for webrootfile in $webrootfile1 $webrootfile2 
do
	cp $webrootfile  mcu/webroot
done
#copy mcs.htm
cp $webrootfile2 mcu/webroot/mcs.htm

#copy  McsOutlookAddinSetup.exe to webroot
cp $webrootfile5 mcu/webroot/outlook.exe

#webroot2 files£º GK
for gkwebrootfile in  $webrootfile3 $webrootfile4
do
	cp $gkwebrootfile  mcu/webroot2
done
#copy gk files to webroot
cp $webrootfile3 mcu/webroot
cp $webrootfile4 mcu/webroot/gkc.htm



#script 
for scriptfile in $script1 $script2 $script3 $script4 $script5
do
	cp $scriptfile mcu

done



#cfg
#cp ../../60-mercury/8kelinuxcab/pxysrvCfg.ini mcu/conf
#cp ../../60-mercury/8kelinuxcab/gkconfig.ini	mcu/conf



#image
cp ../../60-mercury/vmp8kelib/image/FILE_DTF_PATH_BMP_4v3.bmp mcu/ftp
cp ../../60-mercury/vmp8kelib/image/FILE_DTF_PATH_BMP_16v9.bmp mcu/ftp

#tool
cp ../../60-mercury/8kelinuxcab/vsftpd-2.0.5-16.el5.i386.rpm mcu/tool

chmod a+x mcu/snmpd
chmod a+x mcu/mcu_8000e
chmod a+x mcu/mmp_8000e
chmod a+x mcu/prs_8000e
chmod a+x  mcu/mcugk_redhat
chmod a+x  mcu/pxyserverapp_redhat
chmod a+x  mcu/kdvlogserver
chmod a+x  mcu/detectee

#chmod a+w  mcu/conf/gkconfig.ini
#chmod a+w	 mcu/conf/pxysrvCfg.ini


chmod a+x  mcu/tool/vsftpd-2.0.5-16.el5.i386.rpm

chmod a+x  mcu/apachesvrcfg
chmod a+x  mcu/guard.sh
#chmod a+x  mcu/netcfg.sh
chmod a+x  mcu/ethdetect.sh
chmod a+x  mcu/NetCap.sh

#tar
tar zcvf mcu.tar.gz ./mcu

#make BINary
#cat selfcab.sh mcu.tar.gz > mcusetup.bin
#cat selfupdate.sh mcu.tar.gz > mcuupdate.bin
#cat  selfcab.sh mcu.tar.gz > kdv8000esetup.bin
cat selfupdate.sh mcu.tar.gz > kdv8000g.bin
#chmod a+x mcusetup.bin
#chmod a+x mcuupdate.bin
#chmod a+x kdv8000esetup.bin
chmod a+x kdv8000g.bin

#cp mcusetup.bin ../../10-common/version/release/linux/mcu8000e_hw/mcusetup.bin
#cp mcuupdate.bin ../../10-common/version/release/linux/mcu8000e_hw/mcuupdate.bin
#cp  kdv8000esetup.bin ../../10-common/version/release/linux/kdv8000esetup.bin
cp  kdv8000g.bin ../../10-common/version/release/linux/kdv8000g.bin


#rm -f mcusetup.bin
#rm -f mcuupdate.bin
#rm -f kdv8000esetup.bin
rm -f kdv8000g.bin
rm -f mcu.tar.gz
rm -fr mcu

#echo make mcu self-extr-cab and update-cab completed! 
echo make kdv8000g.bin completed! 

fi