/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Wind River Systems
 **** Emissary SNMP MIB Compiler, version 7.0.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Fri Jan 18 16:29:41 2002
 **** from files:
 ****  ../mibs/rfc1213.mib, snmpmib2.mib
 ******************************************************************************
 ******************************************************************************
 */

#define LEAF_sysDescr	1
#define MINSIZE_sysDescr	0L
#define MAXSIZE_sysDescr	255L
#define LEAF_sysObjectID	2
#define LEAF_sysUpTime	3
#define LEAF_sysContact	4
#define MINSIZE_sysContact	0L
#define MAXSIZE_sysContact	255L
#define LEAF_sysName	5
#define MINSIZE_sysName	0L
#define MAXSIZE_sysName	255L
#define LEAF_sysLocation	6
#define MINSIZE_sysLocation	0L
#define MAXSIZE_sysLocation	255L
#define LEAF_sysServices	7
#define MIN_sysServices	0L
#define MAX_sysServices	127L
#define LEAF_ifNumber	1
#define LEAF_ifIndex	1
#define LEAF_ifDescr	2
#define MINSIZE_ifDescr	0L
#define MAXSIZE_ifDescr	255L
#define LEAF_ifType	3
#define VAL_ifType_other	1L
#define VAL_ifType_regular1822	2L
#define VAL_ifType_hdh1822	3L
#define VAL_ifType_ddn_x25	4L
#define VAL_ifType_rfc877_x25	5L
#define VAL_ifType_ethernet_csmacd	6L
#define VAL_ifType_iso88023_csmacd	7L
#define VAL_ifType_iso88024_tokenBus	8L
#define VAL_ifType_iso88025_tokenRing	9L
#define VAL_ifType_iso88026_man	10L
#define VAL_ifType_starLan	11L
#define VAL_ifType_proteon_10Mbit	12L
#define VAL_ifType_proteon_80Mbit	13L
#define VAL_ifType_hyperchannel	14L
#define VAL_ifType_fddi	15L
#define VAL_ifType_lapb	16L
#define VAL_ifType_sdlc	17L
#define VAL_ifType_ds1	18L
#define VAL_ifType_e1	19L
#define VAL_ifType_basicISDN	20L
#define VAL_ifType_primaryISDN	21L
#define VAL_ifType_propPointToPointSerial	22L
#define VAL_ifType_ppp	23L
#define VAL_ifType_softwareLoopback	24L
#define VAL_ifType_eon	25L
#define VAL_ifType_ethernet_3Mbit	26L
#define VAL_ifType_nsip	27L
#define VAL_ifType_slip	28L
#define VAL_ifType_ultra	29L
#define VAL_ifType_ds3	30L
#define VAL_ifType_sip	31L
#define VAL_ifType_frame_relay	32L
#define LEAF_ifMtu	4
#define LEAF_ifSpeed	5
#define LEAF_ifPhysAddress	6
#define LEAF_ifAdminStatus	7
#define VAL_ifAdminStatus_up	1L
#define VAL_ifAdminStatus_down	2L
#define VAL_ifAdminStatus_testing	3L
#define LEAF_ifOperStatus	8
#define VAL_ifOperStatus_up	1L
#define VAL_ifOperStatus_down	2L
#define VAL_ifOperStatus_testing	3L
#define LEAF_ifLastChange	9
#define LEAF_ifInOctets	10
#define LEAF_ifInUcastPkts	11
#define LEAF_ifInNUcastPkts	12
#define LEAF_ifInDiscards	13
#define LEAF_ifInErrors	14
#define LEAF_ifInUnknownProtos	15
#define LEAF_ifOutOctets	16
#define LEAF_ifOutUcastPkts	17
#define LEAF_ifOutNUcastPkts	18
#define LEAF_ifOutDiscards	19
#define LEAF_ifOutErrors	20
#define LEAF_ifOutQLen	21
#define LEAF_ifSpecific	22
#define LEAF_atIfIndex	1
#define LEAF_atPhysAddress	2
#define LEAF_atNetAddress	3
#define LEAF_ipForwarding	1
#define VAL_ipForwarding_forwarding	1L
#define VAL_ipForwarding_not_forwarding	2L
#define LEAF_ipDefaultTTL	2
#define LEAF_ipInReceives	3
#define LEAF_ipInHdrErrors	4
#define LEAF_ipInAddrErrors	5
#define LEAF_ipForwDatagrams	6
#define LEAF_ipInUnknownProtos	7
#define LEAF_ipInDiscards	8
#define LEAF_ipInDelivers	9
#define LEAF_ipOutRequests	10
#define LEAF_ipOutDiscards	11
#define LEAF_ipOutNoRoutes	12
#define LEAF_ipReasmTimeout	13
#define LEAF_ipReasmReqds	14
#define LEAF_ipReasmOKs	15
#define LEAF_ipReasmFails	16
#define LEAF_ipFragOKs	17
#define LEAF_ipFragFails	18
#define LEAF_ipFragCreates	19
#define LEAF_ipAdEntAddr	1
#define LEAF_ipAdEntIfIndex	2
#define LEAF_ipAdEntNetMask	3
#define LEAF_ipAdEntBcastAddr	4
#define LEAF_ipAdEntReasmMaxSize	5
#define MIN_ipAdEntReasmMaxSize	0L
#define MAX_ipAdEntReasmMaxSize	65535L
#define LEAF_ipRouteDest	1
#define LEAF_ipRouteIfIndex	2
#define LEAF_ipRouteMetric1	3
#define LEAF_ipRouteMetric2	4
#define LEAF_ipRouteMetric3	5
#define LEAF_ipRouteMetric4	6
#define LEAF_ipRouteNextHop	7
#define LEAF_ipRouteType	8
#define VAL_ipRouteType_other	1L
#define VAL_ipRouteType_invalid	2L
#define VAL_ipRouteType_direct	3L
#define VAL_ipRouteType_indirect	4L
#define LEAF_ipRouteProto	9
#define VAL_ipRouteProto_other	1L
#define VAL_ipRouteProto_local	2L
#define VAL_ipRouteProto_netmgmt	3L
#define VAL_ipRouteProto_icmp	4L
#define VAL_ipRouteProto_egp	5L
#define VAL_ipRouteProto_ggp	6L
#define VAL_ipRouteProto_hello	7L
#define VAL_ipRouteProto_rip	8L
#define VAL_ipRouteProto_is_is	9L
#define VAL_ipRouteProto_es_is	10L
#define VAL_ipRouteProto_ciscoIgrp	11L
#define VAL_ipRouteProto_bbnSpfIgp	12L
#define VAL_ipRouteProto_ospf	13L
#define VAL_ipRouteProto_bgp	14L
#define LEAF_ipRouteAge	10
#define LEAF_ipRouteMask	11
#define LEAF_ipRouteMetric5	12
#define LEAF_ipRouteInfo	13
#define LEAF_ipNetToMediaIfIndex	1
#define LEAF_ipNetToMediaPhysAddress	2
#define LEAF_ipNetToMediaNetAddress	3
#define LEAF_ipNetToMediaType	4
#define VAL_ipNetToMediaType_other	1L
#define VAL_ipNetToMediaType_invalid	2L
#define VAL_ipNetToMediaType_dynamic	3L
#define VAL_ipNetToMediaType_static	4L
#define LEAF_ipRoutingDiscards	23
#define LEAF_icmpInMsgs	1
#define LEAF_icmpInErrors	2
#define LEAF_icmpInDestUnreachs	3
#define LEAF_icmpInTimeExcds	4
#define LEAF_icmpInParmProbs	5
#define LEAF_icmpInSrcQuenchs	6
#define LEAF_icmpInRedirects	7
#define LEAF_icmpInEchos	8
#define LEAF_icmpInEchoReps	9
#define LEAF_icmpInTimestamps	10
#define LEAF_icmpInTimestampReps	11
#define LEAF_icmpInAddrMasks	12
#define LEAF_icmpInAddrMaskReps	13
#define LEAF_icmpOutMsgs	14
#define LEAF_icmpOutErrors	15
#define LEAF_icmpOutDestUnreachs	16
#define LEAF_icmpOutTimeExcds	17
#define LEAF_icmpOutParmProbs	18
#define LEAF_icmpOutSrcQuenchs	19
#define LEAF_icmpOutRedirects	20
#define LEAF_icmpOutEchos	21
#define LEAF_icmpOutEchoReps	22
#define LEAF_icmpOutTimestamps	23
#define LEAF_icmpOutTimestampReps	24
#define LEAF_icmpOutAddrMasks	25
#define LEAF_icmpOutAddrMaskReps	26
#define LEAF_tcpRtoAlgorithm	1
#define VAL_tcpRtoAlgorithm_other	1L
#define VAL_tcpRtoAlgorithm_constant	2L
#define VAL_tcpRtoAlgorithm_rsre	3L
#define VAL_tcpRtoAlgorithm_vanj	4L
#define LEAF_tcpRtoMin	2
#define LEAF_tcpRtoMax	3
#define LEAF_tcpMaxConn	4
#define LEAF_tcpActiveOpens	5
#define LEAF_tcpPassiveOpens	6
#define LEAF_tcpAttemptFails	7
#define LEAF_tcpEstabResets	8
#define LEAF_tcpCurrEstab	9
#define LEAF_tcpInSegs	10
#define LEAF_tcpOutSegs	11
#define LEAF_tcpRetransSegs	12
#define LEAF_tcpConnState	1
#define VAL_tcpConnState_closed	1L
#define VAL_tcpConnState_listen	2L
#define VAL_tcpConnState_synSent	3L
#define VAL_tcpConnState_synReceived	4L
#define VAL_tcpConnState_established	5L
#define VAL_tcpConnState_finWait1	6L
#define VAL_tcpConnState_finWait2	7L
#define VAL_tcpConnState_closeWait	8L
#define VAL_tcpConnState_lastAck	9L
#define VAL_tcpConnState_closing	10L
#define VAL_tcpConnState_timeWait	11L
#define VAL_tcpConnState_deleteTCB	12L
#define LEAF_tcpConnLocalAddress	2
#define LEAF_tcpConnLocalPort	3
#define MIN_tcpConnLocalPort	0L
#define MAX_tcpConnLocalPort	65535L
#define LEAF_tcpConnRemAddress	4
#define LEAF_tcpConnRemPort	5
#define MIN_tcpConnRemPort	0L
#define MAX_tcpConnRemPort	65535L
#define LEAF_tcpInErrs	14
#define LEAF_tcpOutRsts	15
#define LEAF_udpInDatagrams	1
#define LEAF_udpNoPorts	2
#define LEAF_udpInErrors	3
#define LEAF_udpOutDatagrams	4
#define LEAF_udpLocalAddress	1
#define LEAF_udpLocalPort	2
#define MIN_udpLocalPort	0L
#define MAX_udpLocalPort	65535L
#define LEAF_snmpInPkts	1
#define LEAF_snmpOutPkts	2
#define LEAF_snmpInBadVersions	3
#define LEAF_snmpInBadCommunityNames	4
#define LEAF_snmpInBadCommunityUses	5
#define LEAF_snmpInASNParseErrs	6
#define LEAF_snmpInTooBigs	8
#define LEAF_snmpInNoSuchNames	9
#define LEAF_snmpInBadValues	10
#define LEAF_snmpInReadOnlys	11
#define LEAF_snmpInGenErrs	12
#define LEAF_snmpInTotalReqVars	13
#define LEAF_snmpInTotalSetVars	14
#define LEAF_snmpInGetRequests	15
#define LEAF_snmpInGetNexts	16
#define LEAF_snmpInSetRequests	17
#define LEAF_snmpInGetResponses	18
#define LEAF_snmpInTraps	19
#define LEAF_snmpOutTooBigs	20
#define LEAF_snmpOutNoSuchNames	21
#define LEAF_snmpOutBadValues	22
#define LEAF_snmpOutGenErrs	24
#define LEAF_snmpOutGetRequests	25
#define LEAF_snmpOutGetNexts	26
#define LEAF_snmpOutSetRequests	27
#define LEAF_snmpOutGetResponses	28
#define LEAF_snmpOutTraps	29
#define LEAF_snmpEnableAuthenTraps	30
#define VAL_snmpEnableAuthenTraps_enabled	1L
#define VAL_snmpEnableAuthenTraps_disabled	2L


