#!/bin/sh

OPTION=`echo $1 | tr "A-Z" "a-z"`

cd prj_linux


if [ "$OPTION" != "noclean" ]; then
           make -f makefile_linux_d clean;
fi

make -f makefile_linux_d 1> ../../../10-common/version/compileinfo/watchclient_linux_d.txt 2>&1
make -f makefile_linux_d install
echo makefile_linux_d completed!

if [ "$OPTION" != "noclean" ]; then
           make -f makefile_linux_r clean;
fi

make -f makefile_linux_r 1> ../../../10-common/version/compileinfo/watchclient_linux_r.txt 2>&1
make -f makefile_linux_r install
echo makefile_linux_r completed!

cd ..