#ifndef _GKMMCUERR_H_
#define _GKMMCUERR_H_
#define GKM_MCU_REQ_WRONGPARAMS			1	/*注册请求事务错误*/
#define GKM_MCU_RESOURCE_UNAVAILABLE	2	/* GRJ, RRJ, ARJ, LRJ网守资源耗尽 */
#define GKM_MCU_INSUFFICIENT_BAND		3	/* BRJ带宽不足 */
#define GKM_MCU_INVALID_REVISION		4	/* GRJ, RRJ, BRJ 不合法的修改*/
#define GKM_MCU_INVALID_CALLADDR		5	/* RRJ 不合法的呼叫地址*/
#define GKM_MCU_INVALID_RASADDR			6	/* RRJ 不合法的RAS地址*/
#define GKM_MCU_INVALID_ENDPOINTTYPE	7       /* RRJ 不合法的终端类型*/
#define GKM_MCU_INVALID_PERMISSION		8	/* ARJ - 权限不合法*/
#define GKM_MCU_INVALID_CONFERENCEID	9	/* BRJ - 会议ID*/
#define GKM_MCU_INVALID_ENDPOINTID		10	/*终端ID*/
#define GKM_MCU_CALLER_NOT_REGED		11	/* ARJ未注册 */
#define GKM_MCU_CALLED_PARTYNOTREG		12	/* ARJ - 地址翻译错误*/
#define GKM_MCU_DISCOVRY_REQUIRED		13	/* RRJ - 注册信息需要更新*/
#define GKM_MCU_DUPLICATE_ALIAS			14	/* RRJ - 别名已经注册 */
#define GKM_MCU_TRANSPORTNOTSUPPORTED	15	/* RRJ - 多个传输*/
#define GKM_MCU_CALLINPROGRESS			16	/* URJ - 正在处理中*/
#define GKM_MCU_REQUESTTODROPOTHER		17	/* DRJ - 不能够释放其它的带宽*/
#define GKM_MCU_NOTREGISTERED			18	/* DRJ, LRJ, INAK - 未注册*/
#define GKM_MCU_UNDEFINEDREASON			19	/* GRJ, RRJ, URJ, ARJ, BRJ, LRJ, INAK */
#define GKM_MCU_REASONNOTBOUND			20	/* BRJ - */
#define GKM_MCU_NOTCURRENTREGISTERED	21	/* URJ - 当前未注册*/
#define GKM_MCU_REQUESTDENIED			22	/* ARJ - 未设置带宽*/
#define GKM_MCU_LOCATIONNOTFOUND		23	/* LRJ - 未发现 */
#define GKM_MCU_SECURITYDENID			24	/* GRJ, RRJ, URJ, ARJ, BRJ, LRJ, DRJ, INAK */
#define GKM_MCU_QOSNOTSUPPORTED			25	/* RRJ */
#define GKM_MCU_INVALID_ALIAS			26	/* RRJ - 别名不合法*/
#define GKM_MCU_PERMISSIONDENIED		27	/* URJ - 不能操作*/
#define GKM_MCU_QOSCONTROLNOTSUPPORTED	28	/* ARJ */
#define GKM_MCU_INCOMPLETEADDR			29	/* ARJ, LRJ 地址信息不完整*/
#define GKM_MCU_FULLREGREQUIRED			30	/* RRJ */
#define GKM_MCU_ROUTECALLTOSCN			31	/* ARJ, LRJ */
#define GKM_MCU_ALIASINCONSISTENT		32	/* ARJ, LRJ - 多别名对应对象模糊 */
#define GKM_MCU_REGNOTSUPPORTED			33	/* RRJ */
#define GKM_MCU_INVALID_TERMINALALIAS	34	/* RRJ */
#define GKM_MCU_EXCEEDCALLCAPACITY		35	/* ARJ - 能力不足*/
#define GKM_MCU_COLLECTDESTINATION		36	/* ARJ */
#define GKM_MCU_COLLECTPIN				37	/* ARJ */
#define GKM_MCU_GENERICDATA				38	/* GRJ, RRJ, ARJ, LRJ */
#define GKM_MCU_FEATURENOTSUPPORTED		39	/* GRJ, RRJ, ARJ, LRJ */
#define GKM_MCU_HOPCOUNTEXCEEDED		40	/* LRJ */

#define GKM_MCU_EXCEPTION				41  /*事务处理中出现异常*/
#define GKM_MCU_ERRSTATE				42  /*错误状态*/
#endif