/******************************************************************************
 ******************************************************************************
 **** This file was automatically generated by Wind River Systems
 **** Emissary SNMP MIB Compiler, version 7.0.
 **** This file was generated using the -leaf switch.
 **** 
 **** This file #defines C preprocessor macros providing a variety of
 **** information for the leaf objects in the MIB.
 **** 
 **** The file includes a LEAF_xxx macro for each leaf object in the
 **** MIB (xxx is replaced by the object's name).  The value of the
 **** LEAF_xxx macro is the final component of the object's object
 **** identifier.
 **** 
 **** If the object's SYNTAX clause included named INTEGER values,
 **** then there is a VAL_xxx_yyy macro for each named value (xxx is
 **** replaced by the object's name and yyy by the value's name).  The
 **** value of the VAL_xxx_yyy macro is the value associated with the
 **** named value.
 **** 
 **** If the object's SYNTAX clause specified a set of range limitations
 **** for the value of the object, then there are one or more sets of
 **** MIN_xxx and MAX_xxx macros specifying the lower and upper bound of
 **** each range limitation.
 **** 
 **** If the object's SYNTAX clause specified a set of size constraints
 **** for the value of the object, then there are one or more sets of
 **** MINSIZE_xxx and MAXSIZE_xxx macros specifying the lower and upper
 **** bound of each size constraint.  (If the size constraint is a single
 **** value rather than a range then the MINSIZE_xxx and MAXSIZE_xxx
 **** macros are replaced by a single SIZE_xxx macro.)
 **** 
 **** DO NOT MODIFY THIS FILE BY HAND.
 **** 
 **** Last build date: Mon Dec 15 13:27:29 2003
 **** from files:
 ****  kdv.smi, kdvmcu.mib
 ******************************************************************************
 ******************************************************************************
 */

#define LEAF_mcusysState	1
#define VAL_mcusysState_running	1L
#define VAL_mcusysState_reboot	2L
#define VAL_mcusysState_standby	3L
#define LEAF_mcusysTime	2
#define SIZE_mcusysTime	14L
#define LEAF_mcusysFtpFileName	3
#define MINSIZE_mcusysFtpFileName	0L
#define MAXSIZE_mcusysFtpFileName	255L
#define LEAF_mcusysConfigVersion	4
#define SIZE_mcusysConfigVersion	14L
#define LEAF_mcusysSoftwareVersion	5
#define MINSIZE_mcusysSoftwareVersion	0L
#define MAXSIZE_mcusysSoftwareVersion	255L
#define LEAF_mcusysFTPUser	6
#define MINSIZE_mcusysFTPUser	0L
#define MAXSIZE_mcusysFTPUser	32L
#define LEAF_mcusysFTPPassword	7
#define MINSIZE_mcusysFTPPassword	0L
#define MAXSIZE_mcusysFTPPassword	32L
#define LEAF_mcusysConfigErrorString	8
#define MINSIZE_mcusysConfigErrorString	0L
#define MAXSIZE_mcusysConfigErrorString	255L
#define LEAF_mcusysLayer	9
#define MIN_mcusysLayer	1L
#define MAX_mcusysLayer	4L
#define LEAF_mcusysSlot	10
#define MIN_mcusysSlot	17L
#define MAX_mcusysSlot	17L
//#define LEAF_mcusysHardwareType	11
//#define VAL_mcusysHardwareType_kdv8000	1L
//#define VAL_mcusysHardwareType_kdv8000b	2L
#define LEAF_mcunetVcIpIndex	1
#define LEAF_mcunetGwIpIndex	2
#define LEAF_mcunetGKIpAddr	3
#define LEAF_mcunetMulticastIpAddr	4
#define LEAF_mcunetMulticastPort	5
#define LEAF_mcunetStartRecvPort	6
#define LEAF_mcunetTrapRcvEntIpAddr	1
#define LEAF_mcunetTrapRcvEntCommunity	2
#define MINSIZE_mcunetTrapRcvEntCommunity	0L
#define MAXSIZE_mcunetTrapRcvEntCommunity	31L
#define LEAF_mcunetTrapRcvEntExist	3
#define VAL_mcunetTrapRcvEntExist_true	1L
#define VAL_mcunetTrapRcvEntExist_false	2L
#define LEAF_mcunetTrapEntryAddIp	2
#define LEAF_mcunetTrapEntryAddCommunity	3
#define MINSIZE_mcunetTrapEntryAddCommunity	0L
#define MAXSIZE_mcunetTrapEntryAddCommunity	255L
#define LEAF_mcunetTrapEntryAddEnable	4
#define LEAF_mcunetEthernetCardEntIndex	1
#define LEAF_mcunetEthernetCardEntIpAddr	2
#define LEAF_mcunetEthernetCardEntMask	3
#define LEAF_mcunetEthernetCardEntPhyAddr	4
#define LEAF_mcunetEthernetCardEntExist	5
#define VAL_mcunetEthernetCardEntExist_true	1L
#define VAL_mcunetEthernetCardEntExist_false	2L
#define LEAF_mcueqpMixerEntId	1
#define MIN_mcueqpMixerEntId	1L
#define MAX_mcueqpMixerEntId	255L
#define LEAF_mcueqpMixerEntPort	2
#define LEAF_mcueqpMixerEntSwitchBrdId	3
#define LEAF_mcueqpMixerEntAlias	4
#define MINSIZE_mcueqpMixerEntAlias	0L
#define MAXSIZE_mcueqpMixerEntAlias	31L
#define LEAF_mcueqpMixerEntRunningBrdId	5
#define LEAF_mcueqpMixerEntIpAddr	6
#define LEAF_mcueqpMixerEntMixStartPort	7
#define LEAF_mcueqpMixerEntMaxMixGroupNum	8
#define LEAF_mcueqpMixerEntConnState	9
#define VAL_mcueqpMixerEntConnState_online	1L
#define VAL_mcueqpMixerEntConnState_offline	2L
#define VAL_mcueqpMixerEntConnState_unknown	3L
#define LEAF_mcueqpMixerEntExist	10
#define LEAF_mcueqpRecorderEntId	1
#define MIN_mcueqpRecorderEntId	1L
#define MAX_mcueqpRecorderEntId	16L
#define LEAF_mcueqpRecorderEntPort	2
#define LEAF_mcueqpRecorderEntSwitchBrdId	3
#define LEAF_mcueqpRecorderEntAlias	4
#define MINSIZE_mcueqpRecorderEntAlias	0L
#define MAXSIZE_mcueqpRecorderEntAlias	15L
#define LEAF_mcueqpRecorderEntIpAddr	5
#define LEAF_mcueqpRecorderEntRecvStartPort	6
#define LEAF_mcueqpRecorderEntRecordChannelNum	7
#define LEAF_mcueqpRecorderEntPlayChannelNum	8
#define LEAF_mcueqpRecorderEntConnState	9
#define VAL_mcueqpRecorderEntConnState_online	1L
#define VAL_mcueqpRecorderEntConnState_offline	2L
#define VAL_mcueqpRecorderEntConnState_unknown	3L
#define LEAF_mcueqpRecorderEntExist	10
#define VAL_mcueqpRecorderEntExist_true	1L
#define VAL_mcueqpRecorderEntExist_false	2L
#define LEAF_mcueqpTVWallEntId	1
#define LEAF_mcueqpTVWallEntAlias	2
#define MINSIZE_mcueqpTVWallEntAlias	0L
#define MAXSIZE_mcueqpTVWallEntAlias	15L
#define LEAF_mcueqpTVWallEntRunningBrdId	3
#define LEAF_mcueqpTVWallEntIpAddr	4
#define LEAF_mcueqpTVWallEntDivStyle	5
#define VAL_mcueqpTVWallEntDivStyle_level	1L
#define LEAF_mcueqpTVWallEntDivNum	6
#define LEAF_mcueqpTVWallEntVideoStartRecvPort	7
#define LEAF_mcueqpTVWallEntConnState	8
#define VAL_mcueqpTVWallEntConnState_online	1L
#define VAL_mcueqpTVWallEntConnState_offline	2L
#define VAL_mcueqpTVWallEntConnState_unknown	3L
#define LEAF_mcueqpTVWallEntExist	9
#define VAL_mcueqpTVWallEntExist_true	1L
#define VAL_mcueqpTVWallEntExist_false	2L
#define LEAF_mcueqpDcsId	1
#define MIN_mcueqpDcsId	1L
#define MAX_mcueqpDcsId	255L
#define LEAF_mcueqpDcsConnState	2
#define VAL_mcueqpDcsConnState_online	1L
#define VAL_mcueqpDcsConnState_offline	2L
#define VAL_mcueqpDcsConnState_unknown	3L
#define LEAF_mcueqpVMPEntId	1
#define LEAF_mcueqpVMPEntPort	2
#define LEAF_mcueqpVMPEntSwitchBrdId	3
#define LEAF_mcueqpVMPEntAlias	4
#define MINSIZE_mcueqpVMPEntAlias	0L
#define MAXSIZE_mcueqpVMPEntAlias	15L
#define LEAF_mcueqpVMPEntRunningBrdId	5
#define LEAF_mcueqpVMPEntIpAddr	6
#define LEAF_mcueqpVMPEntStartRecvPort	7
#define LEAF_mcueqpVMPEntConnState	9
#define VAL_mcueqpVMPEntConnState_online	1L
#define VAL_mcueqpVMPEntConnState_offline	2L
#define VAL_mcueqpVMPEntConnState_unknown	3L
#define LEAF_mcueqpVMPEntExist	10
#define VAL_mcueqpVMPEntExist_true	1L
#define VAL_mcueqpVMPEntExist_false	2L
#define LEAF_mcueqpBasEntId	1
#define LEAF_mcueqpBasEntPort	2
#define LEAF_mcueqpBasEntSwitchBrdId	3
#define LEAF_mcueqpBasEntAlias	4
#define MINSIZE_mcueqpBasEntAlias	0L
#define MAXSIZE_mcueqpBasEntAlias	15L
#define LEAF_mcueqpBasEntRunningBrdId	5
#define LEAF_mcueqpBasEntIpAddr	6
#define LEAF_mcueqpBasEntStartRecvPort	7
#define LEAF_mcueqpBasEntConnState	9
#define VAL_mcueqpBasEntConnState_online	1L
#define VAL_mcueqpBasEntConnState_offline	2L
#define VAL_mcueqpBasEntConnState_unknown	3L
#define LEAF_mcueqpBasEntExist	10
#define VAL_mcueqpBasEntExist_true	1L
#define VAL_mcueqpBasEntExist_false	2L
#define LEAF_mcueqpNetSyncMode	1
#define VAL_mcueqpNetSyncMode_sync_freerun	1L
#define VAL_mcueqpNetSyncMode_sync_trace	2L
#define LEAF_mcueqpNetSyncDTSlot	2
#define MIN_mcueqpNetSyncDTSlot	0L
#define MAX_mcueqpNetSyncDTSlot	14L
#define LEAF_mcueqpNetSyncE1Index	3
#define MIN_mcueqpNetSyncE1Index	0L
#define MAX_mcueqpNetSyncE1Index	7L
#define LEAF_mcueqpNetSyncState	4
#define VAL_mcueqpNetSyncState_clock_lock	1L
#define VAL_mcueqpNetSyncState_clock_unlock	2L
#define LEAF_mcueqpBrdCfgEntId	1
#define LEAF_mcueqpBrdCfgEntLayer	2
#define LEAF_mcueqpBrdCfgEntSlot	3
#define LEAF_mcueqpBrdCfgEntType	4
#define VAL_mcueqpBrdCfgEntType_board_dti	1L
#define VAL_mcueqpBrdCfgEntType_board_dic	2L
#define VAL_mcueqpBrdCfgEntType_board_cri	3L
#define VAL_mcueqpBrdCfgEntType_board_nodefine	255L
#define LEAF_mcueqpBrdCfgEntStatus	5
#define VAL_mcueqpBrdCfgEntStatus_inline	1L
#define VAL_mcueqpBrdCfgEntStatus_offline	2L
#define LEAF_mcueqpBrdCfgEntVersion	6
#define MINSIZE_mcueqpBrdCfgEntVersion	0L
#define MAXSIZE_mcueqpBrdCfgEntVersion	255L
#define LEAF_mcueqpBrdCfgEntIpAddr	7
#define LEAF_mcueqpBrdCfgEntModule	8
#define MINSIZE_mcueqpBrdCfgEntModule	0L
#define MAXSIZE_mcueqpBrdCfgEntModule	255L
#define LEAF_mcueqpBrdCfgEntPanelLed	9
#define LEAF_mcueqpMgtState	1
#define LEAF_mcueqpMgtUpdateSoftware	2
#define LEAF_mcueqpMgtBitErrorTest	3
#define LEAF_mcueqpMgtTimeSync	4
#define LEAF_mcueqpMgtSelfTest	5
#define LEAF_mcueqpMgtE1Operate	6
#define LEAF_mcuId	1
#define MIN_mcuId	1L
#define MAX_mcuId	255L
#define LEAF_mcuAlias	2
#define MINSIZE_mcuAlias	0L
#define MAXSIZE_mcuAlias	31L
#define LEAF_mcuE164Number	3
#define MINSIZE_mcuE164Number	0L
#define MAXSIZE_mcuE164Number	9L
#define LEAF_mcuMmcuNeedBAS	4
#define VAL_mcuMmcuNeedBAS_true	1L
#define VAL_mcuMmcuNeedBAS_false	2L
#define LEAF_mcuTerminalIpEntIpAddr	1
#define LEAF_mcuTerminalIpEntExist	2
#define VAL_mcuTerminalIpEntExist_true	1L
#define VAL_mcuTerminalIpEntExist_false	2L
#define LEAF_mcupfmAlarmStamp	1
#define LEAF_mcupfmAlarmEntSerialNo	1
#define LEAF_mcupfmAlarmEntAlarmCode	2
#define LEAF_mcupfmAlarmEntObjType	3
#define LEAF_mcupfmAlarmEntObject	4
#define MINSIZE_mcupfmAlarmEntObject_1	0L
#define MAXSIZE_mcupfmAlarmEntObject_1	2L
#define MINSIZE_mcupfmAlarmEntObject_2	4L
#define MAXSIZE_mcupfmAlarmEntObject_2	5L
#define LEAF_mcupfmAlarmEntTime	5
#define SIZE_mcupfmAlarmEntTime	19L
