//
// mcspduv2.h
//
// Code automatically generated by asnparse.
//

#if ! H323_DISABLE_MCS_PROTOCOL

#ifndef __MCS_PROTOCOL_H
#define __MCS_PROTOCOL_H

#ifdef P_USE_PRAGMA
#pragma interface
#endif

#include <ptclib/asner.h>

//
// ChannelId
//

class MCS_PROTOCOL_ChannelId : public PASN_Integer
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_ChannelId, PASN_Integer);
#endif
  public:
    MCS_PROTOCOL_ChannelId(unsigned tag = UniversalInteger, TagClass tagClass = UniversalTagClass);

    MCS_PROTOCOL_ChannelId & operator=(int v);
    MCS_PROTOCOL_ChannelId & operator=(unsigned v);
    PObject * Clone() const;
};


//
// StaticChannelId
//

class MCS_PROTOCOL_StaticChannelId : public PASN_Integer
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_StaticChannelId, PASN_Integer);
#endif
  public:
    MCS_PROTOCOL_StaticChannelId(unsigned tag = UniversalInteger, TagClass tagClass = UniversalTagClass);

    MCS_PROTOCOL_StaticChannelId & operator=(int v);
    MCS_PROTOCOL_StaticChannelId & operator=(unsigned v);
    PObject * Clone() const;
};


//
// DynamicChannelId
//

class MCS_PROTOCOL_DynamicChannelId : public PASN_Integer
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_DynamicChannelId, PASN_Integer);
#endif
  public:
    MCS_PROTOCOL_DynamicChannelId(unsigned tag = UniversalInteger, TagClass tagClass = UniversalTagClass);

    MCS_PROTOCOL_DynamicChannelId & operator=(int v);
    MCS_PROTOCOL_DynamicChannelId & operator=(unsigned v);
    PObject * Clone() const;
};


//
// UserId
//

class MCS_PROTOCOL_UserId : public MCS_PROTOCOL_DynamicChannelId
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_UserId, MCS_PROTOCOL_DynamicChannelId);
#endif
  public:
    MCS_PROTOCOL_UserId(unsigned tag = UniversalInteger, TagClass tagClass = UniversalTagClass);

    MCS_PROTOCOL_UserId & operator=(int v);
    MCS_PROTOCOL_UserId & operator=(unsigned v);
    PObject * Clone() const;
};


//
// PrivateChannelId
//

class MCS_PROTOCOL_PrivateChannelId : public MCS_PROTOCOL_DynamicChannelId
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_PrivateChannelId, MCS_PROTOCOL_DynamicChannelId);
#endif
  public:
    MCS_PROTOCOL_PrivateChannelId(unsigned tag = UniversalInteger, TagClass tagClass = UniversalTagClass);

    MCS_PROTOCOL_PrivateChannelId & operator=(int v);
    MCS_PROTOCOL_PrivateChannelId & operator=(unsigned v);
    PObject * Clone() const;
};


//
// AssignedChannelId
//

class MCS_PROTOCOL_AssignedChannelId : public MCS_PROTOCOL_DynamicChannelId
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_AssignedChannelId, MCS_PROTOCOL_DynamicChannelId);
#endif
  public:
    MCS_PROTOCOL_AssignedChannelId(unsigned tag = UniversalInteger, TagClass tagClass = UniversalTagClass);

    MCS_PROTOCOL_AssignedChannelId & operator=(int v);
    MCS_PROTOCOL_AssignedChannelId & operator=(unsigned v);
    PObject * Clone() const;
};


//
// TokenId
//

class MCS_PROTOCOL_TokenId : public PASN_Integer
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TokenId, PASN_Integer);
#endif
  public:
    MCS_PROTOCOL_TokenId(unsigned tag = UniversalInteger, TagClass tagClass = UniversalTagClass);

    MCS_PROTOCOL_TokenId & operator=(int v);
    MCS_PROTOCOL_TokenId & operator=(unsigned v);
    PObject * Clone() const;
};


//
// TokenStatus
//

class MCS_PROTOCOL_TokenStatus : public PASN_Enumeration
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TokenStatus, PASN_Enumeration);
#endif
  public:
    MCS_PROTOCOL_TokenStatus(unsigned tag = UniversalEnumeration, TagClass tagClass = UniversalTagClass);

    enum Enumerations {
      e_notInUse,
      e_selfGrabbed,
      e_otherGrabbed,
      e_selfInhibited,
      e_otherInhibited,
      e_selfRecipient,
      e_selfGiving,
      e_otherGiving
    };

    MCS_PROTOCOL_TokenStatus & operator=(unsigned v);
    PObject * Clone() const;
};


//
// DataPriority
//

class MCS_PROTOCOL_DataPriority : public PASN_Enumeration
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_DataPriority, PASN_Enumeration);
#endif
  public:
    MCS_PROTOCOL_DataPriority(unsigned tag = UniversalEnumeration, TagClass tagClass = UniversalTagClass);

    enum Enumerations {
      e_top,
      e_high,
      e_medium,
      e_low
    };

    MCS_PROTOCOL_DataPriority & operator=(unsigned v);
    PObject * Clone() const;
};


//
// Segmentation
//

class MCS_PROTOCOL_Segmentation : public PASN_BitString
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_Segmentation, PASN_BitString);
#endif
  public:
    MCS_PROTOCOL_Segmentation(unsigned tag = UniversalBitString, TagClass tagClass = UniversalTagClass);

    PObject * Clone() const;
};


//
// DomainParameters
//

class MCS_PROTOCOL_DomainParameters : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_DomainParameters, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_DomainParameters(unsigned tag = UniversalSequence, TagClass tagClass = UniversalTagClass);

    PASN_Integer m_maxChannelIds;
    PASN_Integer m_maxUserIds;
    PASN_Integer m_maxTokenIds;
    PASN_Integer m_numPriorities;
    PASN_Integer m_minThroughput;
    PASN_Integer m_maxHeight;
    PASN_Integer m_maxMCSPDUsize;
    PASN_Integer m_protocolVersion;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// Connect-Initial
//

class MCS_PROTOCOL_Connect_Initial : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_Connect_Initial, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_Connect_Initial(unsigned tag = 101, TagClass tagClass = ApplicationTagClass);

    PASN_OctetString m_callingDomainSelector;
    PASN_OctetString m_calledDomainSelector;
    PASN_Boolean m_upwardFlag;
    MCS_PROTOCOL_DomainParameters m_targetParameters;
    MCS_PROTOCOL_DomainParameters m_minimumParameters;
    MCS_PROTOCOL_DomainParameters m_maximumParameters;
    PASN_OctetString m_userData;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// Connect-Additional
//

class MCS_PROTOCOL_Connect_Additional : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_Connect_Additional, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_Connect_Additional(unsigned tag = 103, TagClass tagClass = ApplicationTagClass);

    PASN_Integer m_calledConnectId;
    MCS_PROTOCOL_DataPriority m_dataPriority;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// PDin
//

class MCS_PROTOCOL_PDin : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_PDin, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_PDin(unsigned tag = 0, TagClass tagClass = ApplicationTagClass);

    PASN_Integer m_heightLimit;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// EDrq
//

class MCS_PROTOCOL_EDrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_EDrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_EDrq(unsigned tag = 1, TagClass tagClass = ApplicationTagClass);

    PASN_Integer m_subHeight;
    PASN_Integer m_subInterval;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// ChannelAttributes
//

class MCS_PROTOCOL_ChannelAttributes_static;
class MCS_PROTOCOL_ChannelAttributes_userId;
class MCS_PROTOCOL_ChannelAttributes_private;
class MCS_PROTOCOL_ChannelAttributes_assigned;

class MCS_PROTOCOL_ChannelAttributes : public PASN_Choice
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_ChannelAttributes, PASN_Choice);
#endif
  public:
    MCS_PROTOCOL_ChannelAttributes(unsigned tag = 0, TagClass tagClass = UniversalTagClass);

    enum Choices {
      e_static,
      e_userId,
      e_private,
      e_assigned
    };

#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_ChannelAttributes_static &() const;
#else
    operator MCS_PROTOCOL_ChannelAttributes_static &();
    operator const MCS_PROTOCOL_ChannelAttributes_static &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_ChannelAttributes_userId &() const;
#else
    operator MCS_PROTOCOL_ChannelAttributes_userId &();
    operator const MCS_PROTOCOL_ChannelAttributes_userId &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_ChannelAttributes_private &() const;
#else
    operator MCS_PROTOCOL_ChannelAttributes_private &();
    operator const MCS_PROTOCOL_ChannelAttributes_private &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_ChannelAttributes_assigned &() const;
#else
    operator MCS_PROTOCOL_ChannelAttributes_assigned &();
    operator const MCS_PROTOCOL_ChannelAttributes_assigned &() const;
#endif

    BOOL CreateObject();
    PObject * Clone() const;
};


//
// TokenAttributes
//

class MCS_PROTOCOL_TokenAttributes_grabbed;
class MCS_PROTOCOL_TokenAttributes_inhibited;
class MCS_PROTOCOL_TokenAttributes_giving;
class MCS_PROTOCOL_TokenAttributes_ungivable;
class MCS_PROTOCOL_TokenAttributes_given;

class MCS_PROTOCOL_TokenAttributes : public PASN_Choice
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TokenAttributes, PASN_Choice);
#endif
  public:
    MCS_PROTOCOL_TokenAttributes(unsigned tag = 0, TagClass tagClass = UniversalTagClass);

    enum Choices {
      e_grabbed,
      e_inhibited,
      e_giving,
      e_ungivable,
      e_given
    };

#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TokenAttributes_grabbed &() const;
#else
    operator MCS_PROTOCOL_TokenAttributes_grabbed &();
    operator const MCS_PROTOCOL_TokenAttributes_grabbed &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TokenAttributes_inhibited &() const;
#else
    operator MCS_PROTOCOL_TokenAttributes_inhibited &();
    operator const MCS_PROTOCOL_TokenAttributes_inhibited &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TokenAttributes_giving &() const;
#else
    operator MCS_PROTOCOL_TokenAttributes_giving &();
    operator const MCS_PROTOCOL_TokenAttributes_giving &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TokenAttributes_ungivable &() const;
#else
    operator MCS_PROTOCOL_TokenAttributes_ungivable &();
    operator const MCS_PROTOCOL_TokenAttributes_ungivable &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TokenAttributes_given &() const;
#else
    operator MCS_PROTOCOL_TokenAttributes_given &();
    operator const MCS_PROTOCOL_TokenAttributes_given &() const;
#endif

    BOOL CreateObject();
    PObject * Clone() const;
};


//
// AUrq
//

class MCS_PROTOCOL_AUrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_AUrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_AUrq(unsigned tag = 10, TagClass tagClass = ApplicationTagClass);


    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    PObject * Clone() const;
};


//
// CJrq
//

class MCS_PROTOCOL_CJrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_CJrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_CJrq(unsigned tag = 14, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_ChannelId m_channelId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// CCrq
//

class MCS_PROTOCOL_CCrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_CCrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_CCrq(unsigned tag = 17, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// CDrq
//

class MCS_PROTOCOL_CDrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_CDrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_CDrq(unsigned tag = 19, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_PrivateChannelId m_channelId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// CDin
//

class MCS_PROTOCOL_CDin : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_CDin, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_CDin(unsigned tag = 20, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_PrivateChannelId m_channelId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// SDrq
//

class MCS_PROTOCOL_SDrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_SDrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_SDrq(unsigned tag = 25, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_ChannelId m_channelId;
    MCS_PROTOCOL_DataPriority m_dataPriority;
    MCS_PROTOCOL_Segmentation m_segmentation;
    PASN_OctetString m_userData;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// SDin
//

class MCS_PROTOCOL_SDin : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_SDin, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_SDin(unsigned tag = 26, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_ChannelId m_channelId;
    MCS_PROTOCOL_DataPriority m_dataPriority;
    MCS_PROTOCOL_Segmentation m_segmentation;
    PASN_OctetString m_userData;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// USrq
//

class MCS_PROTOCOL_USrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_USrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_USrq(unsigned tag = 27, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_ChannelId m_channelId;
    MCS_PROTOCOL_DataPriority m_dataPriority;
    MCS_PROTOCOL_Segmentation m_segmentation;
    PASN_OctetString m_userData;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// USin
//

class MCS_PROTOCOL_USin : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_USin, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_USin(unsigned tag = 28, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_ChannelId m_channelId;
    MCS_PROTOCOL_DataPriority m_dataPriority;
    MCS_PROTOCOL_Segmentation m_segmentation;
    PASN_OctetString m_userData;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TGrq
//

class MCS_PROTOCOL_TGrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TGrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TGrq(unsigned tag = 29, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_TokenId m_tokenId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TIrq
//

class MCS_PROTOCOL_TIrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TIrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TIrq(unsigned tag = 31, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_TokenId m_tokenId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TVrq
//

class MCS_PROTOCOL_TVrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TVrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TVrq(unsigned tag = 33, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_TokenId m_tokenId;
    MCS_PROTOCOL_UserId m_recipient;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TVin
//

class MCS_PROTOCOL_TVin : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TVin, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TVin(unsigned tag = 34, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_TokenId m_tokenId;
    MCS_PROTOCOL_UserId m_recipient;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TPrq
//

class MCS_PROTOCOL_TPrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TPrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TPrq(unsigned tag = 37, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_TokenId m_tokenId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TPin
//

class MCS_PROTOCOL_TPin : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TPin, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TPin(unsigned tag = 38, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_TokenId m_tokenId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TRrq
//

class MCS_PROTOCOL_TRrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TRrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TRrq(unsigned tag = 39, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_TokenId m_tokenId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TTrq
//

class MCS_PROTOCOL_TTrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TTrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TTrq(unsigned tag = 41, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_TokenId m_tokenId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TTcf
//

class MCS_PROTOCOL_TTcf : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TTcf, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TTcf(unsigned tag = 42, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_TokenId m_tokenId;
    MCS_PROTOCOL_TokenStatus m_tokenStatus;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// Reason
//

class MCS_PROTOCOL_Reason : public PASN_Enumeration
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_Reason, PASN_Enumeration);
#endif
  public:
    MCS_PROTOCOL_Reason(unsigned tag = UniversalEnumeration, TagClass tagClass = UniversalTagClass);

    enum Enumerations {
      e_rn_domain_disconnected,
      e_rn_provider_initiated,
      e_rn_token_purged,
      e_rn_user_requested,
      e_rn_channel_purged
    };

    MCS_PROTOCOL_Reason & operator=(unsigned v);
    PObject * Clone() const;
};


//
// Result
//

class MCS_PROTOCOL_Result : public PASN_Enumeration
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_Result, PASN_Enumeration);
#endif
  public:
    MCS_PROTOCOL_Result(unsigned tag = UniversalEnumeration, TagClass tagClass = UniversalTagClass);

    enum Enumerations {
      e_rt_successful,
      e_rt_domain_merging,
      e_rt_domain_not_hierarchical,
      e_rt_no_such_channel,
      e_rt_no_such_domain,
      e_rt_no_such_user,
      e_rt_not_admitted,
      e_rt_other_user_id,
      e_rt_parameters_unacceptable,
      e_rt_token_not_available,
      e_rt_token_not_possessed,
      e_rt_too_many_channels,
      e_rt_too_many_tokens,
      e_rt_too_many_users,
      e_rt_unspecified_failure,
      e_rt_user_rejected
    };

    MCS_PROTOCOL_Result & operator=(unsigned v);
    PObject * Clone() const;
};


//
// Diagnostic
//

class MCS_PROTOCOL_Diagnostic : public PASN_Enumeration
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_Diagnostic, PASN_Enumeration);
#endif
  public:
    MCS_PROTOCOL_Diagnostic(unsigned tag = UniversalEnumeration, TagClass tagClass = UniversalTagClass);

    enum Enumerations {
      e_dc_inconsistent_merge,
      e_dc_forbidden_PDU_downward,
      e_dc_forbidden_PDU_upward,
      e_dc_invalid_BER_encoding,
      e_dc_invalid_PER_encoding,
      e_dc_misrouted_user,
      e_dc_unrequested_confirm,
      e_dc_wrong_transport_priority,
      e_dc_channel_id_conflict,
      e_dc_token_id_conflict,
      e_dc_not_user_id_channel,
      e_dc_too_many_channels,
      e_dc_too_many_tokens,
      e_dc_too_many_users
    };

    MCS_PROTOCOL_Diagnostic & operator=(unsigned v);
    PObject * Clone() const;
};


//
// ConnectMCSPDU
//

class MCS_PROTOCOL_Connect_Initial;
class MCS_PROTOCOL_Connect_Response;
class MCS_PROTOCOL_Connect_Additional;
class MCS_PROTOCOL_Connect_Result;

class MCS_PROTOCOL_ConnectMCSPDU : public PASN_Choice
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_ConnectMCSPDU, PASN_Choice);
#endif
  public:
    MCS_PROTOCOL_ConnectMCSPDU(unsigned tag = 0, TagClass tagClass = UniversalTagClass);

    enum Choices {
      e_connect_initial = 101,
      e_connect_response,
      e_connect_additional,
      e_connect_result
    };

#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_Connect_Initial &() const;
#else
    operator MCS_PROTOCOL_Connect_Initial &();
    operator const MCS_PROTOCOL_Connect_Initial &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_Connect_Response &() const;
#else
    operator MCS_PROTOCOL_Connect_Response &();
    operator const MCS_PROTOCOL_Connect_Response &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_Connect_Additional &() const;
#else
    operator MCS_PROTOCOL_Connect_Additional &();
    operator const MCS_PROTOCOL_Connect_Additional &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_Connect_Result &() const;
#else
    operator MCS_PROTOCOL_Connect_Result &();
    operator const MCS_PROTOCOL_Connect_Result &() const;
#endif

    BOOL CreateObject();
    PObject * Clone() const;
};


//
// DomainMCSPDU
//

class MCS_PROTOCOL_PDin;
class MCS_PROTOCOL_EDrq;
class MCS_PROTOCOL_MCrq;
class MCS_PROTOCOL_MCcf;
class MCS_PROTOCOL_PCin;
class MCS_PROTOCOL_MTrq;
class MCS_PROTOCOL_MTcf;
class MCS_PROTOCOL_PTin;
class MCS_PROTOCOL_DPum;
class MCS_PROTOCOL_RJum;
class MCS_PROTOCOL_AUrq;
class MCS_PROTOCOL_AUcf;
class MCS_PROTOCOL_DUrq;
class MCS_PROTOCOL_DUin;
class MCS_PROTOCOL_CJrq;
class MCS_PROTOCOL_CJcf;
class MCS_PROTOCOL_CLrq;
class MCS_PROTOCOL_CCrq;
class MCS_PROTOCOL_CCcf;
class MCS_PROTOCOL_CDrq;
class MCS_PROTOCOL_CDin;
class MCS_PROTOCOL_CArq;
class MCS_PROTOCOL_CAin;
class MCS_PROTOCOL_CErq;
class MCS_PROTOCOL_CEin;
class MCS_PROTOCOL_SDrq;
class MCS_PROTOCOL_SDin;
class MCS_PROTOCOL_USrq;
class MCS_PROTOCOL_USin;
class MCS_PROTOCOL_TGrq;
class MCS_PROTOCOL_TGcf;
class MCS_PROTOCOL_TIrq;
class MCS_PROTOCOL_TIcf;
class MCS_PROTOCOL_TVrq;
class MCS_PROTOCOL_TVin;
class MCS_PROTOCOL_TVrs;
class MCS_PROTOCOL_TVcf;
class MCS_PROTOCOL_TPrq;
class MCS_PROTOCOL_TPin;
class MCS_PROTOCOL_TRrq;
class MCS_PROTOCOL_TRcf;
class MCS_PROTOCOL_TTrq;
class MCS_PROTOCOL_TTcf;

class MCS_PROTOCOL_DomainMCSPDU : public PASN_Choice
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_DomainMCSPDU, PASN_Choice);
#endif
  public:
    MCS_PROTOCOL_DomainMCSPDU(unsigned tag = 0, TagClass tagClass = UniversalTagClass);

    enum Choices {
      e_pdin,
      e_edrq,
      e_mcrq,
      e_mccf,
      e_pcin,
      e_mtrq,
      e_mtcf,
      e_ptin,
      e_dpum,
      e_rjum,
      e_aurq,
      e_aucf,
      e_durq,
      e_duin,
      e_cjrq,
      e_cjcf,
      e_clrq,
      e_ccrq,
      e_cccf,
      e_cdrq,
      e_cdin,
      e_carq,
      e_cain,
      e_cerq,
      e_cein,
      e_sdrq,
      e_sdin,
      e_usrq,
      e_usin,
      e_tgrq,
      e_tgcf,
      e_tirq,
      e_ticf,
      e_tvrq,
      e_tvin,
      e_tvrs,
      e_tvcf,
      e_tprq,
      e_tpin,
      e_trrq,
      e_trcf,
      e_ttrq,
      e_ttcf
    };

#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_PDin &() const;
#else
    operator MCS_PROTOCOL_PDin &();
    operator const MCS_PROTOCOL_PDin &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_EDrq &() const;
#else
    operator MCS_PROTOCOL_EDrq &();
    operator const MCS_PROTOCOL_EDrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_MCrq &() const;
#else
    operator MCS_PROTOCOL_MCrq &();
    operator const MCS_PROTOCOL_MCrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_MCcf &() const;
#else
    operator MCS_PROTOCOL_MCcf &();
    operator const MCS_PROTOCOL_MCcf &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_PCin &() const;
#else
    operator MCS_PROTOCOL_PCin &();
    operator const MCS_PROTOCOL_PCin &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_MTrq &() const;
#else
    operator MCS_PROTOCOL_MTrq &();
    operator const MCS_PROTOCOL_MTrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_MTcf &() const;
#else
    operator MCS_PROTOCOL_MTcf &();
    operator const MCS_PROTOCOL_MTcf &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_PTin &() const;
#else
    operator MCS_PROTOCOL_PTin &();
    operator const MCS_PROTOCOL_PTin &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_DPum &() const;
#else
    operator MCS_PROTOCOL_DPum &();
    operator const MCS_PROTOCOL_DPum &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_RJum &() const;
#else
    operator MCS_PROTOCOL_RJum &();
    operator const MCS_PROTOCOL_RJum &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_AUrq &() const;
#else
    operator MCS_PROTOCOL_AUrq &();
    operator const MCS_PROTOCOL_AUrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_AUcf &() const;
#else
    operator MCS_PROTOCOL_AUcf &();
    operator const MCS_PROTOCOL_AUcf &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_DUrq &() const;
#else
    operator MCS_PROTOCOL_DUrq &();
    operator const MCS_PROTOCOL_DUrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_DUin &() const;
#else
    operator MCS_PROTOCOL_DUin &();
    operator const MCS_PROTOCOL_DUin &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_CJrq &() const;
#else
    operator MCS_PROTOCOL_CJrq &();
    operator const MCS_PROTOCOL_CJrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_CJcf &() const;
#else
    operator MCS_PROTOCOL_CJcf &();
    operator const MCS_PROTOCOL_CJcf &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_CLrq &() const;
#else
    operator MCS_PROTOCOL_CLrq &();
    operator const MCS_PROTOCOL_CLrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_CCrq &() const;
#else
    operator MCS_PROTOCOL_CCrq &();
    operator const MCS_PROTOCOL_CCrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_CCcf &() const;
#else
    operator MCS_PROTOCOL_CCcf &();
    operator const MCS_PROTOCOL_CCcf &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_CDrq &() const;
#else
    operator MCS_PROTOCOL_CDrq &();
    operator const MCS_PROTOCOL_CDrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_CDin &() const;
#else
    operator MCS_PROTOCOL_CDin &();
    operator const MCS_PROTOCOL_CDin &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_CArq &() const;
#else
    operator MCS_PROTOCOL_CArq &();
    operator const MCS_PROTOCOL_CArq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_CAin &() const;
#else
    operator MCS_PROTOCOL_CAin &();
    operator const MCS_PROTOCOL_CAin &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_CErq &() const;
#else
    operator MCS_PROTOCOL_CErq &();
    operator const MCS_PROTOCOL_CErq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_CEin &() const;
#else
    operator MCS_PROTOCOL_CEin &();
    operator const MCS_PROTOCOL_CEin &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_SDrq &() const;
#else
    operator MCS_PROTOCOL_SDrq &();
    operator const MCS_PROTOCOL_SDrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_SDin &() const;
#else
    operator MCS_PROTOCOL_SDin &();
    operator const MCS_PROTOCOL_SDin &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_USrq &() const;
#else
    operator MCS_PROTOCOL_USrq &();
    operator const MCS_PROTOCOL_USrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_USin &() const;
#else
    operator MCS_PROTOCOL_USin &();
    operator const MCS_PROTOCOL_USin &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TGrq &() const;
#else
    operator MCS_PROTOCOL_TGrq &();
    operator const MCS_PROTOCOL_TGrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TGcf &() const;
#else
    operator MCS_PROTOCOL_TGcf &();
    operator const MCS_PROTOCOL_TGcf &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TIrq &() const;
#else
    operator MCS_PROTOCOL_TIrq &();
    operator const MCS_PROTOCOL_TIrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TIcf &() const;
#else
    operator MCS_PROTOCOL_TIcf &();
    operator const MCS_PROTOCOL_TIcf &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TVrq &() const;
#else
    operator MCS_PROTOCOL_TVrq &();
    operator const MCS_PROTOCOL_TVrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TVin &() const;
#else
    operator MCS_PROTOCOL_TVin &();
    operator const MCS_PROTOCOL_TVin &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TVrs &() const;
#else
    operator MCS_PROTOCOL_TVrs &();
    operator const MCS_PROTOCOL_TVrs &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TVcf &() const;
#else
    operator MCS_PROTOCOL_TVcf &();
    operator const MCS_PROTOCOL_TVcf &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TPrq &() const;
#else
    operator MCS_PROTOCOL_TPrq &();
    operator const MCS_PROTOCOL_TPrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TPin &() const;
#else
    operator MCS_PROTOCOL_TPin &();
    operator const MCS_PROTOCOL_TPin &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TRrq &() const;
#else
    operator MCS_PROTOCOL_TRrq &();
    operator const MCS_PROTOCOL_TRrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TRcf &() const;
#else
    operator MCS_PROTOCOL_TRcf &();
    operator const MCS_PROTOCOL_TRcf &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TTrq &() const;
#else
    operator MCS_PROTOCOL_TTrq &();
    operator const MCS_PROTOCOL_TTrq &() const;
#endif
#if defined(__GNUC__) && __GNUC__ <= 2 && __GNUC_MINOR__ < 9
    operator MCS_PROTOCOL_TTcf &() const;
#else
    operator MCS_PROTOCOL_TTcf &();
    operator const MCS_PROTOCOL_TTcf &() const;
#endif

    BOOL CreateObject();
    PObject * Clone() const;
};


//
// ChannelAttributes_static
//

class MCS_PROTOCOL_ChannelAttributes_static : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_ChannelAttributes_static, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_ChannelAttributes_static(unsigned tag = 0, TagClass tagClass = ContextSpecificTagClass);

    MCS_PROTOCOL_StaticChannelId m_channelId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// ChannelAttributes_userId
//

class MCS_PROTOCOL_ChannelAttributes_userId : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_ChannelAttributes_userId, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_ChannelAttributes_userId(unsigned tag = 1, TagClass tagClass = ContextSpecificTagClass);

    PASN_Boolean m_joined;
    MCS_PROTOCOL_UserId m_userId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// ChannelAttributes_assigned
//

class MCS_PROTOCOL_ChannelAttributes_assigned : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_ChannelAttributes_assigned, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_ChannelAttributes_assigned(unsigned tag = 3, TagClass tagClass = ContextSpecificTagClass);

    MCS_PROTOCOL_AssignedChannelId m_channelId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// ArrayOf_ChannelAttributes
//

class MCS_PROTOCOL_ChannelAttributes;

class MCS_PROTOCOL_ArrayOf_ChannelAttributes : public PASN_Array
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_ArrayOf_ChannelAttributes, PASN_Array);
#endif
  public:
    MCS_PROTOCOL_ArrayOf_ChannelAttributes(unsigned tag = UniversalSet, TagClass tagClass = UniversalTagClass);

    PASN_Object * CreateObject() const;
    MCS_PROTOCOL_ChannelAttributes & operator[](PINDEX i) const;
    PObject * Clone() const;
};


//
// ArrayOf_ChannelId
//

class MCS_PROTOCOL_ChannelId;

class MCS_PROTOCOL_ArrayOf_ChannelId : public PASN_Array
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_ArrayOf_ChannelId, PASN_Array);
#endif
  public:
    MCS_PROTOCOL_ArrayOf_ChannelId(unsigned tag = UniversalSet, TagClass tagClass = UniversalTagClass);

    PASN_Object * CreateObject() const;
    MCS_PROTOCOL_ChannelId & operator[](PINDEX i) const;
    PObject * Clone() const;
};


//
// ArrayOf_UserId
//

class MCS_PROTOCOL_UserId;

class MCS_PROTOCOL_ArrayOf_UserId : public PASN_Array
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_ArrayOf_UserId, PASN_Array);
#endif
  public:
    MCS_PROTOCOL_ArrayOf_UserId(unsigned tag = UniversalSet, TagClass tagClass = UniversalTagClass);

    PASN_Object * CreateObject() const;
    MCS_PROTOCOL_UserId & operator[](PINDEX i) const;
    PObject * Clone() const;
};


//
// TokenAttributes_grabbed
//

class MCS_PROTOCOL_TokenAttributes_grabbed : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TokenAttributes_grabbed, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TokenAttributes_grabbed(unsigned tag = 0, TagClass tagClass = ContextSpecificTagClass);

    MCS_PROTOCOL_TokenId m_tokenId;
    MCS_PROTOCOL_UserId m_grabber;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TokenAttributes_inhibited
//

class MCS_PROTOCOL_TokenAttributes_inhibited : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TokenAttributes_inhibited, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TokenAttributes_inhibited(unsigned tag = 1, TagClass tagClass = ContextSpecificTagClass);

    MCS_PROTOCOL_TokenId m_tokenId;
    MCS_PROTOCOL_ArrayOf_UserId m_inhibitors;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TokenAttributes_giving
//

class MCS_PROTOCOL_TokenAttributes_giving : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TokenAttributes_giving, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TokenAttributes_giving(unsigned tag = 2, TagClass tagClass = ContextSpecificTagClass);

    MCS_PROTOCOL_TokenId m_tokenId;
    MCS_PROTOCOL_UserId m_grabber;
    MCS_PROTOCOL_UserId m_recipient;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TokenAttributes_ungivable
//

class MCS_PROTOCOL_TokenAttributes_ungivable : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TokenAttributes_ungivable, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TokenAttributes_ungivable(unsigned tag = 3, TagClass tagClass = ContextSpecificTagClass);

    MCS_PROTOCOL_TokenId m_tokenId;
    MCS_PROTOCOL_UserId m_grabber;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TokenAttributes_given
//

class MCS_PROTOCOL_TokenAttributes_given : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TokenAttributes_given, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TokenAttributes_given(unsigned tag = 4, TagClass tagClass = ContextSpecificTagClass);

    MCS_PROTOCOL_TokenId m_tokenId;
    MCS_PROTOCOL_UserId m_recipient;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// ArrayOf_TokenAttributes
//

class MCS_PROTOCOL_TokenAttributes;

class MCS_PROTOCOL_ArrayOf_TokenAttributes : public PASN_Array
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_ArrayOf_TokenAttributes, PASN_Array);
#endif
  public:
    MCS_PROTOCOL_ArrayOf_TokenAttributes(unsigned tag = UniversalSet, TagClass tagClass = UniversalTagClass);

    PASN_Object * CreateObject() const;
    MCS_PROTOCOL_TokenAttributes & operator[](PINDEX i) const;
    PObject * Clone() const;
};


//
// ArrayOf_TokenId
//

class MCS_PROTOCOL_TokenId;

class MCS_PROTOCOL_ArrayOf_TokenId : public PASN_Array
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_ArrayOf_TokenId, PASN_Array);
#endif
  public:
    MCS_PROTOCOL_ArrayOf_TokenId(unsigned tag = UniversalSet, TagClass tagClass = UniversalTagClass);

    PASN_Object * CreateObject() const;
    MCS_PROTOCOL_TokenId & operator[](PINDEX i) const;
    PObject * Clone() const;
};


//
// Connect-Response
//

class MCS_PROTOCOL_Connect_Response : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_Connect_Response, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_Connect_Response(unsigned tag = 102, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_Result m_result;
    PASN_Integer m_calledConnectId;
    MCS_PROTOCOL_DomainParameters m_domainParameters;
    PASN_OctetString m_userData;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// Connect-Result
//

class MCS_PROTOCOL_Connect_Result : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_Connect_Result, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_Connect_Result(unsigned tag = 104, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_Result m_result;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// MCrq
//

class MCS_PROTOCOL_MCrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_MCrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_MCrq(unsigned tag = 2, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_ArrayOf_ChannelAttributes m_mergeChannels;
    MCS_PROTOCOL_ArrayOf_ChannelId m_purgeChannelIds;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// MCcf
//

class MCS_PROTOCOL_MCcf : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_MCcf, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_MCcf(unsigned tag = 3, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_ArrayOf_ChannelAttributes m_mergeChannels;
    MCS_PROTOCOL_ArrayOf_ChannelId m_purgeChannelIds;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// PCin
//

class MCS_PROTOCOL_PCin : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_PCin, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_PCin(unsigned tag = 4, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_ArrayOf_UserId m_detachUserIds;
    MCS_PROTOCOL_ArrayOf_ChannelId m_purgeChannelIds;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// MTrq
//

class MCS_PROTOCOL_MTrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_MTrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_MTrq(unsigned tag = 5, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_ArrayOf_TokenAttributes m_mergeTokens;
    MCS_PROTOCOL_ArrayOf_TokenId m_purgeTokenIds;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// MTcf
//

class MCS_PROTOCOL_MTcf : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_MTcf, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_MTcf(unsigned tag = 6, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_ArrayOf_TokenAttributes m_mergeTokens;
    MCS_PROTOCOL_ArrayOf_TokenId m_purgeTokenIds;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// PTin
//

class MCS_PROTOCOL_PTin : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_PTin, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_PTin(unsigned tag = 7, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_ArrayOf_TokenId m_purgeTokenIds;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// DPum
//

class MCS_PROTOCOL_DPum : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_DPum, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_DPum(unsigned tag = 8, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_Reason m_reason;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// RJum
//

class MCS_PROTOCOL_RJum : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_RJum, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_RJum(unsigned tag = 9, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_Diagnostic m_diagnostic;
    PASN_OctetString m_initialOctets;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// AUcf
//

class MCS_PROTOCOL_AUcf : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_AUcf, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_AUcf(unsigned tag = 11, TagClass tagClass = ApplicationTagClass);

    enum OptionalFields {
      e_initiator
    };

    MCS_PROTOCOL_Result m_result;
    MCS_PROTOCOL_UserId m_initiator;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// DUrq
//

class MCS_PROTOCOL_DUrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_DUrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_DUrq(unsigned tag = 12, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_Reason m_reason;
    MCS_PROTOCOL_ArrayOf_UserId m_userIds;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// DUin
//

class MCS_PROTOCOL_DUin : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_DUin, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_DUin(unsigned tag = 13, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_Reason m_reason;
    MCS_PROTOCOL_ArrayOf_UserId m_userIds;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// CJcf
//

class MCS_PROTOCOL_CJcf : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_CJcf, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_CJcf(unsigned tag = 15, TagClass tagClass = ApplicationTagClass);

    enum OptionalFields {
      e_channelId
    };

    MCS_PROTOCOL_Result m_result;
    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_ChannelId m_requested;
    MCS_PROTOCOL_ChannelId m_channelId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// CLrq
//

class MCS_PROTOCOL_CLrq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_CLrq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_CLrq(unsigned tag = 16, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_ArrayOf_ChannelId m_channelIds;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// CCcf
//

class MCS_PROTOCOL_CCcf : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_CCcf, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_CCcf(unsigned tag = 18, TagClass tagClass = ApplicationTagClass);

    enum OptionalFields {
      e_channelId
    };

    MCS_PROTOCOL_Result m_result;
    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_PrivateChannelId m_channelId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// CArq
//

class MCS_PROTOCOL_CArq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_CArq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_CArq(unsigned tag = 21, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_PrivateChannelId m_channelId;
    MCS_PROTOCOL_ArrayOf_UserId m_userIds;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// CAin
//

class MCS_PROTOCOL_CAin : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_CAin, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_CAin(unsigned tag = 22, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_PrivateChannelId m_channelId;
    MCS_PROTOCOL_ArrayOf_UserId m_userIds;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// CErq
//

class MCS_PROTOCOL_CErq : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_CErq, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_CErq(unsigned tag = 23, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_PrivateChannelId m_channelId;
    MCS_PROTOCOL_ArrayOf_UserId m_userIds;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// CEin
//

class MCS_PROTOCOL_CEin : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_CEin, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_CEin(unsigned tag = 24, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_PrivateChannelId m_channelId;
    MCS_PROTOCOL_ArrayOf_UserId m_userIds;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TGcf
//

class MCS_PROTOCOL_TGcf : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TGcf, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TGcf(unsigned tag = 30, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_Result m_result;
    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_TokenId m_tokenId;
    MCS_PROTOCOL_TokenStatus m_tokenStatus;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TIcf
//

class MCS_PROTOCOL_TIcf : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TIcf, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TIcf(unsigned tag = 32, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_Result m_result;
    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_TokenId m_tokenId;
    MCS_PROTOCOL_TokenStatus m_tokenStatus;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TVrs
//

class MCS_PROTOCOL_TVrs : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TVrs, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TVrs(unsigned tag = 35, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_Result m_result;
    MCS_PROTOCOL_UserId m_recipient;
    MCS_PROTOCOL_TokenId m_tokenId;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TVcf
//

class MCS_PROTOCOL_TVcf : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TVcf, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TVcf(unsigned tag = 36, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_Result m_result;
    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_TokenId m_tokenId;
    MCS_PROTOCOL_TokenStatus m_tokenStatus;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// TRcf
//

class MCS_PROTOCOL_TRcf : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_TRcf, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_TRcf(unsigned tag = 40, TagClass tagClass = ApplicationTagClass);

    MCS_PROTOCOL_Result m_result;
    MCS_PROTOCOL_UserId m_initiator;
    MCS_PROTOCOL_TokenId m_tokenId;
    MCS_PROTOCOL_TokenStatus m_tokenStatus;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


//
// ChannelAttributes_private
//

class MCS_PROTOCOL_ChannelAttributes_private : public PASN_Sequence
{
#ifndef PASN_LEANANDMEAN
    PCLASSINFO(MCS_PROTOCOL_ChannelAttributes_private, PASN_Sequence);
#endif
  public:
    MCS_PROTOCOL_ChannelAttributes_private(unsigned tag = 2, TagClass tagClass = ContextSpecificTagClass);

    PASN_Boolean m_joined;
    MCS_PROTOCOL_PrivateChannelId m_channelId;
    MCS_PROTOCOL_UserId m_manager;
    MCS_PROTOCOL_ArrayOf_UserId m_admitted;

    PINDEX GetDataLength() const;
    BOOL Decode(PASN_Stream & strm);
    void Encode(PASN_Stream & strm) const;
#ifndef PASN_NOPRINTON
    void PrintOn(ostream & strm) const;
#endif
    Comparison Compare(const PObject & obj) const;
    PObject * Clone() const;
};


#endif // __MCS_PROTOCOL_H

#endif // if ! H323_DISABLE_MCS_PROTOCOL


// End of mcspduv2.h
