
MAKE := make --no-print-directory

all :
	@$(MAKE) -f makefile_linux_d clean;
	@$(MAKE) -f makefile_linux_d;
	@$(MAKE) -f makefile_linux_d clean;
	@$(MAKE) -f makefile_linux_r clean;
	@$(MAKE) -f makefile_linux_r;
	@$(MAKE) -f makefile_linux_r clean;
	
