

//终端控制台菜单定义
#define MENU_REQ_CHAIRMAN		0	//申请主席
#define MENU_SPEC_CHAIRMAN		1	//指定主席
#define MENU_CANCEL_CHAIRMAN	2	//取消主席
// ---------------				3	//
#define MENU_REQ_SPEAKER		4	//申请发言
#define MENU_SPEC_SPEAKER		5	//指定发言
#define MENU_CANCEL_SPEAKER		6	//取消发言
// ---------------              7
#define MENU_INSPEC_MT			8	//选看终端
#define MENU_INVITE_MT			9	//邀请终端
#define MENU_DELETE_MT			10	//请退终端
// ----------------				11
#define	MENU_POLL_START			12	//开始轮询
#define MENU_POLL_STOP			13	//停止轮询
#define MENU_POLL_PAUSE			14	//暂停轮询
#define MENU_POLL_RESUM			15	//恢复轮询
// ----------------				16
#define MENU_START_DISCUSS		17	//开始讨论
#define MENU_STOP_DISCUSS		18	//停止讨论
// ----------------				19
#define MENU_VMP				20	//视频复合


//桌面终端菜单项定义
//Menu 1 当前终端为主席时点击自己时的弹出菜单
#define MENU_CHRMN_REQSPEAK		0	//申请发言
#define MENU_CHRMN_QUITCONF		1	//退出会议
#define MENU_CHRMN_BRCADMSG		2	//广播消息
//								3	// ----------
#define MENU_CHRMN_CANSPEAK		4	//取消发言
#define	MENU_CHRMN_CANCHRMN		5	//取消主席
#define	MENU_CHRMN_POLLSEE		6	//轮流查询
#define	MENU_CHRMN_CONFDELAY	7	//延长会议
#define	MENU_CHRMN_DISCUSS		8	//讨论模式
#define	MENU_CHRMN_INSPIRIT		9	//语音激励
#define	MENU_CHRMN_VMPSTART		10	//画面合成
#define	MENU_CHRMN_ENDCONF		11	//结束会议

// Menu 2 当前终端不是主席时点击自己时的弹出菜单
#define MENU_NORM_REQSPEAK	0	//申请发言
#define MENU_NORM_REQCHRMN	1	//申请主席
#define MENU_NORM_QUITCONF	2	//退出会议
#define MENU_NORM_BRCADMSG	3	//广播消息

//Menu 3 当前终端是主席时点击其他终端时的弹出菜单
#define MENU_CHAIR_VIEWMT		0	//选看终端
#define MENU_CHAIR_BROAD		1	//广播消息
//								2	//----------------
#define MENU_CHAIR_SPECSPK		3	//指定主席
#define MENU_CHAIR_SPECCHA		4	//指定发言
#define MENU_CHAIR_CANSPEAK		5	//取消发言
#define MENU_CHAIR_POLLSEE		6	//轮流查询
#define MENU_CHAIR_SILENCE		7	//远端静音
#define MENU_CHAIR_MICMUTE		8	//远端哑音
#define MENU_CHAIR_CONFDELAY	9	//延长会议
#define MENU_CHAIR_DISCUSS		10	//讨论模式
#define MENU_CHAIR_INSPIRIT		11	//语音激励
#define MENU_CHAIR_VMPSTART		12	//画面合成
#define MENU_CHAIR_DELETEMT		13	//请退终端

//Menu 4 点击会议监控视频源时
#define MENU_STOP_MONITOR		0	//停止监控
#define MENU_REALTIME_MONITOR	1	//实时监控

#define MTUI_HWND_CHECK(x) \
{\
	m_bHasError = false;\
	if( x == NULL)\
	{\
	int nLen = 0;\
	nLen = strlen(m_strNotFoundHWnd);\
	strcpy(m_strNotFoundHWnd+nLen, #x);\
	nLen = strlen(m_strNotFoundHWnd);\
	strcpy(m_strNotFoundHWnd+nLen, ", ");\
	m_bHasError = true;\
	}\
}

// Microsoft Developer Studio generated include file.
// Used by Mtc2.rc
//
#define IDS_MTC2                        1
#define IDD_ABOUTBOX_MTC2               1
#define IDB_MTC2                        1
#define IDI_ABOUTDLL                    1
#define IDS_MTC2_PPG                    2
#define IDC_SAVEAS                      3
#define IDC_BTN_SELECTFILE              3
#define IDC_BTN_VERSIONUPLOAD           3
#define IDC_CONFIG_BTN                  4
#define IDC_BTN_ADDROUTE                5
#define IDC_ADDMT_BTN                   5
#define IDC_BTN_DELROUTE                6
#define IDC_EDITMT_BTN                  6
#define IDC_BTN_REBOOT                  7
#define IDC_DELMT_BTN                   8
#define IDS_MTC2_PPG_CAPTION            200
#define IDD_PROPPAGE_MTC2               200
#define IDC_CONNECT_MT                  201
#define IDD_MAINFRAME_DLG               201
#define IDC_CREATE_CONF                 202
#define IDD_CONNECT_DLG                 202
#define IDC_APPLIY_JOIN_CONF            203
#define IDD_CREATECONF_DLG              203
#define IDC_START_DUVIDEO_FLOW          204
#define IDD_CONFIG_DLG                  204
#define IDC_CONFIG                      205
#define IDD_CFGLOCAL_DLG                205
#define IDC_SNAPSHOT                    206
#define IDD_CFGNET_DLG                  206
#define IDC_LOCAL_MONITOR               207
#define IDD_CFGCALL_DLG                 207
#define IDC_REMOTE_MONITOR              208
#define IDD_CFGVENCDEC_DLG              208
#define IDC_LOCAL_START_MONITE          209
#define IDD_CFGAENCDEC_DLG              209
#define IDC_LOCAL_STOP_MONITE           210
#define IDD_CFGSR_RESEND_DLG            210
#define IDC_CONF_MANAGE                 210
#define IDC_REMOTE_START_MONITE         211
#define IDD_SNAPSHOT_DLG                211
#define IDC_REMOTE_STOP_MONITE          212
#define IDC_DEVICE_CONTROL              212
#define IDC_OPER_INFO                   213
#define IDC_BTN_VERSIONUPDATE           213
#define IDC_MSGBOARD                    214
#define IDC_REVSM_MTCOMBO               215
#define IDB_MAN                         215
#define IDC_SHORTMSG                    216
#define IDD_IP_DLG                      216
#define IDC_SEND_SHORTMSG               217
#define IDD_ADDRBOOK_DLG                217
#define IDC_PLATFORM_LIST               218
#define IDD_CONFLIST_DLG                218
#define IDC_AUDIENCE_LIST               219
#define IDC_CONNECT_IP                  219
#define IDR_MENU_SIMCONF                219
#define IDC_CONNECT_PORT                220
#define IDC_ADDRBOOK                    220
#define IDD_MTPOLL_DLG                  220
#define IDC_CONNECT_USER                221
#define IDC_CONFMT_LIST                 221
#define IDC_USER_MANAGE                 221
#define IDD_DISCUSS_DLG                 221
#define IDC_CONNECT_PWD                 222
#define IDC_IPADDRESS1                  222
#define IDD_INSPECT_MT_DLG              222
#define IDC_P2P_CALL                    222
#define IDC_IPADDRESS_MT                222
#define IDC_IP_TRAP                     222
#define IDC_IP_MATRIX                   222
#define IDC_CONFNAME                    223
#define IDC_CFG_NETMASK                 223
#define IDD_ENTERPWD_DLG                223
#define IDC_IPADDRESS_MASK              223
#define IDC_MTNAME_EDIT                 223
#define IDC_IPADDRESS2                  224
#define IDC_CFG_GATEWAY                 224
#define IDD_MSG_DLG                     224
#define IDC_REMOTE_CTRL                 224
#define IDC_IPADDRESS_MCU               224
#define IDC_IPADDRESS_GATE              224
#define IDC_MTIP                        224
#define IDC_IP_ETHMASK                  224
#define IDC_IP_FIREPROXY_ADDR           224
#define IDC_ADDMT                       225
#define IDC_VMP                         225
#define IDC_SYSTEM_MANAGE               225
#define IDC_DELMT                       226
#define IDC_CFG_LOCAL                   226
#define IDD_FULLSCREEN_DLG              226
#define IDC_MATRIX                      226
#define IDC_CONF_DISCUSS                226
#define IDC_CFG_NET                     227
#define IDC_ADDR                        227
#define IDB_CONNECTMT_1                 227
#define IDC_VOICE_SPARK                 227
#define IDC_CFG_CALL                    228
#define IDC_ALIAS                       228
#define IDB_CONNECTMT_2                 228
#define IDC_VIDEO_COMPOUND              228
#define IDC_CFG_VENCDEC                 229
#define IDC_E164                        229
#define IDB_CONNECTMT_3                 229
#define IDC_CFG_AENCDEC                 230
#define IDC_LOCAL_TYPE                  230
#define IDB_CONNECTMT_4                 230
#define IDC_CFG_RESEND                  231
#define IDC_LOCAL_POSITION              231
#define IDC_CFG_MACADDR                 231
#define IDB_CREATECONF_1                231
#define IDC_CFG_BANDWIDTH               232
#define IDB_CREATECONF_2                232
#define IDC_SWITCH_DELAY                232
#define IDC_CFG_SNDSTART_PORT           233
#define IDB_CREATECONF_3                233
#define IDC_CFG_REVSTART_PORT           234
#define IDB_CREATECONF_4                234
#define IDC_NETCARD_NUM                 235
#define IDB_APPLYJOIN_1                 235
#define IDC_CFG_IPADDR                  236
#define IDB_APPLYJOIN_2                 236
#define IDC_CFG_ANSWER_MODE             237
#define IDB_APPLYJOIN_3                 237
#define IDC_CFG_BANDWIDTH2              237
#define IDC_CFG_CALL_MODE               238
#define IDB_APPLYJOIN_4                 238
#define IDC_AUTOCALL_INTERVAL           239
#define IDB_DUALVIDEO_1                 239
#define IDC_AUTOCALL_IP                 240
#define IDB_DUALVIDEO_2                 240
#define IDC_GK_IP                       241
#define IDC_VDEC_FORMAT                 241
#define IDB_DUALVIDEO_3                 241
#define IDC_CFG_EXPAND_MODE             242
#define IDC_VENC_SOURCE                 242
#define IDB_DUALVIDEO_4                 242
#define IDC_CFG_USEGK                   243
#define IDC_VENC_FORMAT                 243
#define IDB_CONFIG_1                    243
#define IDC_VENC_RESOLUTION             244
#define IDB_CONFIG_2                    244
#define IDC_AUTOCALL_BITRATE            244
#define IDC_VENC_SYSTEM                 245
#define IDB_CONFIG_3                    245
#define IDC_CFG_ENCRYPT                 245
#define IDC_VENC_FTRAMERATE_UNIT        246
#define IDB_CONFIG_4                    246
#define IDC_VENC_BITRATE                247
#define IDB_SNAPSHOT_1                  247
#define IDC_CMB_VENC_COMPRESS           247
#define IDC_VENC_FRAMERATE              248
#define IDB_SNAPSHOT_2                  248
#define IDC_VENC_MAXBANDWIDTH           249
#define IDB_SNAPSHOT_3                  249
#define IDC_VENC_COMPRESS               250
#define IDB_SNAPSHOT_4                  250
#define IDC_VDEC_MPEG4_PROCESS_VALUE    251
#define IDB_ADDRBOOK_1                  251
#define IDC_AUTO_DROP_FRAME             252
#define IDB_ADDRBOOK_2                  252
#define IDC_VENC_MAX_IFRAME_INTERVAL    253
#define IDC_ADEC_FORMAT                 253
#define IDB_ADDRBOOK_3                  253
#define IDC_VENC_MAX_QUAL_VALUE         254
#define IDC_AENC_SOURCE                 254
#define IDB_ADDRBOOK_4                  254
#define IDC_VENC_MIN_QUAL_VALUE         255
#define IDC_AENC_FORMAT                 255
#define IDB_USERMANAGE_1                255
#define IDC_AENC_BITRATE                256
#define IDB_USERMANAGE_2                256
#define IDC_AENC_SAMPLERATE             257
#define IDB_USERMANAGE_3                257
#define IDC_ADEC_VOLUMN                 258
#define IDB_USERMANAGE_4                258
#define IDC_AENC_VOLUMN                 259
#define IDC_SEND_RESEND                 259
#define IDB_REMOTECTRL_1                259
#define IDC_RECEIVE_RESEND              260
#define IDB_REMOTECTRL_2                260
#define IDC_SEND_TIMEOUT                261
#define IDB_REMOTECTRL_3                261
#define IDC_LOST_PACKAGE_TIMEOUT        262
#define IDC_PIC_LIST                    262
#define IDB_REMOTECTRL_4                262
#define IDC_CHECK_POINT_1               263
#define IDC_SAVE_POSTION                263
#define IDB_START                       263
#define IDC_CHECK_POINT_2               264
#define IDC_PREVIEW                     264
#define IDB_STOP                        264
#define IDC_CHECK_POINT_3               265
#define IDC_IPADDR                      265
#define IDB_SEND                        265
#define IDC_CONF_LIST                   266
#define IDB_CALL_1                      266
#define IDB_DISCONNECT_1                267
#define IDC_MTPOLL_INTERVAL             268
#define IDB_DISCONNECT_2                268
#define IDC_CANDI_MT_LIST               269
#define IDB_DISCONNECT_3                269
#define IDC_SELECTED_MT_LIST            270
#define IDB_DISCONNECT_4                270
#define IDC_ADD_MT                      271
#define IDB_STOPDUALVIDEO_1             271
#define IDC_ADDALL_MT                   272
#define IDC_DISCUSS_NUM                 272
#define IDB_STOPDUALVIDEO_2             272
#define IDC_DEL_MT                      273
#define IDC_MT_TO_INSPECT               273
#define IDB_STOPDUALVIDEO_3             273
#define IDC_DELALL_MT                   274
#define IDC_INSPECT_TYPE                274
#define IDB_STOPDUALVIDEO_4             274
#define IDC_CONFPWD                     275
#define IDB_QUITCONF_1                  275
#define IDC_MESSAGE                     276
#define IDB_QUITCONF_2                  276
#define IDC_P2P_ADDR                    277
#define IDB_QUITCONF_3                  277
#define IDC_LOCAL_IP                    278
#define IDB_QUITCONF_4                  278
#define IDC_CONFNAME_STATIC             279
#define IDB_RELEASECONF_1               279
#define IDC_MT_COMBO                    279
#define IDC_LOCAL_STATIC                280
#define IDB_RELEASECONF_2               280
#define IDC_REMOTE_STATIC               281
#define IDB_RELEASECONF_3               281
#define IDC_SHORTMSG_STATIC             282
#define IDB_RELEASECONF_4               282
#define IDC_MSGINFO_STATIC              283
#define IDB_CANCEL_1                    283
#define IDC_MTIP_STATIC                 284
#define IDB_CANCEL_2                    284
#define IDC_MTPORT_STATIC               285
#define IDB_CONFIRM_1                   285
#define IDC_MTUSER_STATIC               286
#define IDB_CONFIRM_2                   286
#define IDC_MTPWD_STATIC                287
#define IDB_DEL_1                       287
#define IDC_MTLOCALIP_STATIC            288
#define IDB_DEL_2                       288
#define IDC_ADECFORMAT_STATIC           289
#define IDB_DEL_3                       289
#define IDC_STATIC_CONNECTMT            289
#define IDC_ADECVOLUMN_STATIC           290
#define IDB_DEL_4                       290
#define IDC_MT_NAME                     290
#define IDC_ASOURCE_STATIC              291
#define IDB_ADD_1                       291
#define IDB_ADD_2                       292
#define IDC_AENCFORMAT_STATIC           293
#define IDB_ADD_3                       293
#define IDC_AENCBITRATE_STATIC          294
#define IDB_ADD_4                       294
#define IDC_AENCSAMPLERATE_STATIC       295
#define IDC_AENCVOLUMN_STATIC           296
#define IDB_CONNECT_2                   296
#define IDB_CONNECT_3                   297
#define IDC_ANSWERMODE_STATIC           298
#define IDB_ADDRMT_1                    298
#define IDC_CALLMODE_STATIC             299
#define IDB_ADDRMT_2                    299
#define IDC_CALLINTERVAL_STATIC         300
#define IDB_ADDRMT_3                    300
#define IDC_AUTOCALLIP_STATIC           301
#define IDB_ADDRMT_4                    301
#define IDC_EXPTENDMODE_STATIC          302
#define IDB_STARTPOLL_1                 302
#define IDC_USEGK_STATIC                303
#define IDB_STARTPOLL_2                 303
#define IDC_GKADDR_STATIC               304
#define IDB_DOUBLERIGHT_1               304
#define IDC_MTALIAS_STATIC              305
#define IDB_DOUBLERIGHT_2               305
#define IDC_MTE164_STATIC               306
#define IDC_MTTYPE_STATIC               307
#define IDB_DOUBLERIGHT_3               307
#define IDC_MTSTATUS_STATIC             308
#define IDB_DOUBLERIGHT_4               308
#define IDC_IPADDR_STATIC               309
#define IDB_DOUBLELEFT_1                309
#define IDC_NETMASK_STATIC              310
#define IDB_DOUBLELEFT_2                310
#define IDC_MACADDR_STATIC              311
#define IDB_DOUBLELEFT_3                311
#define IDC_NETCARDNUM_STATIC           312
#define IDB_DOUBLELEFT_4                312
#define IDC_BANDWIDTH_STATIC            313
#define IDB_RIGHT_1                     313
#define IDC_RECEIVEINITPORT_STATIC      314
#define IDB_RIGHT_2                     314
#define IDC_SENDINITPORT_STATIC         315
#define IDB_RIGHT_3                     315
#define IDB_RIGHT_4                     316
#define IDC_BANDWIDTH_STATIC2           316
#define IDC_WAITTIME_STATIC             317
#define IDB_LEFT_1                      317
#define IDB_LEFT_2                      318
#define IDC_DROPTIMEOUT_STATIC          319
#define IDB_LEFT_3                      319
#define IDC_CHECKPOINT1_STATIC          320
#define IDB_LEFT_4                      320
#define IDC_CHECKPOINT2_STATIC          321
#define IDB_CONNECT_1                   321
#define IDC_CHECKPOINT3_STATIC          322
#define IDB_DIRECTION                   322
#define IDB_CLOSE_DLG_1                 323
#define IDC_VDECFORMAT_STATIC           324
#define IDB_CLOSE_DLG_2                 324
#define IDC_MPEG4VALUE_STATIC           325
#define IDB_IDLEPIC                     325
#define IDD_ADDRENTRY_DLG               326
#define IDC_VENCSOURCE_STATIC           327
#define IDB_LISTMTGROUP                 327
#define IDC_VENCFORMAT_STATIC           328
#define IDD_GROUPENTRY_DLG              328
#define IDC_VENDSYSTEM_STATIC           329
#define IDD_REMOTECTRL_DLG              329
#define IDC_VENCRESOLUTION_STATIC       330
#define IDD_USERMANAGE_DLG              330
#define IDC_VENCBITRATE_STATIC          331
#define IDB_EDIT_1                      331
#define IDC_VENCCOMPRESSVALUE_STATIC    332
#define IDB_EDIT_2                      332
#define IDC_VENCIKENINTERVAL_STATIC     333
#define IDB_EDIT_3                      333
#define IDC_VENCMAXQUALVALUE_STATIC     334
#define IDB_EDIT_4                      334
#define IDC_VENCMINQUALVALUE_STATIC     335
#define IDD_USERINFO_DLG                335
#define IDC_VENCFRAMERATE_STATIC        336
#define IDB_VMP_1                       336
#define IDC_VENCMAXBANDWIDTH_STATIC     337
#define IDB_VMP_2                       337
#define IDC_CONFLIST_STATIC             338
#define IDB_VMP_3                       338
#define IDC_MCUADDR_STATIC              339
#define IDB_MATRIX_1                    339
#define IDC_CALLMT_STATIC               340
#define IDD_VMP_DLG                     340
#define IDC_ENTERPWD_STATIC             341
#define IDB_MATRIX_2                    341
#define IDC_MCUADDR_INFO_STATIC         341
#define IDC_SELMT_STATIC                342
#define IDB_MATRIX_3                    342
#define IDC_CALLTYPE_STATIC             342
#define IDC_INSPECTMODE_STATIC          343
#define IDD_MATRIX_DLG                  343
#define IDC_MCUIP_STATIC                344
#define IDB_BK_TOP                      344
#define IDC_POLINTERVAL_STATIC          345
#define IDB_BK_LEFT                     345
#define IDC_MCUIP_TYPE                  345
#define IDB_BK_RIGHT                    346
#define IDB_BK_LEFT2                    347
#define IDB_BK_MIDBOTTOM                348
#define IDC_VALUEONE_STATIC             349
#define IDB_BK_BOTTOM                   349
#define IDC_VALUE5_STATIC               350
#define IDC_MATRIX_CURSOR               350
#define IDC_VALUE1_STATIC               351
#define IDB_BK_RIGHT2_UP                351
#define IDC_VALUE4_STATIC               352
#define IDB_BK_RIGHT2_DOWN              352
#define IDB_MATRIX_ICON_DIS             353
#define IDC_AUDIODEC_BTN                354
#define IDB_MATRIX_ICON1                354
#define IDC_AUDIOENC_BTN                355
#define IDC_SENDRESEND_BTN              356
#define IDC_AUDIOENC_BTN2               356
#define IDC_GROUP_AEC                   356
#define IDC_RECEIVERESEND_BTN           357
#define IDB_MATRIX_ICON10               357
#define IDC_VIDEODEC_BTN                358
#define IDB_MATRIX_ICON11               358
#define IDC_VIDEOENC_BTN                359
#define IDB_MATRIX_ICON12               359
#define IDC_SAVEPOS_BTN                 360
#define IDB_MATRIX_ICON13               360
#define IDC_SNAPRREVIEW_BTN             361
#define IDC_FILELIST_BTN                362
#define IDB_MATRIX_ICON15               362
#define IDC_SAVEPOS_BTN2                363
#define IDC_CLOSE_BTN                   364
#define IDC_CLOSE                       365
#define IDB_MATRIX_ICON14               366
#define IDB_MATRIX_ICON16               367
#define IDB_MATRIX_ICON4                368
#define IDB_MATRIX_ICON2                369
#define IDB_MATRIX_ICON3                370
#define IDB_MATRIX_ICON5                371
#define IDB_MATRIX_ICON6                372
#define IDB_MATRIX_ICON7                373
#define IDB_MATRIX_ICON8                374
#define IDC_DISCUSSNUM_STATIC           375
#define IDB_MATRIX_ICON9                375
#define IDD_MATRIX_SCHEME               376
#define IDC_LOCALMTNAME_STATIC          377
#define IDD_MATRIX_DISP                 377
#define IDC_ENTRY_LIST                  378
#define IDB_MATRIX_ICON_LIST            378
#define IDC_REMOTENAME_STATIC           378
#define IDC_GROUP_LIST                  379
#define IDB_HANG_UP_3                   379
#define IDC_MTBITRATE_STATIC            380
#define IDC_GROUPMT_LIST                380
#define IDB_HANG_UP_2                   380
#define IDB_HANG_UP_1                   381
#define IDC_CALLALIAS_EDIT              382
#define IDB_CONTROLER                   382
#define IDC_ENTRYNAME_EDIT              383
#define IDB_STOP_3                      383
#define IDC_MT_IPADDR                   384
#define IDB_STOP_2                      384
#define IDC_CALLNUM_EDIT                385
#define IDB_STOP_1                      385
#define IDC_MTBITRATE_EDIT              386
#define IDD_CFGDUAL_CODEC               386
#define IDB_APPLY_3                     387
#define IDC_MODIFY_BTN                  389
#define IDB_CLOSE_DLG_3                 389
#define IDB_APPLY_1                     390
#define IDC_ADD_BTN                     391
#define IDB_APPLY_2                     391
#define IDC_DEL_BTN                     392
#define IDC_CALLALIAS_STATIC            393
#define IDC_ADDTOGROUP_BTN              393
#define IDB_CLOSE_1                     393
#define IDC_CALLNUM_STATIC              394
#define IDC_DELFRMGROUP_BTN             394
#define IDB_CLOSE_2                     394
#define IDC_ENTRYNAME_STATIC            395
#define IDC_ADDOUP_BTN                  395
#define IDC_ENTRY_STATIC                396
#define IDB_PLAY_1                      396
#define IDC_GROUPNAME_STATIC            397
#define IDB_PLAY_2                      397
#define IDC_GROUPMT_STATIC              398
#define IDB_PLAY_3                      398
#define IDC_MTLIST_STATIC               399
#define IDB_PAUSE_3                     399
#define IDC_DELGROUP_BTN                400
#define IDB_PAUSE_2                     400
#define IDC_MODIFYGROUP_BTN             401
#define IDB_PAUSE_1                     401
#define IDC_CLOSEADDR                   402
#define IDB_DUMB_3                      402
#define IDC_GROUP_STATIC                403
#define IDB_MUTE_2                      403
#define IDB_MUTE_3                      404
#define IDC_CONFBITRATE_STATIC          405
#define IDB_DUMB_1                      405
#define IDC_OPEN_CHECK                  406
#define IDB_DUMB_2                      406
#define IDC_GROUPNAME_EDIT              407
#define IDB_MUTE_1                      407
#define IDC_CONFBITRATE_EDIT            408
#define IDB_NO_DUMB_3                   408
#define IDC_MCUIP_IP                    409
#define IDB_NO_DUMB_2                   409
#define IDC_OPEN_STATIC                 410
#define IDB_NO_DUMB_1                   410
#define IDC_POWER                       412
#define IDB_NO_MUTE_3                   412
#define IDC_DECODEMUTE                  413
#define IDB_NO_MUTE_2                   413
#define IDC_NUM_1                       414
#define IDB_NO_MUTE_1                   414
#define IDB_BK_MUTE                     416
#define IDC_NUM_2                       417
#define IDC_USERLIST_STATIC             417
#define IDD_ADDRENTRY                   417
#define IDC_NUM_3                       418
#define IDC_USER_LIST                   418
#define IDD_CAMERA_CONTROL              418
#define IDC_NUM_4                       419
#define IDC_ADD_USER                    419
#define IDC_NUM_5                       420
#define IDC_MODIFY_USER                 420
#define IDD_CFG_MATRIX_DLG              420
#define IDC_NUM_6                       421
#define IDC_DEL_USER                    421
#define IDD_CFGCAMERA_DLG               421
#define IDC_NUM_7                       422
#define IDD_CFG_VIDEOOUT_CFG            422
#define IDC_NUM_8                       423
#define IDC_USERNAME_STATIC             423
#define IDD_DETECT_CALL_DLG             423
#define IDC_NUM_9                       424
#define IDC_FULLNAME_STATIC             424
#define IDD_SMS_PRSET_DLG               424
#define IDC_NUM_0                       425
#define IDC_PWD_STATIC                  425
#define IDD_DETECT_TEST_DLG             425
#define IDC_STAR                        426
#define IDC_PWDCONFIRM_STATIC           426
#define IDD_MTC_SNAPSHOT_DLG            426
#define IDC_POUND                       427
#define IDC_RIGHT_STATIC                427
#define IDB_MANAGE_CONF_4               427
#define IDC_ENCODEMUTE                  428
#define IDC_DESCRIBE_STATIC             428
#define IDB_MANAGE_CONF_2               428
#define IDC_SELFCHECK                   429
#define IDC_USERNAME_EDIT               429
#define IDB_MANAGE_CONF_3               429
#define IDC_ONOFF                       430
#define IDC_FULLNAME_EDIT               430
#define IDB_MANAGE_CONF_1               430
#define IDC_ZOOM                        431
#define IDC_PWD_EDIT                    431
#define IDB_MANAGE_DEVICE_4             431
#define IDC_CHAIRMAN                    432
#define IDC_PWDCONFIRM_EDIT             432
#define IDB_MANAGE_DEVICE_2             432
#define IDC_SPEAK                       433
#define IDC_DESCRIBE_EDIT               433
#define IDB_MANAGE_DEVICE_3             433
#define IDC_QUIT                        434
#define IDC_RIGHT_COMBO                 434
#define IDB_MANAGE_DEVICE_1             434
#define IDC_STATUS                      435
#define IDC_STARTVMP_BTN                435
#define IDB_MANAGE_CONFIG_4             435
#define IDC_SETTING                     436
#define IDC_STOPVMP_BTN                 436
#define IDB_MANAGE_CONFIG_2             436
#define IDC_MANU                        437
#define IDC_VMPSTYLE_COMBO              437
#define IDB_MANAGE_CONFIG_3             437
#define IDC_LEFT                        438
#define IDC_VMPSTYLE_STATIC             438
#define IDB_MANAGE_CONFIG_1             438
#define IDC_RIGHT                       439
#define IDC_VMPBTN_1                    439
#define IDB_MANAGE_SYSTEM_4             439
#define IDC_UP                          440
#define IDC_VMPBTN_2                    440
#define IDB_MANAGE_SYSTEM_2             440
#define IDC_DOWN                        441
#define IDC_VMPBTN_3                    441
#define IDB_MANAGE_SYSTEM_3             441
#define IDC_CONFIRM                     442
#define IDC_VMPBTN_4                    442
#define IDB_MANAGE_SYSTEM_1             442
#define IDC_VMPBTN_5                    443
#define IDB_MANAGE_DETECT_4             443
#define IDC_VMPBTN_6                    444
#define IDB_MANAGE_DETECT_2             444
#define IDC_VMPBTN_7                    445
#define IDB_MANAGE_DETECT_3             445
#define IDC_VMPBTN_8                    446
#define IDB_MANAGE_DETECT_1             446
#define IDC_VMPBTN_9                    447
#define IDB_BITMAP_TEST                 447
#define IDC_VMPBTN_10                   448
#define IDC_VMPBTN_11                   449
#define IDB_BK_LINE                     449
#define IDC_VMPBTN_12                   450
#define IDB_EAR_RIGHT                   450
#define IDC_VMPBTN_13                   451
#define IDB_EAR_LEFT                    451
#define IDC_VMPBTN_14                   452
#define IDC_VMPBTN_15                   453
#define IDB_BK_FREETIME                 453
#define IDC_VMPBTN_16                   454
#define IDB_HEAD_ADDRBOOK_4             454
#define IDC_BROADCAST_CHECK             455
#define IDB_HEAD_ADDRBOOK_2             455
#define IDB_HEAD_ADDRBOOK_3             456
#define IDC_RECT                        457
#define IDB_HEAD_ADDRBOOK_1             457
#define IDC_TITLE_STATIC                458
#define IDB_HEAD_SNAPSHOT_4             458
#define IDB_HEAD_SNAPSHOT_2             459
#define IDC_VMATRIX_BTN                 460
#define IDB_HEAD_SNAPSHOT_3             460
#define IDC_AMATRIX_BTN                 461
#define IDB_HEAD_SNAPSHOT_1             461
#define IDC_VSCHE_COMBO                 462
#define IDC_SAVE_VSCHE_BTN              463
#define IDB_HEAD_DUAL_4                 463
#define IDC_VINPORT_STATIC_0            464
#define IDB_HEAD_DUAL_2                 464
#define IDC_VINPORT_STATIC_1            465
#define IDB_HEAD_DUAL_3                 465
#define IDC_VINPORT_BTN_0               466
#define IDB_HEAD_DUAL_1                 466
#define IDC_VINPORT_STATIC_2            467
#define IDC_COMBO1                      467
#define IDC_SCHEID_COMBO                467
#define IDC_COMBO_POLL_TYPE             467
#define IDC_CB_LABEL_TYPE               467
#define IDC_COMBO_VIDEO_FORMAT          467
#define IDC_COMBO_NET_TYPE              467
#define IDC_COMBO_POLICY                467
#define IDC_COMBO_TYPE                  467
#define IDC_COMBO_PRESET                467
#define IDC_COMBO_TVOUT_TYPE            467
#define IDB_HEAD_RESET_4                467
#define IDC_COMBO_PROTOCOL              467
#define IDC_COMBO_TIME                  467
#define IDC_COMBO_DUAL_TYPE             467
#define IDC_COMBO_CONF_GROUP            467
#define IDC_COMBO_BANNER_FONT_SIZE      467
#define IDC_COMBO_ADDR_GROUP            467
#define IDC_COMBO_FRAME_RATE_COUNT      467
#define IDC_CB_DECOMPRESS               467
#define IDC_COMBO_WAITUNIT              467
#define IDC_COMBO_ISNETKEEP             467
#define IDC_COMBO_ETHSEQ                467
#define IDC_COMBO_QOS                   467
#define IDC_COMBO_VIDEOTYPE             467
#define IDC_COMBO_SMS_TYPE              467
#define IDC_COMBO_BK_MODE               467
#define IDC_COMBO_CONTROL_TYPE          467
#define IDC_COMBO_EXMATRIXYPE           467
#define IDC_VINPORT_STATIC_3            468
#define IDC_COPYRIGHT_STATIC            468
#define IDC_COMBO_AUDIO_FORMAT          468
#define IDB_HEAD_RESET_2                468
#define IDC_COMBO_BAUDRATE              468
#define IDC_COMBO_BANNER_PLACE          468
#define IDC_COMBO_SPEED                 468
#define IDC_VINPORT_STATIC_4            469
#define IDC_MONITOR_STATIC              469
#define IDC_COMBO_RESOLUTION            469
#define IDB_HEAD_RESET_3                469
#define IDC_COMBO_BYTESIZE              469
#define IDC_COMBO_BANNER_ALIGN          469
#define IDC_VINPORT_STATIC_5            470
#define IDC_RIGHTDOWN_STATIC            470
#define IDB_HEAD_RESET_1                470
#define IDC_COMBO_PARITY                470
#define IDC_COMBO_CONF_BITRATE          470
#define IDC_COMBO_BANNER_SCROLL_MODE    470
#define IDC_VINPORT_STATIC_6            471
#define IDC_BKRIGHT_STATIC              471
#define IDC_COMBO_STOPBITS              471
#define IDC_COMBO_BANNER_SCROLL_SPEED   471
#define IDC_COMBO_ENCRYPT               471
#define IDC_VINPORT_STATIC_7            472
#define IDB_HEAD_ABOUT_4                472
#define IDC_VINPORT_STATIC_8            473
#define IDC_SCHENAME_EDIT               473
#define IDB_HEAD_ABOUT_2                473
#define IDC_VINPORT_STATIC_9            474
#define IDC_SCHEID_STATIC               474
#define IDB_HEAD_ABOUT_3                474
#define IDC_VINPORT_STATIC_10           475
#define IDC_SCHENAME_STATIC             475
#define IDB_HEAD_ABOUT_1                475
#define IDC_VINPORT_STATIC_11           476
#define IDC_PORTNAME_STATIC             476
#define IDB_MONITOR_SNAPSHOT_4          476
#define IDC_VINPORT_STATIC_12           477
#define IDC_PORTPIC_STATIC              477
#define IDB_MONITOR_SNAPSHOT_2          477
#define IDC_VINPORT_STATIC_13           478
#define IDC_PORTNAME_EDIT               478
#define IDB_MONITOR_SNAPSHOT_3          478
#define IDC_VINPORT_STATIC_14           479
#define IDC_PORTPIC_LIST                479
#define IDB_MONITOR_SNAPSHOT_1          479
#define IDC_VINPORT_STATIC_15           480
#define IDB_MONITOR_FULL_4              480
#define IDC_VOUTPORT_STATIC_0           481
#define IDC_SLIDER_BRIGHTNESS           481
#define IDB_MONITOR_FULL_2              481
#define IDC_VOUTPORT_STATIC_1           482
#define IDC_SLIDER_SATURATION           482
#define IDB_MONITOR_FULL_3              482
#define IDC_VOUTPORT_STATIC_2           483
#define IDC_SLIDER_CONTRAST             483
#define IDB_MONITOR_FULL_1              483
#define IDC_VOUTPORT_STATIC_3           484
#define IDC_STATIC_BRIGHTNESS           484
#define IDB_RADIO_UNSEL_2               484
#define IDC_VOUTPORT_STATIC_4           485
#define IDC_STATIC_SATURATION           485
#define IDB_RADIO_SEL_2                 485
#define IDC_VOUTPORT_STATIC_5           486
#define IDC_STATIC_CONTRAST             486
#define IDB_RADIO_UNSEL_1               486
#define IDC_VOUTPORT_STATIC_6           487
#define IDC_CHECK_BROADCAST             487
#define IDB_RADIO_SEL_1                 487
#define IDC_VOUTPORT_STATIC_7           488
#define IDC_STATIC_POLL_TYPE            488
#define IDC_VOUTPORT_STATIC_8           489
#define IDC_BTN_CHANGE_BMP              489
#define IDB_PROMPT                      489
#define IDC_VOUTPORT_STATIC_9           490
#define IDC_STATIC_BMP                  490
#define IDD_ANSWER_APPLY                490
#define IDC_VOUTPORT_STATIC_10          491
#define IDC_CK_LABEL_SHOW               491
#define IDD_CFG_SERIAPORT               491
#define IDC_VOUTPORT_STATIC_11          492
#define IDC_CK_LABLE_ENCODE             492
#define IDD_SLEEP                       492
#define IDC_VOUTPORT_STATIC_12          493
#define IDC_VOUTPORT_STATIC_13          494
#define IDC_CB_PIPMODE                  494
#define IDB_HEAD_DORMANCY_4             494
#define IDC_VOUTPORT_STATIC_14          495
#define IDC_STATIC_LABEL_TYPE           495
#define IDB_HEAD_DORMANCY_2             495
#define IDC_VOUTPORT_STATIC_15          496
#define IDC_STATIC_PIP_MODE             496
#define IDB_HEAD_DORMANCY_3             496
#define IDC_VINPORT_BTN_1               497
#define IDC_STATIC_LABEL                497
#define IDB_HEAD_DORMANCY_1             497
#define IDC_VINPORT_BTN_2               498
#define IDC_EDIT_PWD                    498
#define IDC_STATIC_SWTCH_DELAY          498
#define IDB_CONTROLER_4                 498
#define IDC_VINPORT_BTN_3               499
#define IDC_EDIT_PWD_CONFIRM            499
#define IDC_STATIC_SWITCH               499
#define IDB_CONTROLER_2                 499
#define IDC_VINPORT_BTN_4               500
#define IDC_EDIT_CONF_NUM               500
#define IDB_CONTROLER_3                 500
#define IDC_VINPORT_BTN_5               501
#define IDC_CHECK_AUTOVMP               501
#define IDB_CONTROLER_1                 501
#define IDC_VINPORT_BTN_6               502
#define IDC_CHECK_VAC                   502
#define IDD_DUAL_SELECT                 502
#define IDC_VINPORT_BTN_7               503
#define IDC_CHECK_AUDIO_MIX             503
#define IDD_VERSION                     503
#define IDC_VINPORT_BTN_8               504
#define IDC_EDIT_CONF_DELAY             504
#define IDC_VINPORT_BTN_9               505
#define IDC_STATIC_PWD1                 505
#define IDC_VINPORT_BTN_10              506
#define IDC_STATIC_PWD2                 506
#define IDC_VINPORT_BTN_11              507
#define IDC_STATIC_RESOLUTION           507
#define IDC_VINPORT_BTN_12              508
#define IDC_STATIC_AFORMAT              508
#define IDC_VINPORT_BTN_13              509
#define IDC_STATIC_VFORMAT              509
#define IDB_LOGO                        509
#define IDC_VINPORT_BTN_14              510
#define IDC_STATIC_CONF_DELAY           510
#define IDC_VINPORT_BTN_15              511
#define IDC_STATIC_CONF_NUM             511
#define IDD_DIALOG_ADD_MT_TO_CONF       511
#define IDC_VOUTPORT_BTN_0              512
#define IDC_EDIT_CONF_BITRATE           512
#define IDC_VOUTPORT_BTN_1              513
#define IDC_STATIC_BITRATE              513
#define IDC_VOUTPORT_BTN_2              514
#define IDC_BUTTON1                     514
#define IDC_CFG_DUALSTREAM              514
#define IDC_BTN_SEL_MT                  514
#define IDC_SAVE                        514
#define IDC_RESET                       514
#define IDC_BTN_ADDR                    514
#define IDC_BTN_LEFT                    514
#define IDC_BTN_SELFTEST                514
#define IDC_BTN_CANCEL                  514
#define IDC_BTN_GROUP                   514
#define IDC_BTN_OK                      514
#define IDC_BTN_BACKUP                  514
#define IDC_BUTTON_ADDMT_QUIT           514
#define IDD_DIALOG_CONF_SELECT_MT       514
#define IDC_BUTTON_MT_DEL               514
#define IDC_BUTTON_SEARCH               514
#define IDC_BUTTON_CALL_SET_DEFAULT     514
#define IDC_BUTTON_ACTUAL_BANNER_QUIT   514
#define IDC_BUTTON_CHOSE_FONT           514
#define IDC_BUTTON_TRANSFER_EXIT        514
#define IDC_MAINVSRC                    514
#define IDC_BTN_CHANGEOSD               514
#define IDC_BTN_H264ADVAN               514
#define IDC_BUTTON_SMS_ADVAN            514
#define IDC_BTN_BKCORLOR                514
#define IDC_BTN_CANCELLOAD              514
#define IDC_BTN_START                   514
#define IDC_BTN_EXMATRIXSCHEM           514
#define IDC_VOUTPORT_BTN_3              515
#define IDC_BTN_SET_GROUP               515
#define IDC_BTN_UP                      515
#define IDC_BUTTON_MT_ADD               515
#define IDC_BUTTON_GROUP_ADD            515
#define IDC_BTN_UNSELECT                515
#define IDC_VOUTPORT_BTN_4              516
#define IDC_BTN_SEL_MT_GROUP            516
#define IDC_BTN_RIGHT                   516
#define IDD_DIALOG_NEW_ADDRBOOK         516
#define IDC_BUTTON_ADD_GROUP_MT         516
#define IDC_BTN_SELETEALL               516
#define IDC_VOUTPORT_BTN_5              517
#define IDC_BTN_APPLY                   517
#define IDC_BTN_FOCUS_FAR               517
#define IDD_DIALOG_BANNER               517
#define IDC_BUTTON_DEL_GROUP_MT         517
#define IDC_BTN_DELETEALL               517
#define IDC_VOUTPORT_BTN_6              518
#define IDC_DELETE                      518
#define IDC_BTN_DOWN                    518
#define IDD_DIALOG_ADDRBOOK_MANAGE      518
#define IDC_BUTTON_GROUP_MODIFY         518
#define IDC_VOUTPORT_BTN_7              519
#define IDC_MIC_VOLUME                  519
#define IDC_BTN_FOCUS_NEAR              519
#define IDC_BUTTON_GROUP_DEL            519
#define IDB_BITMAP_BANNER_BK            519
#define IDC_VOUTPORT_BTN_8              520
#define IDC_SPEAKER_VOLUME              520
#define IDC_BTN_FOCUS_AUTO              520
#define IDC_BUTTON_ADD_MT               520
#define IDC_VOUTPORT_BTN_9              521
#define IDC_MUTE                        521
#define IDC_BTN_ZOOM_IN                 521
#define IDC_BUTTON_MODIFY_MT            521
#define IDR_MENU_EDITCTRL               521
#define IDC_DUMB                        522
#define IDC_VOUTPORT_BTN_10             522
#define IDC_DISPLAY_STATUS              522
#define IDC_BTN_ZOOM_OUT                522
#define IDC_BUTTON_DEL_MT               522
#define IDD_DIALOG_BANNER_ACTUAL_VIEW   522
#define IDC_VOUTPORT_BTN_11             523
#define IDC_CK_SWITCHTOMONITMT          523
#define IDB_BITMAP_BANNER_BK_SMALL      523
#define IDC_VOUTPORT_BTN_12             524
#define IDB_BITMAP_BANNER_BK_BIG        524
#define IDC_VOUTPORT_BTN_13             525
#define IDC_ADDRESS                     525
#define IDD_DIALOG_TRANSFER_BANNER      525
#define IDC_VOUTPORT_BTN_14             526
#define IDC_MCU_ADDRESS                 526
#define IDC_CURSOR_MOVE_BANNER          526
#define IDD_REMOTECTRL_NEW_DLG          526
#define IDC_VOUTPORT_BTN_15             527
#define IDC_MT_ADDRESS                  527
#define IDD_REMOTECTRL_REVIEW           527
#define IDC_ASCHE_COMBO                 528
#define IDC_STATIC_TRAP                 528
#define IDB_NEWCTRL_1                   528
#define IDC_SAVE_ASCHE_BTN              529
#define IDC_EDIT_COMMUNITY_NAME         529
#define IDB_NEWCTRL_2                   529
#define IDC_AINPORT_STATIC_0            530
#define IDC_STATIC_COMMUNITY            530
#define IDB_PREVIEW_NEWCTRL             530
#define IDC_AINPORT_STATIC_1            531
#define IDC_BTN_DEL_ALL                 531
#define IDB_PREVIEW_OLDCTRL             531
#define IDC_AINPORT_STATIC_2            532
#define IDC_STATIC_COUNT                532
#define IDB_OLDCTRL_2                   532
#define IDC_AINPORT_STATIC_3            533
#define IDC_STATIC_SPARE_SIZE           533
#define IDB_OLDCTRL_1                   533
#define IDC_AINPORT_STATIC_4            534
#define IDC_BTN_CLOSE                   534
#define IDC_AINPORT_STATIC_5            535
#define IDC_ST_NET_TYPE                 535
#define IDC_AINPORT_STATIC_6            536
#define IDC_STATIC_ADVICE               536
#define IDC_AINPORT_STATIC_7            537
#define IDC_CHECK_AEC                   537
#define IDD_264_ENCODE_SET              537
#define IDC_AINPORT_STATIC_8            538
#define IDC_CHECK_AGC                   538
#define IDC_AINPORT_STATIC_9            539
#define IDC_CHECK_AUTO_FRAME            539
#define IDD_FILETRANSFER_DLG            539
#define IDC_AINPORT_STATIC_10           540
#define IDC_BTN_SNAPSHOT                540
#define IDC_AINPORT_STATIC_11           541
#define IDC_RESET_MT                    541
#define IDB_UPLOAD_1                    541
#define IDC_AINPORT_STATIC_12           542
#define IDC_ABOUT                       542
#define IDB_UPLOAD_2                    542
#define IDC_AINPORT_STATIC_13           543
#define IDC_HELP_DOC                    543
#define IDC_SLEEP_MT                    543
#define IDB_UPLOAD_3                    543
#define IDC_AINPORT_STATIC_14           544
#define IDC_FULLSCREEN_LOCAL            544
#define IDB_UPLOAD_4                    544
#define IDC_AINPORT_STATIC_15           545
#define IDC_FULLSCREEN_REMOTE           545
#define IDD_CFGE1CHAN_DLG               545
#define IDC_AOUTPORT_STATIC_0           546
#define IDC_LIST_MT                     546
#define IDD_CFGE1MODULE_DLG             546
#define IDC_AOUTPORT_STATIC_1           547
#define IDC_LOAD_MSG                    547
#define IDD_DIALOG_CFGROUTE             547
#define IDC_AOUTPORT_STATIC_2           548
#define IDC_PRESET_MSG                  548
#define IDD_DIALOG_IPROUTEINFO          548
#define IDC_AOUTPORT_STATIC_3           549
#define IDC_AOUTPORT_STATIC_4           550
#define IDC_LIST1                       550
#define IDC_LISTBOX_MT                  550
#define IDC_LIST_ADDMT_ALL_MT           550
#define IDC_LIST_CONF_MT                550
#define IDC_LIST_GROUP                  550
#define IDC_FILE_LIST                   550
#define IDC_LIST_ROUTE                  550
#define IDC_CONFIGINFO_LIST             550
#define IDC_LIST_FILELIST               550
#define IDC_AOUTPORT_STATIC_5           551
#define IDC_LIST_ADDMT_ALL_GROUP        551
#define IDC_LIST_CONF_ATTENDMT          551
#define IDC_AOUTPORT_STATIC_6           552
#define IDC_BTN_MODIFY                  552
#define IDC_LIST_ADDMT_GROUP_MT         552
#define IDC_AOUTPORT_STATIC_7           553
#define IDC_BTN_ADD                     553
#define IDB_BITMAP_LOGIN                553
#define IDC_AOUTPORT_STATIC_8           554
#define IDC_BTN_DEL                     554
#define IDC_AOUTPORT_STATIC_9           555
#define IDC_BTN_SEARCH                  555
#define IDC_AOUTPORT_STATIC_10          556
#define IDC_EDIT_BITRATE                556
#define IDC_AOUTPORT_STATIC_11          557
#define IDC_SHEET_TITLE                 557
#define IDB_REWAKE_1                    557
#define IDC_AOUTPORT_STATIC_12          558
#define IDB_REWAKE_2                    558
#define IDC_AOUTPORT_STATIC_13          559
#define IDB_REWAKE_3                    559
#define IDC_AOUTPORT_STATIC_14          560
#define IDD_CFGUSER_DLG                 560
#define IDC_AOUTPORT_STATIC_15          561
#define IDD_CFGH323CFG_DLG              561
#define IDC_AINPORT_BTN_0               562
#define IDC_EDIT_PORT                   562
#define IDD_CFG_ETHNET_DLG              562
#define IDC_AINPORT_BTN_1               563
#define IDC_BTN_BRIGHT_HIGH             563
#define IDD_CFG_FIREWALL_DLG            563
#define IDC_AINPORT_BTN_2               564
#define IDC_BTN_BRIGHT_LOW              564
#define IDD_CFG_QOS_DIALOG              564
#define IDC_AINPORT_BTN_3               565
#define IDD_DIALOG1                     565
#define IDD_DETECT_CALL_INFO_DLG        565
#define IDC_AINPORT_BTN_4               566
#define IDC_BTN_SAVE                    566
#define IDD_DIALOG_VIDEOPARAM           566
#define IDC_VINPORT_BTN_21              567
#define IDC_AINPORT_BTN_5               567
#define IDC_BTN_LOAD                    567
#define IDC_AINPORT_BTN_6               568
#define IDC_TAB_CAM                     568
#define IDB_BTN_BLANK1                  568
#define IDC_AINPORT_BTN_7               569
#define IDC_CHECK_USE                   569
#define IDB_BTN_BLANK3                  569
#define IDC_AINPORT_BTN_8               570
#define IDB_BTN_BLANK2                  570
#define IDC_AINPORT_BTN_9               571
#define IDC_RADIO_NET                   571
#define IDC_RADIO_BANNER_STOP_INFINITE  571
#define IDC_RADIO_CALL_MT               571
#define IDC_RADIO_FRAME_ADJUST_AUTO     571
#define IDC_RADIO_ENCRYPT_AUTO          571
#define IDC_RADIO_LOCAL                 571
#define IDC_RADIO_PAP                   571
#define IDC_RADIO_ENCRYAUTO             571
#define IDC_RADIO_BKTRANSPARENT         571
#define IDC_RADIO_HALFTRANSPARENT       571
#define IDC_RADIO_BEGIN                 571
#define IDC_AINPORT_BTN_10              572
#define IDC_RADIO2                      572
#define IDC_RADIO_RS232                 572
#define IDC_RADIO_BANNER_STOP_CERTAIN_TIME 572
#define IDC_RADIO_CALL_MCU              572
#define IDC_RADIO_FRAME_ADJUST_FIX      572
#define IDC_RADIO_ENCRYPT_CLOSE         572
#define IDC_RADIO_REMOTE                572
#define IDC_RADIO_CHAP                  572
#define IDC_RADIO_ENCRYCLOSE            572
#define IDD_DETECT_CODEC_INFO_DLG       572
#define IDC_RADIO_BKOPAQUE              572
#define IDC_AINPORT_BTN_11              573
#define IDC_RADIO3                      573
#define IDC_RADIO_RS422                 573
#define IDC_RADIO_BANNER_SCROLL_TIME_INFINITE 573
#define IDC_RADIO_AUTO_DISCARD_FRAME_PERMIT 573
#define IDC_RADIO_ENCRYPT_MODE_AUTO     573
#define IDC_RADIO_ENCRYMODEAUTO         573
#define IDC_AINPORT_BTN_12              574
#define IDC_RADIO4                      574
#define IDC_RADIO_RS485                 574
#define IDC_RADIO_BANNER_SCROLL_CERTAIN_TIMES 574
#define IDC_RADIO_AUTO_DISCARD_FRAME_DISABLE 574
#define IDC_RADIO_ENCRYPT_MODE_AES      574
#define IDC_RADIO_ENCRYAES              574
#define IDB_COLORPICK_BTN4              574
#define IDC_AINPORT_BTN_13              575
#define IDC_EDIT_CHANNEL_NAME           575
#define IDC_RADIO_ENCRYPT_MODE_DES      575
#define IDB_COLORPICK_BTN2              575
#define IDC_RADIO5                      575
#define IDC_AINPORT_BTN_14              576
#define IDC_EDIT_CHANNEL_PWD            576
#define IDC_RADIO_H329_AUTO             576
#define IDB_COLORPICK_BTN3              576
#define IDC_RADIO6                      576
#define IDC_AINPORT_BTN_15              577
#define IDC_EDIT_GBC_PORT               577
#define IDB_COLORPICK_BTN1              577
#define IDC_RADIO7                      577
#define IDC_AOUTPORT_BTN_0              578
#define IDC_CK_OPEN_VIDEO               578
#define IDD_DIALOG_CONNECT2             578
#define IDC_RADIO8                      578
#define IDC_AOUTPORT_BTN_1              579
#define IDC_IPADDRESS_GROUPBC           579
#define IDC_RADIO_H329_CLOSE            579
#define IDC_RADIO9                      579
#define IDC_AOUTPORT_BTN_2              580
#define IDC_COMBO_SOURCE                580
#define IDD_LOG_ADVANCE_DLG             580
#define IDC_RADIO10                     580
#define IDC_AOUTPORT_BTN_3              581
#define IDC_SYSTEM_DETECT               581
#define IDC_RADIO11                     581
#define IDC_AOUTPORT_BTN_4              582
#define IDC_EDIT_SMS_CONTENT            582
#define IDD_EX_MATRIX_DLG               582
#define IDC_RADIO12                     582
#define IDC_AOUTPORT_BTN_5              583
#define IDC_BTN_DELETE                  583
#define IDD_EX_MATRIX_SCHEME_DLG        583
#define IDC_RADIO13                     583
#define IDC_AOUTPORT_BTN_6              584
#define IDC_STATIC_INFO                 584
#define IDC_RADIO14                     584
#define IDD_VOD_DLG                     584
#define IDC_AOUTPORT_BTN_7              585
#define IDC_BTN_VOICE_TEST              585
#define IDC_RADIO15                     585
#define IDD_VOD_LOGIN_DLG               585
#define IDC_AOUTPORT_BTN_8              586
#define IDC_PROGRESS_IN                 586
#define IDC_RADIO16                     586
#define IDB_VOD_FILE                    586
#define IDC_AOUTPORT_BTN_9              587
#define IDC_BTN_IMAGE_TEST              587
#define IDC_RADIO17                     587
#define IDB_VOD_FILEFOLDER              587
#define IDC_AOUTPORT_BTN_10             588
#define IDC_PROGRESS_OUT                588
#define IDC_RADIO18                     588
#define IDB_VOD_VOLUME                  588
#define IDC_AOUTPORT_BTN_11             589
#define IDC_CHECK_LOCAL                 589
#define IDC_RADIO19                     589
#define IDB_VOD_VOLUME_OVER             589
#define IDC_AOUTPORT_BTN_12             590
#define IDC_CHECK_REMOTE                590
#define IDC_RADIO20                     590
#define IDC_AOUTPORT_BTN_13             591
#define IDC_RADIO21                     591
#define IDB_VOD_VOLUME_PRESS            591
#define IDC_AOUTPORT_BTN_14             592
#define IDC_RADIO22                     592
#define IDC_AOUTPORT_BTN_15             593
#define IDC_RADIO23                     593
#define IDB_VOD_VOLUME_UNABLE           593
#define IDC_EDIT_VGA_RATE               594
#define IDC_RADIO24                     594
#define IDD_CFGEXMATRIX_DLG             594
#define IDC_RADIO25                     595
#define IDC_PIC_FRAME                   596
#define IDC_RADIO26                     596
#define IDC_EDIT_PATH                   597
#define IDC_RADIO27                     597
#define IDC_SAVEAS_BTN                  598
#define IDC_RADIO28                     598
#define IDC_SAVE_BTN                    599
#define IDC_RADIO29                     599
#define IDC_BTN_LOCAL_SNAPSHOT          600
#define IDC_RADIO30                     600
#define IDC_BTN_REMOTE_SNAPSHOT         601
#define IDC_RADIO31                     601
#define IDC_CHECK_ENABLE_PIP            602
#define IDC_RADIO32                     602
#define IDC_COMBO_DUAL_MODE             603
#define IDC_COMBO_VIDEO_SRC             603
#define IDC_RADIO33                     603
#define IDC_BTN_ADDRESSBOOK             604
#define IDC_RADIO34                     604
#define IDC_CHECK_P2P                   605
#define IDC_RADIO35                     605
#define IDC_RADIO36                     606
#define IDC_BTN_PIP_SWTICH              607
#define IDC_RADIO37                     607
#define IDC_RADIO38                     608
#define IDC_RADIO39                     609
#define IDC_RADIO40                     610
#define IDC_RADIO41                     611
#define IDC_BTN_PIP_MOVE                612
#define IDC_RADIO42                     612
#define IDC_STATIC_SHEET                613
#define IDC_RADIO43                     613
#define IDC_STATIC_MANAGE_CONF          614
#define IDC_RADIO44                     614
#define IDC_STATIC_MANAGE_DEVICE        615
#define IDC_RADIO45                     615
#define IDC_STATIC_MANAGE_CONFIG        616
#define IDC_RADIO46                     616
#define IDC_STATIC_MANAGE_SYSTEM        617
#define IDC_RADIO47                     617
#define IDC_STATIC_MANAGE_DETECT        618
#define IDC_RADIO48                     618
#define IDC_STATIC_IN                   619
#define IDC_RADIO49                     619
#define IDC_STATIC_OUT                  620
#define IDC_RADIO50                     620
#define IDC_COMBO_MCU_TYPE              621
#define IDC_RADIO51                     621
#define IDC_COMBO_MT_TYPE               622
#define IDC_STATIC_SAVEPATH             622
#define IDC_RADIO52                     622
#define IDC_STATIC_TYPE                 623
#define IDC_RADIO53                     623
#define IDC_STATIC_IPADDR               624
#define IDC_RADIO54                     624
#define IDC_STATIC_CAMTYPE              625
#define IDC_RADIO55                     625
#define IDC_STATIC_PORT                 626
#define IDC_RADIO56                     626
#define IDC_STATIC_FOCUS                627
#define IDC_STATIC_CAMSPEED             627
#define IDC_RADIO57                     627
#define IDC_STATIC_ZOOM                 628
#define IDC_RADIO58                     628
#define IDC_STATIC_LIGHT                629
#define IDC_RADIO59                     629
#define IDC_STATIC_SOURCE               630
#define IDC_RADIO60                     630
#define IDC_STATIC_PRSET                631
#define IDC_RADIO61                     631
#define IDC_GROUP_SOURCE                632
#define IDC_RADIO62                     632
#define IDC_GROUP_STREAM                633
#define IDC_PRESET_SOURCE               633
#define IDC_RADIO63                     633
#define IDC_GROUP_VIDEO_OUT             634
#define IDC_RADIO64                     634
#define IDC_GROUP_IMG                   635
#define IDC_GROUP_DIRECT                636
#define IDC_LIST_MSG                    637
#define IDC_STATIC_LIST                 638
#define IDC_STATIC_CONTENT              639
#define IDC_STATIC_HEAD                 640
#define IDC_STATIC_TIP                  641
#define IDC_STATIC_ZOOM_INFO            645
#define IDC_ST_VERSION_INFO             646
#define IDC_STATIC_ADDR_SET             647
#define IDC_EDIT_ADDR_SET               648
#define IDC_BUTTON_ADDMT_SELECT_MT      649
#define IDC_BUTTON_ADDMT_SELECT_GROUP   650
#define IDC_BUTTON_ADDMT_SELECT_GROUP_MT 651
#define IDC_BUTTON_ADD_MT_CLOSE         652
#define IDC_STATIC_CONF_GROUP           653
#define IDC_BUTTON_CONF_ADDMT_SURE      654
#define IDC_BUTTON_CONF_ADDMT_CANCEL    655
#define IDC_BUTTON_CONF_CLOSE           656
#define IDC_BUTTON_MT_ADDALL            657
#define IDC_BUTTON_MT_DELALL            658
#define IDC_STATIC_GROUP_MEMBER         658
#define IDC_LIST_GROUP_MEMBER           659
#define IDC_LIST_ADDR_ALL_MT            660
#define IDC_BUTTON_ADDR_ADD_MT          661
#define IDC_BUTTON_ADDR_DELMT           662
#define IDC_BUTTON_ADDR_MODIFYMT        663
#define IDC_BUTTON_ADDR_ADDGROUP_MEMBER 664
#define IDC_LIST_ADDR_ALL_GROUP         665
#define IDC_BUTTON_DELGROUP_MEMBER      666
#define IDC_CHECK_BANNER_ENABLE         666
#define IDC_BUTTON_ADDR_ADDGROUP        667
#define IDC_EDIT_BANNER_CONTENT         667
#define IDC_BUTTON_ADDR_DELGROUP        668
#define IDC_STATIC_BANNER_PREVIEW       668
#define IDC_BUTTON_BANNER_SAVE          669
#define IDC_BUTTON_BANNER_OPEN          670
#define IDC_STATIC_BANNER_BK_COLOR      674
#define IDC_STATIC_BANNER_FONT_COLOR    675
#define IDC_EDIT_BANNER_STOP_TIME       678
#define IDC_EDIT_BANNER_SCROLL_TIME     679
#define IDC_RADIO_BANNER_BK_TRANSPARENT 682
#define IDC_RADIO_BANNER_BK_OPAQUE      683
#define IDC_STATIC_FRAME_CONTENT        684
#define IDC_STATIC_FRAME_SHOW           685
#define IDC_STATIC_FRAME_PREVIEW        686
#define IDC_EDIT_SEARCH                 687
#define IDC_STATIC_CURRENT_GROUP        688
#define IDC_STATIC_FRAME_MT             689
#define IDC_STATIC_FRAME_GROUP          690
#define IDC_EDIT_FIND_MT                691
#define IDC_BUTTON_FIND_MT              692
#define IDC_EDIT_ADDR_MM_MT             693
#define IDC_BUTTON_ADDR_MM_FIND         694
#define IDC_COMBO_BANNER_FONT_NAME      695
#define IDC_BUTTON_ADVANCED_CFG         698
#define IDC_STATIC_SHOW_TIME            699
#define IDC_LIST_OPERATION              701
#define IDC_LIST_R_S_SMSG               703
#define IDC_STATIC_BANNER_CONTAINER     704
#define IDC_EDIT_MCU_ADDR               705
#define IDC_SLIDER_BANNER_VERT_PLACE    709
#define IDC_STATIC_TRANSFER_TIP         710
#define IDC_STATIC_SHOW_LINE            711
#define IDC_EDIT_BANNER_SHOW_LINE       712
#define IDC_BUTTON_TRANSFER_STATUS_EXIT 713
#define IDC_STATIC_DUAL_FRAME_TOP       714
#define IDC_STATIC_DUAL_FRAME_BOTTOM    715
#define IDC_EDIT_FRAME_RATE             716
#define IDC_RADIO_PICTURE_QUANLITY_FIRST 717
#define IDC_RADIO_PICTURE_SPEED_FIRST   718
#define IDC_EDIT_FRAME_INTERVAL         719
#define IDC_EDIT_LIANGHUA_PARA_BEGIN    720
#define IDC_EDIT_LIANGHUA_PARA_END      721
#define IDC_EDIT_OPERATION_LIST         722
#define IDC_RADIO_PICTURE_QUANLITY_FIRST2 722
#define IDC_EDIT_LIST_OPERATION         723
#define IDC_AV                          724
#define IDC_FARCTRL                     725
#define IDC_VGA                         726
#define IDC_S                           727
#define IDC_CONNECT                     728
#define IDC_SHOTSNAP                    729
#define IDC_DISCONNECT                  730
#define IDC_VOLDEC                      732
#define IDC_VOLINC                      733
#define IDC_DEL                         734
#define IDC_PREMOVE                     735
#define IDC_PRESAVE                     736
#define IDC_AUTOFOCUS                   737
#define IDC_NEARZOOM                    738
#define IDC_FARZOOM                     739
#define IDC_BRIGHTDEC                   740
#define IDC_BRIGHTINC                   741
#define IDC_PIPENABLE                   742
#define IDC_PIPVERSE                    743
#define IDC_DUAL                        744
#define IDC_SELFTEST                    745
#define IDC_HOTKEY1                     746
#define IDC_HOTKEY2                     747
#define IDC_HOTKEY3                     748
#define IDC_HELP_BTN                    749
#define IDC_NUM1                        750
#define IDC_NUM2                        751
#define IDC_NUM3                        752
#define IDC_NUM4                        753
#define IDC_NUM5                        754
#define IDC_NUM6                        755
#define IDC_NUM7                        756
#define IDC_NUM8                        757
#define IDC_NUM9                        758
#define IDC_NUM0                        759
#define IDC_CROSS_BTN                   760
#define IDC_MENU                        761
#define IDC_ENTER                       762
#define IDC_FUNC                        764
#define IDC_OLD_REMOTECTRL              765
#define IDC_NEW_REMOTECTRL              766
#define IDC_STATIC_OLDBACK              769
#define IDC_264_ENCODE_SET              771
#define IDC_PK_INTERVAL                 779
#define IDC_MAX_QUALITY                 780
#define IDC_MIN_QUALITY                 781
#define IDC_CHECK_BEREMOTE              782
#define IDC_STATIC_ENCRYPT              783
#define IDC_STATIC_AUTO_VERSION         784
#define IDC_ST_VERSION_INFORIGHT        785
#define IDC_STATIC_PROGRESSNOW          794
#define IDC_TRANS_PROGRESS              795
#define IDC_BTN_UPLOAD                  797
#define IDC_STATIC_TOTALPROGRESS        798
#define IDC_TOTAL_PROGRESS              800
#define IDC_STATIC_FILELIST             801
#define IDC_STATIC_LINKSTATE            802
#define IDC_STATIC_E1CHAN               803
#define IDC_BTN_ADDE1MODULE             806
#define IDC_CHECK_BIND                  807
#define IDC_EDIT_MINFRAGPACKAGELEN      808
#define IDC_EDIT_SERVERNAME             809
#define IDC_EDIT_SERVERPWD              810
#define IDC_EDIT_CLIENTNAME             811
#define IDC_EDIT_CLIENTPWD              812
#define IDC_STATIC_IP                   813
#define IDC_STATIC_MASK                 814
#define IDC_STATIC_MINFRAGPACKAGELEN    815
#define IDC_STATIC_SERVERNAME           816
#define IDC_STATIC_SERVERPWD            817
#define IDC_STATIC_CLIENTNAME           818
#define IDC_STATIC_CLIENTPWD            819
#define IDC_BTN_CFGE1_1                 820
#define IDC_BTN_CFGE1_2                 821
#define IDC_STATIC_PROTOCOL             822
#define IDC_BTN_CFGE1_3                 822
#define IDC_RADIO_PPP                   823
#define IDC_BTN_CFGE1_4                 823
#define IDC_RADIO_HDLC                  824
#define IDC_STATIC_REQTIMEINTERVAL      825
#define IDC_STATIC_MAXRESENDNUM         826
#define IDC_EDIT_MAXRESENDNUM           827
#define IDC_EDIT_REQTIMEINTERNAL        828
#define IDC_STATIC_TOTALTIMESLICE       829
#define IDC_IPADDRESS_IP                830
#define IDC_STATIC_TIMESLICESELECTED    830
#define IDC_STATIC_TIMESLOTSELECTED     830
#define IDC_STATIC_AVAILABLE            831
#define IDC_STATIC_TIME                 831
#define IDC_STATIC_AUTHENTIFY           832
#define IDC_BTN_CANCELCFG               833
#define IDC_BTN_SELECT                  835
#define IDC_LIST_TIMESLICESELECTED      837
#define IDC_LIST_TIMESLICE              838
#define IDC_LIST_E1MODULE               839
#define IDC_EDIT_ROUTEPRI               840
#define IDC_IPADDRESS_DESTNET           841
#define IDC_STATIC_DESTNET              842
#define IDC_BTN_EDITE1MODULE            843
#define IDC_BTN_DELE1MODULE             844
#define IDC_STATIC_GATEWAY              844
#define IDC_BTN_CFGROUTE                845
#define IDC_STATIC_ROUTEPRI             845
#define IDC_STATIC_ROUTE                846
#define IDC_BTN_DELE1CHAN               846
#define IDC_STATIC_ROUTEPRI2            847
#define IDC_STATIC_E1MODULEINFO         848
#define IDC_CHECK_E1MODULE1             850
#define IDC_CHECK_E1MODULE2             851
#define IDC_CHECK_E1MODULE4             852
#define IDC_CHECK_E1MODULE3             853
#define IDC_STATIC_E1MODULEFRAME        854
#define IDC_LIST_TIMESLOT               855
#define IDC_DIVISION_ST                 860
#define IDC_CHK_DHCP                    862
#define IDC_CHK_DHCP1                   862
#define IDC_CHK_PPPOE                   863
#define IDC_CHK_PPPOE1                  863
#define IDC_EDIT_PPPOEUSER              864
#define IDC_EDIT_PPPOEUSER1             864
#define IDC_EDIT_PPPoEPWD               865
#define IDC_EDIT_PPPoEPWD2              865
#define IDC_CHK_AUTOPIP                 873
#define IDC_CHK_CONFTIME                875
#define IDC_CHK_SYSTIME                 876
#define IDC_CHK_AUTOCALL                878
#define IDC_EDIT_AUTOCALL               879
#define IDC_EDIT_CALLSPEED              880
#define IDC_EDIT_WAITTIME               881
#define IDC_CHK_SWITCHTOMONITMT         883
#define IDC_EDIT_WAITTIMEFORMON         884
#define IDC_BUTTON_ADVANCE_CFG          885
#define IDC_CHK_SLEEP                   886
#define IDC_STATIC_WAITTIME             890
#define IDC_EDIT_MTALIAS                891
#define IDC_EDIT_MTE164                 892
#define IDC_EDIT_DETECTTIME             893
#define IDC_COMBO_PRIORVIDEO            899
#define IDC_COMBO_PRIORAUDIO            900
#define IDC_COMBO_PRIORCIF              901
#define IDC_RADIO_ENCRYDES              902
#define IDC_RADIO_H239AUTO              903
#define IDC_RADIO_H239CLOSE             904
#define IDC_IP_NETKEEP                  905
#define IDC_STATIC_ENCRYMODE            906
#define IDC_STATIC_H239                 907
#define IDC_EDIT_ETHUPBAND              908
#define IDC_EDIT_ETHDOWNBAND            909
#define IDC_EDIT_SNMP_PUBLIC            911
#define IDC_EDIT_PPPOE_USER             913
#define IDC_EDIT_PPPOE_PWD              914
#define IDC_CHK_ASSIGNBAND              918
#define IDC_IP_SNMP_ADDR                920
#define IDC_IP_ETHADDR                  921
#define IDC_CHK_NAPMAP                  924
#define IDC_CHK_FIREWALL_PROXY          925
#define IDC_EDIT_PROXY_LISTENPORT       926
#define IDC_EDIT_PROXY_STARTPORT        927
#define IDC_IP_NAPMAP_ADDR              929
#define IDC_CHK_SHOWSTATE               930
#define IDC_STATIC_MONADVANCE           931
#define IDC_STATIC_OSDBMP               932
#define IDC_STATIC_ETHNET               933
#define IDC_STATIC_PPPOE                934
#define IDC_STATIC_SNMP                 935
#define IDC_COMBO_OSDSHOW               937
#define IDC_COMBO_SHOWMODE              938
#define IDC_COMBO_ANSWER                939
#define IDC_STATIC_SHOW                 940
#define IDC_EDIT_PORTINDEX              941
#define IDC_STATIC_SERIAL               947
#define IDC_EDIT_QOS_SIGNAL             950
#define IDC_EDIT_QOS_DATA               951
#define IDC_EDIT_QOS_AUDIO              952
#define IDC_EDIT_QOS_VIDEO              953
#define IDC_COMBO_QOS_TOS               954
#define IDC_EDIT_QOS_SIGNAL2            955
#define IDC_EDIT_QOS_DATA2              956
#define IDC_EDIT_QOS_AUDIO2             957
#define IDC_EDIT_QOS_VIDEO2             958
#define IDC_EDIT_QUALMAXVALUE           959
#define IDC_EDIT_QUALMINVALUE           960
#define IDC_EDIT_IKEYRATE               961
#define IDC_COMBO_ENCODEMODE            962
#define IDC_COMBO_RESTORETYPE           963
#define IDC_CHECK_USEDFIXEDFRAME        965
#define IDC_EDIT_FRAMERATE              966
#define IDC_COMBO_FARAMUNIT             967
#define IDC_EDIT_MODEL                  970
#define IDC_EDIT_INPORT_NUM             971
#define IDC_EDIT_OUTPORT_NUM            972
#define IDC_COMBO_CTRLTYPE              973
#define IDC_COMBO_VSTANDRAD             974
#define IDC_CHK_LOCALVIDEO              975
#define IDC_EDIT_TTL                    976
#define IDC_STATIC_TTL                  977
#define IDC_STATIC_CALLMODE             978
#define IDC_STATIC_GKREG                979
#define IDC_STATIC_PRIOM_SEND_AUDIO     980
#define IDC_STATIC_PRIOM_REC_AUDIO      981
#define IDC_STATIC_PRIOM_SEND_VIDEO     982
#define IDC_STATIC_PRIOM_REV_VIDEO      983
#define IDC_STATIC_PRIOM_SEND_CIF       984
#define IDC_STATIC_PRIOM_REV_CIF        985
#define IDC_STATIC_PRIOM_SEND_RATE      986
#define IDC_STATIC_PRIOM_REV_RATE       987
#define IDC_STATIC_PRIOM_SEND_ENCRY     988
#define IDC_STATIC_PRIOM_REV_ENCRY      989
#define IDC_STATIC_SECOND_SEND_AUDIO    990
#define IDC_STATIC_SECOND_REV_AUDIO     991
#define IDC_STATIC_SECOND_SEND_VIDEO    992
#define IDC_STATIC_SECOND_REV_VIDEO     993
#define IDC_STATIC_SECOND_SEND_CIF      994
#define IDC_STATIC_SECOND_REV_CIF       995
#define IDC_STATIC_SECOND_SEND_RATE     996
#define IDC_STATIC_SECOND_REV_RATE      997
#define IDC_STATIC_SECOND_SEND_ENCRY    998
#define IDC_STATIC_SECOND_REV_ENCRY     999
#define IDC_STATIC_PRIOM                1000
#define IDC_STATIC_SECOND               1001
#define IDC_STATIC_CODECINFO            1003
#define IDC_BTN_BKCOLOR                 1006
#define IDC_STATIC_SINGAL               1007
#define IDC_STATIC_DATA                 1008
#define IDC_STATIC_AUDIO                1009
#define IDC_STATIC_VIDEO                1010
#define IDC_EDIT_SMS_ROOLTIME           1011
#define IDC_COMBO_SMS_ROLLSPEED         1012
#define IDC_EDIT_SMS_LINES              1013
#define IDC_STATIC_SMS_ADVANCE          1014
#define IDC_STATIC_SMS_TYPE             1015
#define IDC_STATIC_SMS_ROLLSPEED        1016
#define IDC_STATIC_SMS_ROLLTIME         1017
#define IDC_STATIC_SMS_LINES            1018
#define IDC_CONNECT_USER2               1019
#define IDC_CONNECT_PWD2                1020
#define IDC_EDIT_LOGOCONTENT            1021
#define IDC_BTN_FONT                    1022
#define IDC_STATIC_LOGOPREVIEW          1023
#define IDC_STATIC_BKCOLOR              1025
#define IDC_BTN_LOADBITMAP              1028
#define IDC_STATIC_LOGO                 1029
#define IDC_EDIT_BITMAP_XPOS            1030
#define IDC_EDIT_BITMAP_YPOS            1031
#define IDC_CHK_RECORDPWD               1034
#define IDC_CHK_AUTOLOGIN               1035
#define IDC_STATIC_CURAPPLY_SCHEME      1037
#define IDC_CHK_ENABLE_BANNER2          1038
#define IDC_COMBO_BANNER_SN             1039
#define IDC_EDIT_IP_PORT                1040
#define IDC_BTN_EXMATRIX_SCHEME         1041
#define IDC_IP_SERIAL_TCPIP             1044
#define IDC_STATIC_MATRIXTYPE           1045
#define IDC_STATIC_INPORT_NUM           1046
#define IDC_STATIC_OUTPORT              1047
#define IDC_STATIC_INPUT_NUM            1050
#define IDC_EDIT_OUTNAME                1051
#define IDC_EDIT_UDP                    1052
#define IDC_STATIC_FIREWALL             1053
#define IDC_STATIC_NATMAP               1054
#define IDC_STATIC_UDP                  1055
#define IDC_STATIC_LOGOTEXT             1056
#define IDC_STATIC_INVOL                1057
#define IDC_STATIC_OUTVOL               1058
#define IDC_SLIDER_PLAYTIME             1061
#define IDC_BTN_STEPIN                  1062
#define IDC_BTN_STEPOUT                 1063
#define IDC_BTN_LOGIN                   1064
#define IDC_SLIDER_PLAYVOLUM            1065
#define IDC_BTN_STOP                    1066
#define IDC_STATIC_FILENAME             1067
#define IDC_STATIC_FILESIZE             1068
#define IDC_STATIC_RECORDTIME           1069
#define IDC_STATIC_TOTALTIME            1070
#define IDC_EDIT_LOGINPORT              1071
#define IDC_EDIT_USERNAME               1072
#define IDC_EDIT_LOGINPWD               1073
#define IDC_IP_VODSERVER                1076
#define IDC_STATIC_PLAYTIME             1078
#define IDC_BTN_QUITE                   1079
#define IDC_TAB_VPARAM                  1081
#define IDC_EDIT_EXMATRIXPORT           1082
#define IDC_IP_EXMATRIX                 1083
#define IDC_CHK_STATRRETRANS            1084
#define IDC_EDIT_FIRSTTIMESPAN          1085
#define IDC_EDIT_THIRDTIMESPAN          1086
#define IDC_EDIT_SECONDTIMESPAN         1087
#define IDC_EDIT_REJECTTIMESPAN         1088
#define IDC_EDIT_SENDBUFTIME            1089
#define IDC_STATIC_LOST                 1090
#define IDC_MY_APPLY                    20041
#define IDC_MY_CANCEL                   20042
#define IDC_MY_RESET                    20043
#define IDM_APPLY_CHAIRMAN              32768
#define IDM_SPEC_CHAIRMAN               32769
#define IDM_CANCEL_CHAIRMAN             32770
#define IDM_APPLY_SPEAKER               32771
#define IDM_SPEC_SPEAKER                32772
#define IDM_CANCEL_SPEAK                32773
#define IDM_SELECT_MT                   32774
#define IDM_START_POLL                  32775
#define IDM_POLL_STOP                   32776
#define IDM_POLL_PAUSE                  32777
#define IDM_RESUME_POLL                 32778
#define IDM_START_DISCUSS               32779
#define IDM_DISCUSS_STOP                32780
#define IDM_MCS_SPECIFY                 32781
#define IDM_FOLLOW_SPEAKER              32782
#define IDM_FOLLOW_CHAIRMAN             32783
#define IDM_FOLLOW_POLL                 32784
#define IDM_STOP_VMP                    32785
#define IDM_VMP                         32786
#define IDM_CONF_EXPAND                 32787
#define IDM_CONF_CASCADE                32788
#define IDM_DEL_PIC                     32789
#define IDM_INVITE_MT                   32790
#define IDM_DELETE_MT                   32791
#define IDM_KEYFRAME_PLAY               32792
#define IDM_FULLSCREEN                  32793
#define IDM_PIP                         32794
#define IDM_VAC                         32795
#define IDM_APPLY_CHIME                 32796
#define IDM_HELP_DOC                    32797
#define IDM_VERSION                     32798
#define IDM_MT_SILENT                   32799
#define IDM_MT_DUMMY                    32800
#define IDM_EDITCTRL_CLEAR              32802
#define IDM_SLEEP_IMMEDIATELY           32803
#define IDM_SLEEP_60                    32804
#define IDM_SLEEP_120                   32805
#define IDM_SLEEP_180                   32806
#define IDM_SLEEP_NEVER                 32807
#define IDM_DUAL_PC                     32808
#define IDM_DUAL_VGA                    32809
#define IDM_DUAL_VIDEO                  32810
#define IDM_LANGUAGE_EN                 32811
#define IDM_LANGUAGE_CN                 32812


//接口宏定义

//SHEET页面宏定义
#define SHEET_CONF_MANAGE   1
#define SHEET_DEVICE_MANAGE 2
#define SHEET_CONFIG_MANAGE 3
#define SHEET_SYSTEM_MANAGE 4
#define SHEET_DETECT_MANAGE 5

//tab页宏
enum emTabIndex
{
	CFG_USER = 0,
	CFG_CAPTION,  
	CFG_H323,	
    CFG_ETHNET,
	CFG_FIREWALL,
	CFG_RESEND,         
	CFG_AUDIO,
	CFG_VIDEO,
	CFG_CAMERA,
	CFG_QOS,
	CFG_MATRIX,
	CFG_TVOUT,
	CFG_SERIALPORT,
	CFG_E1CHAN,
	CFG_ROUTE
};







//呼叫类型宏定义
#define CAll_TYPE_IP        1
#define CALL_TYPE_E164      2
#define CAll_TYPE_H323ID    3

//图像测试类型
#define IMAGE_TEST_LOCAL    1
#define IMAGE_TEST_REMOTE   2
#define IMAGE_TEST_ALL      3
