#ifndef PCMTGUITESTLIBDEFINE_H
#define PCMTGUITESTLIBDEFINE_H

typedef struct tagOtherCfg
{
	BOOL32 bAutoMonitorChairman;
	BOOL32 bStartMinimize;
	BOOL32 bConfigNeedPwd;
	BOOL32 bShowLabel;
}TOTHERCFG;

//界面索引
const s32 UIVIEW_VC_BROADCASTWND = 0;
const s32 UIVIEW_VC_SIMROOM = 1;
const s32 UIVIEW_DC_SHARE = 2;
const s32 UIVIEW_DC_WHITEBOARD = 3;
const s32 UIVIEW_VC_MONITOR = 4;

//菜单
//非主席、发言人
const s32 MENU_NOCHAIR_APPLYSPEAKER =0;
const s32 MENU_NOCHAIR_APPLYCHIME = 1;
const s32 MENU_NOCHAIR_APPLYCHAIR = 2;
const s32 MENU_NOCHAIR_EXITCONF = 3;
const s32 MENU_NOCHAIR_SENDMESSAGE = 4;
//                                      5
const s32 MENU_CHAIR_CANCELSPEAKER = 6;              //取消发言
const s32 MENU_CHAIR_CANCELCHAIR = 7;              //取消主席
const s32 MENU_CHAIR_LOOPLOOK = 8;              //轮询
const s32 MENU_CHAIR_EXTENDCONF = 9;              //
const s32 MENU_CHAIR_SETCONFMODE = 10;             //讨论模式
const s32 MENU_CHAIR_CONF_VAC = 11;             //语音激励
const s32 MENU_CHAIR_CONF_VMPER = 12;              //画面合成
const s32 MENU_CHAIR_INVITEMT = 13;              //邀请终端
const s32 MENU_CHAIR_RELEASECONF = 14;              //结束会议

//主席、非自己
const s32 MENU_CHAIR_OSELECTMT = 0;              //选看终端 
const s32 MENU_CHAIR_OSPECIFYCHAIR = 3;              //指定主席                                     
const s32 MENU_CHAIR_OSPECIFYSPEAKER = 4;             //指定发言
const s32 MENU_CHAIR_OCANCELSPEAKER = 5;              //取消发言
const s32 MENU_CHAIR_OREMOTESILENT = 7;              //静音
const s32 MENU_CHAIR_OREMOTEDUMMY = 8;              //哑音
const s32 MENU_CHAIR_OREVOKEMT = 13;             //清退终端

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WebPCMT.rc
//
#define IDS_WEBPCMT                     1
#define IDD_ABOUTBOX_WEBPCMT            1
#define IDB_WEBPCMT                     1
#define IDI_ABOUTDLL                    1
#define IDS_WEBPCMT_PPG                 2
#define IDOK2                           2
#define ID_BUTTON_STOP_VMP              3
#define IDC_BTN_ADDRBOOK                3
#define IDC_BTN_SETPWD                  3
#define ID_BUTTON_START_VMP             4
#define IDC_BTN_HELP                    4
#define IDC_BTN_MONITORPANEL            5
#define IDC_BTN_DATACONF                6
#define IDS_WEBPCMT_PPG_CAPTION         200
#define IDD_PROPPAGE_WEBPCMT            200
#define IDD_DIALOG_MAINFRAME            201
#define IDD_DIALOG_MAINBROADCASTWND     202
#define IDD_DIALOG_PCMTCONF             203
#define IDD_DIALOG_PCMTP2P              204
#define IDD_DIALOG_PCMTSMS              205
#define IDC_STATIC_PCMTVCC              205
#define IDD_DIALOG_PCMTMMC              206
#define IDC_STATIC_PCMTP2P              206
#define IDD_DIALOG_PCMTMONITOR          206
#define IDC_STATIC_PCMTAVC              207
#define IDC_STATIC_PCMTMAINSHEET        207
#define IDC_STATIC_PCMTSMS              208
#define IDB_LISTMTGROUP                 208
#define IDC_STATIC_PCMTMMC              209
#define IDR_MENU_CONF                   209
#define IDC_LIST_MT                     210
#define IDR_MENU_EDIT                   210
#define IDC_CREATE_CONF                 211
#define IDD_DIALOG_PCMTARC              211
#define IDD_DIALOG_PCMTSIMROOM          211
#define IDC_BTN_CREATECONF              211
#define IDC_RELEASE_CONF                212
#define IDB_ARMTLIST                    212
#define IDC_BTN_ENDCONF                 212
#define IDC_APPLY_JOIN                  213
#define IDD_DIALOG_PCMTMMP              213
#define IDC_BTN_APPLYCHIMEIN            213
#define IDD_DIALOG_PCMTMONITORPANEL     213
#define IDC_INVITE_MT                   214
#define IDR_MENU_MMC                    214
#define IDC_BTN_INVITEMT                214
#define IDR_MENU_MMP                    215
#define IDC_BTN_MAKECALL                215
#define IDR_MENU_HIDE                   216
#define IDC_BTN_APPLYSPEAK              216
#define IDC_COMBO_ADDRBOOK              217
#define IDD_DIALOG_AUTOCLOSE            217
#define IDC_BTN_APPLYCHAIRMAN           217
#define IDC_CALLOUT_HANGUP              218
#define IDD_DIALOG_CODECINFO            218
#define IDC_BTN_APPLYJOIN               218
#define IDC_RICHEDIT_MSGRECEIVED        219
#define IDD_DIALOG_NOTIFYMSG            219
#define IDC_REDIT_MSGRECEIVED           219
#define IDC_BTN_QUITCONF                219
#define IDC_COMBO_RECEIVER              220
#define IDD_DIALOG_ANSWER               220
#define IDD_DIALOG_ANSWERAPPLY          220
#define IDC_EDIT_SHORTMSG               221
#define IDC_SEND_MESSAGE                222
#define IDC_CURSOR1                     222
#define IDC_BTN_SENDMESSAGE             222
#define IDC_CONFIGURATION               223
#define IDC_VIDEOCONF                   224
#define IDD_DIALOG_ADDRBOOK             224
#define IDC_DATACONF                    225
#define IDC_ASSEMBLYROOM                226
#define IDC_MEETINGMONITOR              227
#define IDC_PCMTHELP                    228
#define IDC_STATIC_PLAYWND              229
#define IDD_DIALOG_APPLYJOIN            229
#define IDC_LIST_PLAYWND                229
#define IDC_MUTE                        230
#define IDC_CHK_MUTE                    230
#define IDC_PLAY_VOLUME                 231
#define IDC_SLIDER_PLAYVOLUME           231
#define IDC_DUMB                        232
#define IDD_DIALOG_INVITEMT             232
#define IDC_CHK_DUMB                    232
#define IDC_CAPTURE_VOLUME              233
#define IDR_MENU_VIDEO                  233
#define IDC_SLIDER_CAPTUREVOLUME        233
#define IDC_AVCONFIG                    234
#define IDD_DELAYCONF                   234
#define IDC_BTN_AVCONFIG                234
#define IDC_STATISTIC                   235
#define IDD_DIALOG_FULLSCREEN           235
#define IDC_BTN_STATISTIC               235
#define IDC_FULLSCREEN                  236
#define IDC_SNAPSHOT                    237
#define IDD_DIALOG_ENDPROMPT            237
#define IDC_BTN_SNAPSHOT                237
#define IDC_RECORD                      238
#define IDD_AUDIO_CONFIG                238
#define IDC_STATIC_AVSOURCE             239
#define IDD_CAMERACONFIG                239
#define IDC_STATIC_CONFVIDEO            240
#define IDD_CALLCONFIG                  240
#define IDD_DIALOG_CALLCFG              240
#define IDC_STATIC_PREVIEW              241
#define IDR_MENU_P2P                    241
#define IDC_STATIC_SELFVIDEO            242
#define IDD_DIALOG_CONFIG               242
#define IDC_STATIC_MMSOURCE1            243
#define IDC_STATIC_NAMESOURCE1          243
#define IDC_STATIC_MMSOURCE2            244
#define IDC_STATIC_NAMESOURCE2          244
#define IDC_STOP_MMSOURCE1              245
#define IDD_PROMPT                      245
#define IDC_STOP_MMSOURCE2              246
#define IDD_CALLED_RECORD               246
#define IDC_MMC_SOURCE1                 247
#define IDC_STATIC_SOURCE1              247
#define IDC_STATIC_SOURCE10             247
#define IDC_MMC_SOURCE2                 248
#define IDD_SNAP_SHOT                   248
#define IDC_STATIC_SOURCE2              248
#define IDC_LIST_PLATFORM               249
#define IDD_ERR_MSG                     249
#define IDC_LIST_AUDIENCE               250
#define IDC_SHOWAS_1X1                  251
#define IDB_SCROLLBAR_TOP               251
#define IDD_DIALOG_CREATECONF           251
#define IDC_SHOWAS1                     251
#define IDC_SHOWAS_2X2                  252
#define IDB_SCROLLBAR_UPARROW           252
#define IDC_SHOWAS4                     252
#define IDC_SHOWAS_3X3                  253
#define IDB_SCROLLBAR_SPAN              253
#define IDC_SHOWAS9                     253
#define IDC_SHOWAS_4X4                  254
#define IDC_STATIC_MMC00                255
#define IDB_SCROLLBAR_DOWNARROW         255
#define IDC_STATIC_MMC01                256
#define IDB_SCROLLBAR_THUMB             256
#define IDC_STATIC_MMC02                257
#define IDB_COLUMNHEADER_START          257
#define IDC_STATIC_MMC03                258
#define IDB_COLUMNHEADER_SPAN           258
#define IDC_STATIC_MMC04                259
#define IDB_COLUMNHEADER_END            259
#define IDC_STATIC_MMC05                260
#define IDB_DIALOG_HEAD                 260
#define IDC_STATIC_MMC06                261
#define IDB_BTN_AVC_1                   261
#define IDC_STATIC_MMC07                262
#define IDB_BTN_AVC_2                   262
#define IDC_STATIC_MMC08                263
#define IDB_BTN_ARC_2                   263
#define IDC_STATIC_MMC09                264
#define IDB_BTN_ARC_1                   264
#define IDC_STATIC_MMC10                265
#define IDB_BTN_HELP_2                  265
#define IDC_STATIC_MMC11                266
#define IDB_BTN_HELP_1                  266
#define IDC_STATIC_MMC12                267
#define IDB_HEAD_LINE_LEFT              267
#define IDC_STATIC_MMC13                268
#define IDB_HEAD_LINE_RIGHT             268
#define IDC_STATIC_MMC14                269
#define IDB_BTN_MMP_1                   269
#define IDC_STATIC_MMC15                270
#define IDB_BTN_MMP_2                   270
#define IDC_EXIT                        271
#define IDB_BTN_DC_1                    271
#define IDC_SHOWAS2                     271
#define IDB_BTN_DC_2                    272
#define IDC_SHOWAS6                     272
#define IDC_BTN_VIEWONE                 272
#define IDC_COMBO1                      273
#define IDC_COMBO_Mt                    273
#define IDC_COMBO_VSOURCE               273
#define IDB_BTN_CONFIG_1                273
#define IDC_CALL_TYPE                   273
#define IDC_CB_TYPE                     273
#define IDC_CAPTURE_TYPE_COMBO          273
#define IDC_COMBO_MERGEMODE             273
#define IDC_COMBO_MODE                  273
#define IDC_SHOWAS8                     273
#define IDC_COMBO_RESOLUTION            273
#define IDC_COMBO_SERVERIP              273
#define IDC_COMBO_GROUP                 273
#define IDC_COMBO_CAPTURETYPE           273
#define IDC_MT_TO_INSPECT               273
#define IDC_BTN_VIEWTWO                 273
#define IDC_COMBO_ASOURCE               274
#define IDB_BTN_CONFIG_2                274
#define IDC_COMBO_AUDIOFORMAT           274
#define IDC_INSPECT_TYPE                274
#define IDC_BTN_VIEWFOUR                274
#define IDC_COMBO2                      274
#define IDC_COMBO_ENCODEMODE            274
#define IDC_LIST_ADDRBOOK               275
#define IDC_COMBO_VFORMAT               275
#define IDC_COMBO_VIDEOFORMAT           275
#define IDC_BTN_VIEWSIX                 275
#define IDC_BUTTON_ADD                  276
#define IDC_COMBO_VSYSTEM               276
#define IDB_HEADBAR_BACKGROUND          276
#define IDC_STATIC_MESSAGE              276
#define IDC_BTN_VIEWEIGHT               276
#define IDC_COMBO_LOSTPACKAGERESTORE    276
#define IDC_BUTTON_MODIFY               277
#define IDC_COMBO_VRESOLUTION           277
#define IDB_HEAD_ICON                   277
#define IDC_BTN_VIEWNINE                277
#define IDC_BUTTON_SAVE                 278
#define IDC_COMBO_VCOMPRESS             278
#define IDB_BTN_CONFIG_3                278
#define IDC_BUTTON_MODIFYGROUP          278
#define IDC_BUTTON_DELETE               279
#define IDC_COMBO_AFORMAT               279
#define IDB_BTN_ARC_3                   279
#define IDC_EDIT_ENTRYNAME              280
#define IDC_COMBO_VFORMAT_DEC           280
#define IDB_BTN_AVC_3                   280
#define IDC_EDIT_MTALIAS                281
#define IDC_COMBO_AFORMAT_DEC           281
#define IDB_BTN_MMP_3                   281
#define IDB_BTN_DC_3                    282
#define IDC_EDIT_MTNUMBER               283
#define IDB_BTN_HELP_3                  283
#define IDC_EDIT_CALLRATE               284
#define IDB_BTN_SPEAKER_1               284
#define IDC_BUTTON_EXIT                 285
#define IDB_BTN_SPEAKER_2               285
#define IDC_BUTTON_SEARCH               285
#define IDC_IPADDRESS                   286
#define IDB_BTN_SPEAKER_3               286
#define IDB_BTN_MICPHONE_1              287
#define IDB_BTN_MICPHONE_2              288
#define IDC_BUTTON_SEARCH2              288
#define IDB_BTN_MICPHONE_3              289
#define IDB_BTN_AVCONFIG_1              290
#define IDD_DIALOG_POLLMT               291
#define IDB_BTN_AVCONFIG_2              291
#define IDC_LIST_ALLCONF                292
#define IDB_BTN_AVCONFIG_3              292
#define IDC_EDIT_CONFID                 293
#define IDB_BTN_FULLSCREEN_1            293
#define IDB_BTN_FULLSCREEN_2            294
#define IDC_EDIT_CONFRADE               294
#define IDB_BTN_FULLSCREEN_3            295
#define IDB_BTN_SHOOT_1                 296
#define IDB_BTN_SHOOT_2                 297
#define IDC_LIST_ALLMT                  298
#define IDB_BTN_SHOOT_3                 298
#define IDB_BTN_STAT_1                  299
#define IDC_INVITEBOOK                  300
#define IDB_BTN_STAT_2                  300
#define IDB_BTN_STAT_3                  301
#define IDC_AUDIO                       302
#define IDB_BTN_SNATCH_1                302
#define IDC_VIDEO                       303
#define IDB_BTN_SNATCH_2                303
#define IDC_DELAYTIME                   304
#define IDB_BTN_SNATCH_3                304
#define IDC_PREVIEW                     305
#define IDB_BTN_SLIDER_3                305
#define IDC_PIC_PREVIEW                 305
#define IDB_BTN_SLIDER_2                306
#define IDC_STATIC_TIP                  307
#define IDB_BTN_SLIDER_1                307
#define IDB_HEAD_ICON2                  308
#define IDC_STATIC_PROMPT               309
#define IDB_BTN_CALLOUT_3               309
#define IDC_IPADDRESS_IP                310
#define IDB_BTN_CALLOUT_2               310
#define IDD_DIALOG_SENDSHORTMSG         311
#define IDB_BTN_CALLOUT_1               311
#define IDC_IPADDRESS_GWMASK            312
#define IDB_BTN_CALLDOWN_1              312
#define IDC_IPADDRESS_GW                313
#define IDC_LIST_REFUSED                313
#define IDB_BTN_CALLDOWN_2              313
#define IDC_IPADDRESS_GK                314
#define IDC_LIST_CALLEDOUT              314
#define IDC_EDIT_PORT                   314
#define IDB_BTN_CALLDOWN_3              314
#define IDC_IPADDRESS_AUTOCALL          315
#define IDB_BTN_SENDSMS_3               315
#define IDC_IP_AUTOCALL                 315
#define IDB_BTN_SENDSMS_2               316
#define IDB_BTN_SENDSMS_1               317
#define IDB_BTN_ONESCREEN_3             318
#define IDB_BTN_1SCREEN_3               318
#define IDB_BTN_ONESCREEN_2             319
#define IDB_BTN_1SCREEN_2               319
#define IDB_BTN_ONESCREEN_1             320
#define IDB_BTN_1SCREEN_1               320
#define IDB_BTN_4SCREEN_3               321
#define IDB_BTN_4SCREEN_2               322
#define IDB_BTN_4SCREEN_1               323
#define IDC_STATIC_MAIN                 324
#define IDB_BTN_9SCREEN_3               324
#define IDC_BUTTON_MT                   325
#define IDB_BTN_9SCREEN_2               325
#define IDC_BUTTON_VIDEO                326
#define IDB_BTN_9SCREEN_1               326
#define IDC_BUTTON_P2P                  327
#define IDB_BTN_16SCREEN_3              327
#define IDC_BUTTON_CAM                  328
#define IDB_BTN_16SCREEN_2              328
#define IDC_BUTTON_ADDR                 328
#define IDC_IPADDRESS_LOCAL             329
#define IDB_BTN_16SCREEN_1              329
#define IDC_COMBO_ANSWERTYPE            330
#define IDB_LINE_BACK                   330
#define IDC_COMBO_CALL_TYPE             331
#define IDB_BACKGROUND_MMP              331
#define IDC_COMBO_CALLTYPE              331
#define IDC_LIST_ANSWERED               332
#define IDC_COMBO_ENCRYPTMODE           332
#define IDC_COMBO_TYPE                  333
#define IDB_PLAINT_ICON                 333
#define IDC_ISOVERLAY                   334
#define IDD_CALL_MCU                    334
#define IDD_DIALOG_CALL                 334
#define IDC_RADIO_NOOVERLAY             335
#define IDB_BTN_CREATE_CONF_4           335
#define IDC_EDIT_AVOLUMN_DEC            336
#define IDB_BTN_CREATE_CONF_2           336
#define IDC_EDIT_ADECVOLUMN             336
#define IDB_BTN_CREATE_CONF_3           337
#define IDB_BTN_CREATE_CONF_1           338
#define IDC_BUTTON_BACK                 339
#define IDB_BTN_APPLY_JOIN_4            339
#define IDC_SAYNO                       340
#define IDB_BTN_APPLY_JOIN_2            340
#define IDC_PROMPT_CONTENT              341
#define IDB_BTN_APPLY_JOIN_3            341
#define IDB_BTN_APPLY_JOIN_1            342
#define IDC_SELMT_STATIC                342
#define IDB_BTN_INVITE_JOIN_4           343
#define IDC_INSPECTMODE_STATIC          343
#define IDC_RADIO_CAMERA1               344
#define IDB_BTN_INVITE_JOIN_2           344
#define IDC_RADIO_CAMERA2               345
#define IDB_BTN_INVITE_JOIN_3           345
#define IDC_RADIO_CAMERA3               346
#define IDB_BTN_INVITE_JOIN_1           346
#define IDC_RADIO_CAMERA4               347
#define IDB_BTN_END_CONF_4              347
#define IDC_RADIO_LOCAL_DEVICE          348
#define IDB_BTN_END_CONF_2              348
#define IDC_RADIO_REMOTE_DIVCE          349
#define IDB_BTN_END_CONF_3              349
#define IDB_BTN_END_CONF_1              350
#define IDB_BTN_ARC_4                   351
#define IDB_BTN_MMP_4                   352
#define IDC_BUTTON_AUDIO                353
#define IDB_BTN_SHOOT_4                 353
#define IDC_BTN_SAVE                    354
#define IDB_BTN_FULLSCREEN_4            354
#define IDC_BTN_DELETE                  355
#define IDB_BTN_SNATCH_4                355
#define IDC_BTN_SEND                    356
#define IDB_BTN_MUTE                    356
#define IDC_LIST_RECORD                 357
#define IDB_BTN_DUMP                    357
#define IDD_STOP_POLL                   358
#define IDD_MEETING_GROUP               359
#define IDC_STATIC_NOTIFYMSG            360
#define IDD_GROUP_INFO                  360
#define IDC_ERRMSG                      361
#define IDD_CONFIG_ADDR                 361
#define IDC_BTN_ADDRESSBOOK             362
#define IDC_BTN_HISTORY                 363
#define IDC_IP_LOCAL_MASK               364
#define IDC_IP_LOCAL                    365
#define IDC_CLOSE                       365
#define IDC_IP_GW                       366
#define IDI_WEBPCMT_ICON                366
#define IDC_IP_LOCAL2                   366
#define IDC_IP_GW_MASK                  367
#define IDB_BTN_CLOSE2                  367
#define IDB_BTN_CLOSE1                  368
#define IDC_IP_GK                       369
#define IDD_TRANSFER_AGAIN              369
#define IDD_DIALOG_SENDRECVRESENDCFG    369
#define IDB_BTN_GUANBI1                 370
#define IDC_DECODER_INFO                371
#define IDB_BTN_GUANBI2                 371
#define IDC_ADDRESS_BOOK                372
#define IDB_BTN_DUMP2                   372
#define IDC_EDIT_MCUID                  373
#define IDC_EDIT_MCU_INFO               373
#define IDB_BTN_DUMP3                   373
#define IDC_EDIT_MCUINFO                373
#define IDD_DIALOG_MTCFG                374
#define IDB_BTN_MUTE2                   374
#define IDD_DIALOG_LOCALCFG             374
#define IDC_STATIC_CONFNAME             375
#define IDB_BTN_MUTE3                   375
#define IDD_P2P_INVITE                  376
#define IDC_STATIC_MCUID                376
#define IDC_STATIC_DISPLAYCONFNAME      376
#define IDD_VMPER                       377
#define IDC_STATIC_DCCONFNAME           377
#define IDD_DIALOG_VMP                  377
#define IDD_DIALOG_DATACONF             378
#define IDC_ENTRY_LIST                  378
#define IDC_CHECK1                      379
#define IDC_CHECK_USEGK                 379
#define IDC_TRSAGAIN_SEND_CHB           379
#define IDC_CHECKBROADCAST              379
#define IDD_CONF_PASSWORD               379
#define IDC_CHECK_SELFTEST              379
#define IDC_CHECK_PSW                   379
#define IDC_CHECK_LOGO                  379
#define IDC_CHECK_START                 379
#define IDC_CHECK_SAVE                  379
#define IDC_CHECK_ANONYMOUS             379
#define IDC_CHK_DCCONF                  379
#define IDC_CHK_SELFTEST                379
#define IDC_CHK_PSW                     379
#define IDC_ENTRY_LIST2                 379
#define IDC_CHK_LOGO                    379
#define IDC_CHK_USEGK                   379
#define IDC_CHK_START                   379
#define IDC_CHK_SEND                    379
#define IDD_DIALOG_CONFPSW              379
#define IDC_CHK_AUTOPIP                 379
#define IDC_CHK_DHCP                    379
#define IDC_CHK_ENABLE                  379
#define IDC_CHK_USEFIXFRAME             379
#define IDB_BTN_DC_CONNECT              380
#define IDC_CHECK_PASSWORD              380
#define IDC_CHK_DCPSW                   380
#define IDC_CHK_PASSWORD                380
#define IDC_CHECK2                      380
#define IDC_CHK_START2                  380
#define IDC_CHK_SHOWCONFTIME            380
#define IDC_CHK_CONFIGPWD               380
#define IDC_CHK_USERASSIGN              380
#define IDC_CHK_REMOTECTRL              380
#define IDC_CHK_FORWARD                 380
#define IDC_BUTTON1                     381
#define IDC_BTN_PAUSE                   381
#define IDC_SAVEAS_PIC                  381
#define IDC_BTN_ADD                     381
#define IDC_BTN_GROUP                   381
#define IDC_BUTTON_CALL                 381
#define IDC_BUTTON_OK                   381
#define IDC_BUTTON_PREVIEW              381
#define IDC_BUTTON_PACKED               381
#define IDC_BUTTON_NEXT                 381
#define IDC_BUTTON_FIND                 381
#define IDC_BUTTON_SHOWALL              381
#define IDC_BUTTON_ALLTO                381
#define IDC_BUTTON_HISTROY              381
#define IDC_BTN_CLOSE                   381
#define IDC_BTN_EXIT                    381
#define IDC_BTN_CONFIG                  381
#define IDC_BTN_MAINFULL                381
#define IDC_CHK_USEGK2                  381
#define IDC_CHECK3                      381
#define IDC_CHK_SHOWSYSTIME             381
#define IDC_CHK_NETPWD                  381
#define IDC_CHK_ENABLESLEEP             381
#define IDC_BTN_ADVANCECFG              381
#define IDC_CHK_GKUSE                   381
#define IDC_EDIT_MT_INFO                382
#define IDD_DISCUSS_MODE                382
#define IDC_BUTTON_NEXT2                382
#define IDC_BUTTON_TO                   382
#define IDC_EDIT_MTINFO                 382
#define IDC_CHECK4                      382
#define IDC_CHK_SHOWLABEL               382
#define IDC_CHK_AUTOCALL                382
#define IDC_CHK_H323                    382
#define IDC_MCU_CALL_TYPE               383
#define IDD_DIALOG_SELECTMTMODE         383
#define IDC_COMBO_MCUCALLTYPE           383
#define IDD_DIALOG_INSPECTMT            383
#define IDC_MT_CALL_TYPE                384
#define IDC_BUTTON_ALLBACK              384
#define IDC_COMBO_MTCALLTYPE            384
#define IDC_EDIT_CALL_INFO              385
#define IDD_DIALOG_PCMTAVR_VIDEO        385
#define IDC_CHK_FORBIDSTARTSHARE        385
#define IDC_EDIT_MCU                    386
#define IDB_BTN_8SCREEN_3               386
#define IDC_EDIT_INFORMATION            386
#define IDC_PROMPT_ICON                 387
#define IDB_BTN_2SCREEN_2               387
#define IDC_EDIT_CALLBITRATE            387
#define IDC_LIST_POLLMT                 388
#define IDB_BTN_2SCREEN_3               388
#define IDC_BTN_STOP                    389
#define IDB_BTN_6SCREEN_1               389
#define IDC_CHK_FORBIDSTARTWHITEBOARD   389
#define IDC_STATIC_INTERVAL             390
#define IDB_BTN_6SCREEN_2               390
#define IDC_CHK_FORBIDSTARTFT           390
#define IDB_BTN_6SCREEN_3               391
#define IDC_CHK_FORBIDSTARTTALK         391
#define IDC_AVSOURCE                    392
#define IDB_BTN_8SCREEN_1               392
#define IDC_LOOPLOOK                    393
#define IDB_BTN_8SCREEN_2               393
#define IDC_LOOPSPEAK                   394
#define IDB_BTN_2SCREEN_1               394
#define IDC_FILE_PATH                   395
#define IDC_PIC                         396
#define IDC_SAVE_PIC                    397
#define IDB_BTN_SELFTEST_3              397
#define IDD_VIDEO_CONFIG                398
#define IDB_BTN_STOPSELFTEST_2          398
#define IDD_DIALOG_AVCFG                398
#define IDC_STATIC_ENTRY_NAME           399
#define IDB_BTN_STOPSELFTEST_3          399
#define IDD_PACKEDCONFIG                399
#define IDD_DIALOG_PANELCFG             399
#define IDC_STATIC_ENTRYNAME            399
#define IDC_STATIC_MT_ALIASE            400
#define IDB_BTN_SELFTEST_1              400
#define IDC_STATIC_MTALIASE             400
#define IDC_STATIC_MT_IP                401
#define IDB_BTN_SELFTEST_2              401
#define IDC_STATIC_MTIP                 401
#define IDC_STATIC_CALL_NUM             402
#define IDB_BTN_STOPSELFTEST_1          402
#define IDC_STATIC_CALLNUM              402
#define IDC_STATIC_MT_BITRATE           403
#define IDC_STATIC_MTBITRATE            403
#define IDB_BTN_SELFTEST_4              405
#define IDD_DIALOG_CHECK                406
#define IDC_EDIT_DELAYTIME              406
#define IDC_STATIC_POLLEDMT             407
#define IDD_DIALOG_PSW                  407
#define IDC_LIST_GROUP                  408
#define IDR_MENU_HELP                   408
#define IDC_BTN_MODIFY                  409
#define IDD_DIALOG_ADDRCFG              410
#define IDD_DIALOG_ADDRMANAGE           410
#define IDC_EDIT_GROUP                  412
#define IDR_MENU_ADDR                   412
#define IDD_DIALOG_ADDR_MTINFO          413
#define IDC_STATIC_REGION               413
#define IDD_DIALOG_ADDR_GROUPINFO       414
#define IDD_DIALOG_ADDR_ADDTOGROUP      415
#define IDD_DIALOG_SELECTMT             416
#define IDD_DIALOG_SELSINGLE            418
#define IDC_LIST1                       419
#define IDC_LIST_FILELSIT               419
#define IDC_LIST_MT_FROM                419
#define IDC_LIST_ALLMTGROUP             419
#define IDD_DIALOG_FTPDOWNLOAD          419
#define IDC_ADD_MT                      420
#define IDC_LIST_BACK                   420
#define IDC_DEL_MT                      421
#define IDI_ICON_SHOW                   421
#define IDC_SAVE                        422
#define IDR_MENU_VMP                    422
#define IDC_MCU_IPADDRESS               423
#define IDD_DIALOG_NETCFG               423
#define IDC_EDIT1                       424
#define IDC_EDIT_FILEPATH               424
#define IDC_EDIT_CHECKTIME              424
#define IDC_CUSHION_TIME                424
#define IDC_PASSWORD                    424
#define IDC_AUDIENCE_NUM                424
#define IDC_EDIT_PSW                    424
#define IDC_EDIT1_GROUPNAME             424
#define IDC_EDIT_FIND                   424
#define IDC_EDIT_SERVER                 424
#define IDC_EDIT_CUSHIONTIME            424
#define IDC_EDIT_MSGBOARD               424
#define IDC_EDIT_NETCFGPWD              424
#define IDC_CHECK_OVERLAY               425
#define IDC_EDIT_PSW2                   425
#define IDC_EDIT_AUTOCALLRATE           425
#define IDC_CHK_OVERLAY                 425
#define IDC_EDIT_CFGPWD                 425
#define IDD_CONFLIST_DLG                426
#define IDC_EDIT_DATACONFPSW            426
#define IDC_EDIT_ENTERPSW               426
#define IDC_EDIT_AUTOCALLRATE2          426
#define IDC_TRSAGAIN_RECEIVE_CHB        427
#define IDD_DIALOG_ADDRENTRY            427
#define IDC_CHK_RECEIVE                 427
#define IDC_EDIT_AUTOCALLRATE3          427
#define IDC_OVERTIME_TIME               428
#define IDC_EDIT_OVERTIME               428
#define IDC_CHECK_POINT3                429
#define IDB_BITMAPMONITOR               429
#define IDC_EDIT_POINT3                 429
#define IDC_CHECK_POINT1                430
#define IDC_EDIT_POINT1                 430
#define IDB_DIRECTION                   430
#define IDC_CHECK_POINT2                431
#define IDC_EDIT_POINT2                 431
#define IDD_DIALOG_CONFDELAY            431
#define IDC_RETRANSFER_BTN              432
#define IDD_DIALOG_DCSHARE              432
#define IDC_EDIT_POINT4                 432
#define IDC_EDIT_RECVPACKAGES           432
#define IDC_BUTTON_VMPER1               433
#define IDC_EDIT_POINT5                 433
#define IDC_EDIT_SENDPACKAGES           433
#define IDC_BUTTON_VMPER2               434
#define IDD_DIALOG_DCWHITEBOARD         434
#define IDC_BUTTON_VMPER3               435
#define IDC_BTN_START                   435
#define IDC_BUTTON_VMPER4               436
#define IDC_BUTTON_VMPER5               437
#define IDC_COMBO_VMPSTYLE              437
#define IDR_MENU_MONITOR                437
#define IDC_BUTTON_VMPER6               438
#define IDC_STATIC_VMPSTYLE             438
#define IDB_BITMAP1                     438
#define IDC_BUTTON_VMPER7               439
#define IDC_VMPBTN_1                    439
#define IDB_BITMAP2                     439
#define IDC_BUTTON_VMPER8               440
#define IDC_VMPBTN_2                    440
#define IDB_BITMAP3                     440
#define IDC_BUTTON_VMPER9               441
#define IDC_VMPBTN_3                    441
#define IDB_BITMAP4                     441
#define IDC_BUTTON_VMPER10              442
#define IDC_VMPBTN_4                    442
#define IDB_BITMAP5                     442
#define IDC_BUTTON_VMPER11              443
#define IDC_VMPBTN_5                    443
#define IDB_BITMAP6                     443
#define IDC_BUTTON_VMPER12              444
#define IDC_VMPBTN_6                    444
#define IDB_BITMAP7                     444
#define IDC_BUTTON_VMPER13              445
#define IDC_VMPBTN_7                    445
#define IDB_BITMAP8                     445
#define IDC_BUTTON_VMPER14              446
#define IDC_VMPBTN_8                    446
#define IDB_BITMAP9                     446
#define IDC_BUTTON_VMPER15              447
#define IDC_VMPBTN_9                    447
#define IDB_BITMAP10                    447
#define IDC_BUTTON_VMPER16              448
#define IDC_VMPBTN_10                   448
#define IDB_BITMAP11                    448
#define IDC_STATIC_GROUP                449
#define IDC_VMPBTN_11                   449
#define IDB_BITMAP12                    449
#define IDC_STATIC_CONFGROUP            449
#define IDC_BUTTON_DATA_WBOARD          450
#define IDC_VMPBTN_12                   450
#define IDB_BITMAP13                    450
#define IDC_BUTTON_FILE_TRANSFER        451
#define IDC_VMPBTN_13                   451
#define IDB_BITMAP14                    451
#define IDC_BUTTON_DATA_SHARE           452
#define IDC_VMPBTN_14                   452
#define IDB_BITMAP15                    452
#define IDC_BUTTON_DATA_CHAT            453
#define IDC_VMPBTN_15                   453
#define IDB_BITMAP16                    453
#define IDC_IPADDRESS_SERVER            454
#define IDC_VMPBTN_16                   454
#define IDB_BITMAP17                    454
#define IDC_BUTTON_HANGUP               455
#define IDC_CHK_BROADCASTSTREAM         455
#define IDB_BITMAP18                    455
#define IDC_BUTTON_WBOARDV12            456
#define IDB_BITMAP19                    456
#define IDC_STATIC_STATE                457
#define IDC_STATIC_RECT                 457
#define IDB_BITMAP20                    457
#define IDC_COMBO_NEWCONFTYPE           458
#define IDB_BITMAP21                    459
#define IDC_STATIC_MODE                 460
#define IDB_BITMAP22                    460
#define IDC_STATIC_OUT                  461
#define IDB_BITMAP23                    461
#define IDC_STATIC_OUT2                 462
#define IDC_STATIC_IN                   462
#define IDC_STATIC_TITLE                462
#define IDB_BITMAP24                    462
#define IDC_STATIC1                     463
#define IDC_GROUP_ENCODER               463
#define IDC_GROUP_VIDEOPARAM            463
#define IDC_STATIC2                     464
#define IDC_STATIC_MEDIASOURCE          464
#define IDC_STATIC3                     465
#define IDC_STATIC_FILEPATH             465
#define IDC_STATIC4                     466
#define IDC_STATIC_AFORMAT              466
#define IDC_STATIC_VIDEOFORMAT          466
#define IDC_STATIC5                     467
#define IDC_COMBO_ADDR_GROUP            467
#define IDC_STATIC_AENCVOLUMN           467
#define IDB_BITMAP_SPEAK1               467
#define IDC_STATIC_AUDIOFORMAT          467
#define IDC_STATIC6                     468
#define IDC_COMBO_ADDR_GROUP2           468
#define IDC_STATIC_VFORMAT              468
#define IDB_BITMAP_CALL1                468
#define IDC_STATIC_VIDEORESOLUTION      468
#define IDC_STATIC7                     469
#define IDC_STATIC_VRESOLUTION          469
#define IDB_BITMAP_INVITE1              469
#define IDC_STATIC8                     470
#define IDC_STATIC_VBITRATE             470
#define IDB_BITMAP_CHAIRMAN1            470
#define IDC_STATIC9                     471
#define IDC_STATIC_VFRAMERATE           471
#define IDB_BITMAP_QUIT1                471
#define IDC_STATIC10                    472
#define IDC_STATIC_MAXNETBANDWIDTH      472
#define IDB_BITMAP_MONITOR3             472
#define IDC_STATIC11                    473
#define IDC_STATIC_MAXKEYFRAMERATE      473
#define IDB_BITMAP_MONITOR2             473
#define IDC_STATIC12                    474
#define IDC_STATIC_MINQUANPARAM         474
#define IDB_BITMAP_MONITOR1             474
#define IDC_STATIC13                    475
#define IDC_STATIC_MAXQUANPARAM         475
#define IDB_BITMAP_DATACONF3            475
#define IDC_STATIC14                    476
#define IDC_GROUP_DECODER               476
#define IDB_BITMAP_DATACONF2            476
#define IDC_STATIC_MINQUANPARAM2        476
#define IDC_STATIC_H264MAXKEYFRAMERATE  476
#define IDC_STATIC15                    477
#define IDC_STATIC_ADECVOLUMN           477
#define IDB_BITMAP_DATACONF1            477
#define IDC_STATIC_MINQUANPARAM3        477
#define IDC_STATIC_H264MINQUANPARAM     477
#define IDC_BTN_GETPATH                 478
#define IDB_BITMAP_CLOSE3               478
#define IDC_BUTTON_DBVIEW               479
#define IDB_BITMAP_CLOSE2               479
#define IDC_BTN_GETPATH2                479
#define IDC_STATIC_H264MAXQUANPARAM     479
#define IDC_STATIC_DBVIEW               480
#define IDB_BITMAP_CLOSE1               480
#define IDC_DBVIEW                      481
#define IDC_PIC_DBVIEW                  481
#define IDB_BITMAP_SYSTEM3              481
#define IDB_BITMAP_SYSTEM2              482
#define IDC_STATIC_TIME                 483
#define IDB_BITMAP_SYSTEM1              483
#define IDC_EDIT_TIMES                  484
#define IDB_BITMAP_MONITORBTN9          484
#define IDC_CHECK_VMP                   485
#define IDC_CHK_VMP                     485
#define IDB_BITMAP_MONITORBTN2          485
#define IDC_CHECK_VAC                   486
#define IDC_IPADDRESS_TRAP              486
#define IDC_CHK_VAC                     486
#define IDC_IP_TRAP                     486
#define IDB_BITMAP_MONITORBTN4          486
#define IDC_CHECK_MIX                   487
#define IDC_EDIT_NAME                   487
#define IDC_EDIT_COMNAME                487
#define IDC_CHK_MIX                     487
#define IDB_BITMAP_MONITORBTN6          487
#define IDC_EDIT_PACKEDPSW              488
#define IDC_CHK_DATACONF                488
#define IDB_BITMAP_MONITORBTN8          488
#define IDC_EDIT_PACKEDPORT             489
#define IDB_BITMAP_MONITORBTN1          489
#define IDC_EDIT_TTL                    489
#define IDC_EDIT_CHANNELNAME            490
#define IDB_BITMAP_CHAIRMAN3            490
#define IDC_IPADDRESS_PACKED            491
#define IDC_IP_PACKET                   491
#define IDB_BITMAP_SPEAK3               491
#define IDC_BUTTON_CANCEL               492
#define IDB_BITMAP_CALL2                492
#define IDC_EDIT_MCPORT                 492
#define IDC_STATIC_AV                   493
#define IDB_BITMAP_CALL3                493
#define IDB_BITMAP_QUIT2                494
#define IDC_LIST_CODEC                  495
#define IDB_BITMAP_QUIT3                495
#define IDC_LIST_MTADDR                 496
#define IDB_BITMAP_INVITE2              496
#define IDC_BUTTON_NEW                  497
#define IDB_BITMAP_INVITE3              497
#define IDC_BUTTON_NEWGROUP             498
#define IDB_BITMAP_CHAIRMAN2            498
#define IDC_BUTTON_DEL                  499
#define IDB_BITMAP_SPEAK2               499
#define IDC_BUTTON_DELGROUP             500
#define IDB_BITMAP_ADDR3                500
#define IDC_BUTTON_NEXTONE              501
#define IDC_STATIC_MODESEL              501
#define IDB_BITMAP_ADDR2                501
#define IDC_BUTTON_ADDGROUP             502
#define IDB_BITMAP_ADDR1                502
#define IDC_BUTTON_EXITGROUP            503
#define IDB_BITMAP_FULLSCREEN3          503
#define IDC_IPADDRESS_MCU               504
#define IDB_BITMAP_FULLSCREEN2          504
#define IDB_BITMAP_FULLSCREEN1          505
#define IDC_STATIC_MCUIP                506
#define IDB_BITMAP_LOOP3                506
#define IDC_STATIC_GROUPNAME            507
#define IDB_BITMAP_CONFIG2              507
#define IDC_BUTTON_SELALL               508
#define IDB_BITMAP_CONFIG3              508
#define IDC_BUTTON_SELONE               509
#define IDB_BITMAP_STATISTICS1          509
#define IDC_COMBO_MCU                   510
#define IDB_BITMAP_STATISTICS2          510
#define IDB_BITMAP_STATISTICS3          511
#define IDC_COMBO_CONFRATE              512
#define IDB_BITMAP_SNAP1                512
#define IDC_STATIC_D                    513
#define IDC_COMBO_ENCRYPT               513
#define IDB_BITMAP_SNAP2                513
#define IDC_STATIC_ADDR                 514
#define IDB_BITMAP_SNAP3                514
#define IDC_SEARCH_GROUP                515
#define IDC_BTN_CANCEL2                 515
#define IDB_BITMAP_LOOP1                515
#define IDC_ENTRY_GROUP                 516
#define IDB_BITMAP_LOOP2                516
#define IDC_GROUP_GROUP                 517
#define IDC_STATIC_AVSOURCE_CHAIR       517
#define IDB_BITMAP_CONFIG1              517
#define IDC_SERVER_GROUP                518
#define IDC_AVSOURCE_CHAIR              518
#define IDB_BITMAP_QUIET3               518
#define IDC_APP_GROUP                   519
#define IDB_BITMAP_MUTE2                519
#define IDB_BITMAP_MUTE3                520
#define IDC_EDIT_USER                   521
#define IDB_BITMAP_QUIET1               521
#define IDC_EDIT_PASSWORD               522
#define IDB_BITMAP_QUIET2               522
#define IDC_BUTTON_DOWNLOAD             523
#define IDB_BITMAP_MUTE1                523
#define IDC_EDIT_FILENAME               524
#define IDB_DIALOG_LEFTBOTTOM           524
#define IDC_CHECK_SAVEPSW               525
#define IDB_DIALOG_BOTTOM               525
#define IDC_CHECK_MINISTART             526
#define IDC_CHK_MINISTART               526
#define IDB_DIALOG_RIGHT                526
#define IDC_CHECK_AVCHAIRMAN            527
#define IDC_CHK_AVCHAIRMAN              527
#define IDB_DIALOG_LEFT                 527
#define IDC_CHECK_ENCYPT                528
#define IDC_CHK_ENCRYPT                 528
#define IDB_DIALOG_RIGHTTOP             528
#define IDC_CHECK_H239                  529
#define IDC_CHK_H239                    529
#define IDB_DIALOG_RIGHTBOTTOM          529
#define IDB_DIALOG_LEFTTOP              530
#define IDB_DIALOG_TOP                  531
#define IDB_DIALOG_MLEFT                532
#define IDC_RADIO_MT                    533
#define IDB_DIALOG_MRIGHTBOTTOM         533
#define IDC_RADIO_MCU                   534
#define IDB_DIALOG_MLEFTTOP             534
#define IDC_STATIC_INFORMATION          535
#define IDB_DIALOG_MLEFTBOTTOM          535
#define IDC_STATIC_TYPE                 536
#define IDB_DIALOG_MBOTTOM              536
#define IDC_STATIC_BITRATE              537
#define IDB_DIALOG_MTOP                 537
#define IDC_IP_ADDRESS                  538
#define IDB_DIALOG_MRIGHT               538
#define IDB_DIALOG_MRIGHTTOP            539
#define IDC_STATIC_DCIPADDR             541
#define IDB_BITMAP_HELP3                541
#define IDC_IP_DCCALLEDADDR             542
#define IDB_BITMAP_CREATECONF2          542
#define IDC_STATIC_DCCALLINFO           543
#define IDB_BITMAP_CREATECONF3          543
#define IDB_BITMAP_CREATECONF4          544
#define IDC_BTN_FULLSCREEN              545
#define IDB_BITMAP_HELP1                545
#define IDB_BITMAP_HELP2                546
#define IDC_BTN_CANCEL                  547
#define IDB_BITMAP_CREATECONF1          547
#define IDB_BITMAP_MAINBAR              548
#define IDB_BITMAP_EXITMONITOR3         549
#define IDB_BITMAP_EXITMONITOR2         550
#define IDB_BITMAP_EXITMONITOR1         551
#define IDC_STATIC_CFGSHEET             552
#define IDB_BITMAP_FULLMONITOR1         552
#define IDC_BTN_DEFAULT                 553
#define IDB_BITMAP_FULLMONITOR3         553
#define IDC_BTN_APPLY                   554
#define IDC_BTN_DEL                     554
#define IDB_BITMAP_FULLMONITOR2         554
#define IDC_BUTTON_CLOSE                555
#define IDC_BTN_SEARCH                  555
#define IDB_BITMAP_MAINFULL3            555
#define IDC_STATIC_MTLIST               556
#define IDC_BTN_ADD2                    556
#define IDB_BITMAP_MAINFULL2            556
#define IDC_BTN_DEL2                    557
#define IDB_BITMAP_MAINFULL1            557
#define IDC_BTN_MODIFY2                 558
#define IDB_BITMAP_SPEAK4               558
#define IDC_BTN_SEARCH2                 559
#define IDC_STATIC_REMOTEMONITORNAME    559
#define IDB_BITMAP_BTNBIG4              559
#define IDC_STATIC_LOCALMONITORNAME     560
#define IDB_BITMAP_QUIT4                561
#define IDB_BITMAP_INVITE4              562
#define IDC_STATIC_LOCALVIDEO           563
#define IDB_BITMAP_CHAIRMAN4            563
#define IDC_STATIC_REMOTEVIDEO          564
#define IDC_BTN_QUIT                    564
#define IDB_BITMAP_BTN1                 564
#define IDC_GROUP_DATACONFINFO          565
#define IDB_BITMAP_BTN2                 565
#define IDC_BTN_ADDMT                   566
#define IDB_BITMAP_BTN3                 566
#define IDC_STATIC_CALLTYPE             567
#define IDB_BITMAP_BTN4                 567
#define IDC_STATIC_ANSWERTYPE           568
#define IDB_BITMAP_BTNBIG1              568
#define IDC_GROUP_CALLCFG               569
#define IDB_BITMAP_BTNBIG2              569
#define IDC_STATIC_AUTOACALLIP          570
#define IDB_BITMAP_BTNBIG3              570
#define IDC_STATIC_AUTOCALLBITRATE      571
#define IDB_BITMAP_CALL4                571
#define IDC_STATIC_CHECKTIME            572
#define IDR_MENU_DATACONF               572
#define IDC_STATIC_AUTOACALLIP2         572
#define IDC_STATIC_CHANNELNAME          573
#define IDB_BITMAP_MONITORBAR           573
#define IDC_STATIC_AUTOCALLBITRATE2     573
#define IDC_STATIC_IP                   574
#define IDD_DIALOG_OSDCFG               574
#define IDC_STATIC_PORT                 575
#define IDD_DIALOG_GUIDECFG             575
#define IDC_STATIC_TTL                  575
#define IDC_STATIC_PSW                  576
#define IDD_DIALOG_ADVANCEVIDEOCFG      576
#define IDC_GROUP_PACKET                577
#define IDB_BITMAPMTIMAGELIST           577
#define IDC_GROUP_SEND                  578
#define IDB_BITMAP_MONITORBTN94         578
#define IDC_GROUP_RESTRANS              578
#define IDC_STATIC_MCPORT               578
#define IDC_STATIC_CUSHIONTIME          579
#define IDB_BITMAP_MONITORBTN14         579
#define IDC_GROUP_RECEIVE               580
#define IDB_BITMAP_MONITORBTN22         580
#define IDC_STATIC_POINT1               581
#define IDB_BITMAP_MONITORBTN24         581
#define IDC_STATIC_DISCARD              582
#define IDB_BITMAP_MONITORBTN42         582
#define IDC_STATIC_POINT2               583
#define IDB_BITMAP_MONITORBTN44         583
#define IDC_STATIC_POINT3               584
#define IDB_BITMAP_MONITORBTN62         584
#define IDC_GROUP_NETCFG                585
#define IDC_STATIC_POINT4               585
#define IDB_BITMAP_MONITORBTN64         585
#define IDC_STATIC_RECVPACKAGES         585
#define IDC_STATIC_LOCALIP              586
#define IDC_STATIC_POINT5               586
#define IDB_BITMAP_MONITORBTN82         586
#define IDC_STATIC_SENDPACKAGES         586
#define IDC_STATIC_NETTYPE              587
#define IDB_BITMAP_MONITORBTN84         587
#define IDC_STATIC_RECVPORT             588
#define IDB_BITMAP_MONITORBTN92         588
#define IDC_STATIC_UPBANDWIDTH          589
#define IDB_BITMAP_MONITORBTN12         589
#define IDC_STATIC_DOWNBANDWIDTH        590
#define IDD_DIALOG_MTOSDCFG             590
#define IDC_STATIC_SENDINITPORT         591
#define IDD_DIALOG_MTGUIDECFG           591
#define IDC_GROUP_SNMP                  592
#define IDD_DIALOG_VIDEOADVANCECFG      592
#define IDC_STATIC_TRAPADDR             593
#define IDC_STATIC_LOCALIP2             594
#define IDD_DIALOG_DCMTCALL             594
#define IDC_STATIC_COMMON               595
#define IDB_BITMAP_MONITOR94            595
#define IDC_COMBO_VFRAMERATEUNIT        596
#define IDB_BITMAP_MONITOR14            596
#define IDC_STATIC_PROMTP               597
#define IDB_BITMAP_MONITOR22            597
#define IDB_BITMAP_MONITOR24            598
#define IDB_BITMAP_MONITOR42            599
#define IDB_BITMAP_MONITOR44            600
#define IDB_BITMAP_MONITOR62            601
#define IDC_TAB_MAIN                    602
#define IDB_BITMAP_MONITOR64            602
#define IDC_BUTTON2                     603
#define IDB_BITMAP_MONITOR82            603
#define IDC_BTN_LABEL                   603
#define IDC_BTN_H323Cfg                 603
#define IDB_BITMAP_MONITOR84            604
#define IDB_BITMAP_MONITOR92            605
#define IDB_BITMAP_MONITOR12            606
#define IDB_BITMAP_RADIOUNSEL2          608
#define IDB_BITMAP_RADIOSEL1            609
#define IDB_BITMAP_RADIOSEL2            610
#define IDB_BITMAP_RADIOUNSEL1          611
#define IDB_BITMAP_MTLIST               612
#define IDB_BITMAP_LR                   613
#define IDB_BITMAP_HR                   614
#define IDB_BITMAP_LL                   615
#define IDB_BITMAP_HL                   616
#define IDC_STATIC_VIDEO1               618
#define IDC_STATIC_MONITORPANEL         619
#define IDC_STATIC_LOCALCFG             620
#define IDC_STATIC_ALIAS                621
#define IDC_STATIC_E164                 622
#define IDC_STATIC_MTTYPE               623
#define IDC_STATIC_ENTERPWD             624
#define IDC_STATIC_VIDEO2               625
#define IDC_STATIC_SETPWD               625
#define IDC_STATIC_VIDEO3               626
#define IDC_STATIC_CONFIRM              626
#define IDC_STATIC_VIDEO4               627
#define IDC_BTN_CFGCANCEL               627
#define IDC_STATIC_VIDEO5               628
#define IDC_STATIC_VIDEO6               629
#define IDC_STATIC_VIDEO7               630
#define IDC_STATIC_VIDEO8               631
#define IDC_STATIC_VIDEO9               632
#define IDC_DCMTCTRL                    632
#define IDC_IP_MCU                      634
#define IDC_IP_MT                       635
#define IDC_STATIC_ENCRYPT              636
#define IDC_STATIC_BROADCASTBAR         637
#define IDC_LIST4                       640
#define IDC_PIC_BROADCAST               641
#define IDC_PIC_MAINBROADCAST           641
#define IDC_PIC_RIGHTMIDDLE             642
#define IDC_PIC_RIGHT                   643
#define IDC_IPADDRESS1                  644
#define IDC_IPADDRESS2                  645
#define IDC_IP_MASK                     645
#define IDC_RADIO1                      646
#define IDC_RADIO_QUALITY               646
#define IDC_RADIO_SINGLE                646
#define IDC_RADIO_H323                  646
#define IDC_RADIO_AES                   646
#define IDC_RADIO_REJECT                646
#define IDC_RADIO2                      647
#define IDC_RADIO_SPEED                 647
#define IDC_RADIO_OWNSCREEN             647
#define IDC_RADIO_H320                  647
#define IDC_RADIO_DES                   647
#define IDC_RADIO3                      648
#define IDC_RADIO_AUTO                  648
#define IDC_RADIO_SIP                   648
#define IDC_RADIO4                      649
#define IDC_RADIO_MANUAL                649
#define IDC_RADIO_ENGLISH               649
#define IDC_RADIO5                      650
#define IDC_RADIO_LOSTQUALITY           650
#define IDC_RADIO_OFF                   650
#define IDC_RADIO_CHINESE               650
#define IDC_RADIO6                      651
#define IDC_RADIO_NORMAL                651
#define IDC_STATIC_ENCODESTRATEGY       652
#define IDC_STATIC_LOSTPACKAGERESTORE   653
#define IDC_GROUP_ENCODE                654
#define IDC_GROUP_RETRANSFER            655
#define IDC_RADIO_FAST                  656
#define IDC_RADIO_SLOW                  657
#define IDC_GROUP_H264                  658
#define IDC_STATIC_LABELTYPE            659
#define IDC_STATIC_DVIDEOSHOWMODE       660
#define IDC_GROUP_MODE                  661
#define IDC_GROUP_LABELTYPE             662
#define IDC_GROUP                       663
#define IDC_GROUP_PROTOCOL              663
#define IDC_STATIC_MASK                 664
#define IDC_STATIC_CONFPROTOCOL         665
#define IDC_STATIC_LANGUAGE             666
#define IDC_GROUP_LANGUAGE              667
#define IDC_EDIT_ALIAS                  668
#define IDC_STATIC_SLEEPTIME            669
#define IDC_EDIT_SLEEPTIME              670
#define IDC_IP_CALL                     671
#define IDC_IP_TERMINAL                 672
#define IDC_STATIC_BROADCAST            673
#define IDC_STATIC_NOT                  674
#define IDC_STATIC_WAITING              675
#define IDC_CHK_SAVE                    676
#define IDC_STATIC_INPUTPWD             677
#define IDC_STATIC_ALLGROUP             678
#define IDC_STATIC_CURGROUP             679
#define IDC_STATIC_FILESETUP            680
#define IDC_STATIC_ANSWERED             681
#define IDC_STATIC_NOTANSWERED          682
#define IDC_STATIC_HISTORY              683
#define IDC_CHK_H320                    685
#define IDC_CHK_SIP                     686
#define IDC_STATIC_NETCFGPWD            687
#define IDC_STATIC_CFGPWD               688
#define IDC_STATIC_TIMES                688
#define IDC_STATIC_MTAVAILBLE           689
#define IDC_STATIC_MTSELECTED           690
#define IDC_STATIC_HOST                 691
#define IDC_STATIC_FILENAME             692
#define IDC_EDIT_ADDR_MM_MT             693
#define IDC_STATIC_USERNAME             693
#define IDC_BUTTON_ADDR_MM_FIND         694
#define IDC_STATIC_PASSWORD             694
#define IDC_EDIT_ADDR_MM_MT2            695
#define IDC_STATIC_ALLPOLLEDMT          695
#define IDC_BUTTON_ADDR_MM_FIND2        696
#define IDC_STATIC_CURRENTMT            696
#define IDC_STATIC_POLLINTERVAL         697
#define IDC_STATIC_MEDIAMODE            698
#define IDC_STATIC_MT_AVAILABLE         699
#define IDC_STATIC_MT_SELECTED          700
#define IDC_STATIC_FIND                 701
#define ID_EXIT                         1003
#define EXIT                            1003
#define IDC_EDIT_CONFNAME               1051
#define IDC_CHECK_OPENTYPE              1052
#define IDC_EDIT_DATACONFNAME           1052
#define IDC_CHECK_IMMEDIATE             1053
#define IDC_RADIO_NORMALMODE            1054
#define IDC_RADIO_HDMODE                1055
#define IDC_EDIT_CONFBITRATE            1056
#define IDC_EDIT_DURATIONH              1057
#define IDC_EDIT_DURATIONM              1058
#define IDC_LIST_SELMT                  1062
#define IDC_BUTTON_ADDONE               1063
#define IDC_BUTTON_ADDALL               1064
#define IDC_BUTTON_DELONE               1065
#define IDC_BUTTON_DELALL               1066
#define IDC_EDIT_ROLLTIMES              1072
#define IDC_BUTTON_SELFILE              1074
#define IDC_BUTTON_ADDSTOCKMSG          1075
#define IDC_BUTTON_DELSTOCKMSG          1076
#define IDC_COMBO_STOCKMSG              1077
#define IDC_EDIT_POLLINTERVAL           1081
#define IDC_RADIO_POLLVCB               1082
#define IDC_RADIO_POLLVCS               1083
#define IDC_BANDWIDTH                   1150
#define IDC_BANDWIDTH_LOCAL             1151
#define IDC_MTALIAS                     1158
#define IDC_MTNUMBER                    1159
#define IDC_RCVSTARTPORT                1163
#define IDC_EDIT_RCVSTARTPORT           1163
#define IDC_SENDSTARTPORT               1164
#define IDC_EDIT_SENDSTARTPORT          1164
#define IDC_EDIT_VFRAMERATE             1165
#define IDC_UPLOAD_BW                   1165
#define IDC_EDIT_UPLOADBW               1165
#define IDC_EDIT_VBITRATE               1166
#define IDC_DOWNLOAD_BW                 1166
#define IDC_EDIT_DOWNLOADBW             1166
#define IDC_EDIT_VBANDWIDTH             1167
#define IDC_EDIT_MAXNETBANDWIDTH        1167
#define IDC_EIDT_VIKEYRATE              1168
#define IDC_EIDT_VKEYRATE               1168
#define IDC_EDIT_VQUALMAXVALUE          1169
#define IDC_EDIT_VQUANMAXVALUE          1169
#define IDC_EDIT_VQUALMINVALUE          1170
#define IDC_EDIT_VQUANMINVALUE          1170
#define IDC_EDIT_ASAMPLERATE            1171
#define IDC_EIDT_H264VKEYRATE           1171
#define IDC_EDIT_ABITRATE               1172
#define IDC_EDIT_H264VQUANMINVALUE      1172
#define IDC_EDIT_AVOLUMN                1173
#define IDC_EDIT_AENCVOLUMN             1173
#define IDC_EDIT_H264VQUANMAXVALUE      1173
#define IDC_MTTYPE                      1215
#define IDC_COMBO_MTTYPE                1215
#define IDC_MTPOSITION                  1216
#define IDC_NET_TYPE                    1216
#define IDC_COMBO_NETTYPE               1216
#define ID_MENU_APPLYSPEAKER            32768
#define ID_MENU_APPLYCHAIRMAN           32769
#define ID_MENU_QUITCONF                32770
#define ID_MENU_SPECSPEAKER             32771
#define ID_MENU_CANCELSPEAKER           32773
#define ID_MENU_CANCELCHAIRMAN          32774
#define ID_MENU_DELETEMT                32775
#define ID_MENU_SELLOOKMT               32776
#define ID_MENU_LOOPLOOK                32777
#define ID_MENU_LOOPSPEAK               32778
#define ID_MENU_FARMUTE                 32779
#define ID_MENU_FARDUMB                 32780
#define ID_MENU_EXTENDCONF              32781
#define ID_MENU_SETCONFMODE             32782
#define ID_MENU_SENDMESSAGE             32783
#define ID_MENU_UNDO                    32784
#define ID_MENU_CUT                     32785
#define ID_MENU_COPY                    32786
#define ID_MENU_PASTE                   32787
#define ID_MENU_DELETE                  32788
#define ID_MENU_SELALL                  32789
#define ID_MENU_CLEARALL                32790
#define ID_MENU_STOPMONITOR             32791
#define ID_MENU_REALTIMEMONITOR         32792
#define ID_MENU_SIZEX1                  32795
#define ID_MENU_SIZEX2                  32796
#define ID_MENU_SIZEX3                  32797
#define ID_MENU_NOFARMUTE               32798
#define ID_MENU_NOFARDUMB               32799
#define ID_MENU_RELEASECONF             32800
#define ID_MENU_SPECCHAIRMAN            32801
#define ID_MENU_FULLSCREEN              32802
#define ID_MENU_PREVIEW                 32803
#define ID_MENU_CALL                    32804
#define ID_MENU_SNAPSHOT                32806
#define ID_MENU_KEYFRAME                32807
#define ID_MENU_CONF_VAC                32808
#define ID_MENU_CONF_VMPER              32809
#define ID_MENU_SWITCH                  32810
#define ID_MENU_PREOPEN                 32811
#define ID_MENU_APPLYCHIME              32812
#define ID_MENU_HELP                    32813
#define ID_MENU_ABOUT                   32814
#define ID_MENU_CONFIG                  32815
#define ID_MENU_ADDR_ADD                32816
#define IDC_MENU_ADDR_DEL               32817
#define IDC_MENU_ADDR_MODIFY            32818
#define IDC_MENU_ADDR_CALL              32819
#define IDC_MENU_ADDR_ADDGROUP          32820
#define IDC_MENU_ADDR_EXITGROUP         32821
#define IDR_STOPMONITOR_MENU            32821
#define ID_MENU_ADDR_ADDGROUP           32822
#define IDR_MUTEMONITOR_MENU            32822
#define ID_MENU_ADDR_DELGROUP           32823
#define IDR_REALMONITOR_MENU            32823
#define ID_MENU_STARTMONITOR            32824
#define IDR_MONITORINFO_MENU            32824
#define ID_MENU_SHOWWINDOW              32825
#define IDR_FULLSCREEN_MENU             32825
#define ID_MENU_EXIT                    32826
#define IDR_RESTORE_MENU                32826
#define IDM_MCS_SPECIFY                 32827
#define IDM_FOLLOW_SPEAKER              32828
#define IDR_SNAP_MENU                   32828
#define IDM_FOLLOW_CHAIRMAN             32829
#define IDM_FOLLOW_POLL                 32830
#define IDM_STOP_VMP                    32831
#define IDC_MENU_STARTSHARE             32832
#define IDC_MENU_STARTWHITEBOARD        32833
#define ID_MENU_DATACONFOUT             32834
#define ID_MENU_INVITEMT                32836
#define ID_MENU_STARTSHARE              32837
#define ID_MENU_STARTWHITEBOARD         32838
#define ID_MENU_STARTFT                 32839
#define IDC_MENU_CHINESE                32840
#define IDC_MENU_ENGLISH                32841
#define ID_MENU_STARTCHAT               32842


//tab页宏
#define CFG_LOCAL           0
#define CFG_NET             1
#define CFG_CALL            2
#define CFG_VIDEO           3
#define CFG_RESEND          4
#define CFG_PANEL           5
#define CFG_OSD             6

//呼叫类型宏定义
#define CAll_TYPE_IP        1
#define CALL_TYPE_E164      2
#define CAll_TYPE_H323ID    3


//配置文件名定义
#define TESTCFG_FILENAME	"PcmtGuiTest.ini"
	
//检验返回值
#define PCMTUI_CHECK_RET(p)	if(!p) { return FALSE; }

//检验句柄是否合法, 不合法则直接返回FALSE
#define PCMTUI_CHECK_HANDLE_RET(hWnd) if( hWnd == NULL ){ return FALSE; }

//销毁弹出菜单
#define PCMTUI_DESTROY_MENU(p)														\
	if (!p)																			\
	{																				\
		m_cGuiUnit.MouseMove(m_hBtnHelp);											\
		m_cGuiUnit.MouseLClick();													\
		return FALSE;																\
	}

//等待500ms
#define PCMTUI_SLEEP_500		m_bDelay ? Sleep(500) : NULL

//等待1s
#define PCMTUI_SLEEP_1000	m_bDelay ? Sleep(1000) : NULL

//为了实现界面正常操作而必须作的延时
#define PCMTUI_SLEEP_SYS		Sleep(500)

//应用程序名
#define PCMTUI_APP_TITLE_NAME	_T("科达科技桌面终端4.0")
#define PCMTUI_APP_EXE_NAME		_T("pcmtcontainer.exe")

#endif
